// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// ziskasrules
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of rule1_V
//        bit 31~0 - rule1_V[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of rule2_V
//        bit 31~0 - rule2_V[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of rule3_V
//        bit 31~0 - rule3_V[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of rule1cnt_V
//        bit 31~0 - rule1cnt_V[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of rule2cnt_V
//        bit 31~0 - rule2cnt_V[31:0] (Read/Write)
// 0x34 : reserved
// 0x38 : Data signal of rule3cnt_V
//        bit 31~0 - rule3cnt_V[31:0] (Read/Write)
// 0x3c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XMY_IP_HLS_ZISKASRULES_ADDR_RULE1_V_DATA    0x10
#define XMY_IP_HLS_ZISKASRULES_BITS_RULE1_V_DATA    32
#define XMY_IP_HLS_ZISKASRULES_ADDR_RULE2_V_DATA    0x18
#define XMY_IP_HLS_ZISKASRULES_BITS_RULE2_V_DATA    32
#define XMY_IP_HLS_ZISKASRULES_ADDR_RULE3_V_DATA    0x20
#define XMY_IP_HLS_ZISKASRULES_BITS_RULE3_V_DATA    32
#define XMY_IP_HLS_ZISKASRULES_ADDR_RULE1CNT_V_DATA 0x28
#define XMY_IP_HLS_ZISKASRULES_BITS_RULE1CNT_V_DATA 32
#define XMY_IP_HLS_ZISKASRULES_ADDR_RULE2CNT_V_DATA 0x30
#define XMY_IP_HLS_ZISKASRULES_BITS_RULE2CNT_V_DATA 32
#define XMY_IP_HLS_ZISKASRULES_ADDR_RULE3CNT_V_DATA 0x38
#define XMY_IP_HLS_ZISKASRULES_BITS_RULE3CNT_V_DATA 32

