// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _my_ip_hls_HH_
#define _my_ip_hls_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "my_ip_hls_entry3.h"
#include "my_ip_hls_entry90.h"
#include "Block_codeRepl6_proc.h"
#include "okanonas82.h"
#include "okanonas83.h"
#include "okanonas.h"
#include "ps2ip_fifo.h"
#include "core.h"
#include "okanonas284.h"
#include "okanonas285.h"
#include "okanonas2.h"
#include "ip2ps_fifo.h"
#include "fifo_w32_d1_A.h"
#include "fifo_w32_d2_A.h"
#include "fifo_w32_d64_A.h"
#include "fifo_w4_d64_A.h"
#include "fifo_w1_d64_A.h"
#include "start_for_my_ip_hbkb.h"
#include "start_for_Block_ccud.h"
#include "start_for_okanonadEe.h"
#include "start_for_okanonaeOg.h"
#include "start_for_okanonafYi.h"
#include "start_for_okanonag8j.h"
#include "start_for_okanonahbi.h"
#include "start_for_okanonaibs.h"
#include "start_for_ip2ps_fjbC.h"
#include "my_ip_hls_ziskasrules_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_ZISKASRULES_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_ZISKASRULES_DATA_WIDTH = 32>
struct my_ip_hls : public sc_module {
    // Port declarations 29
    sc_in< sc_logic > s_axi_ziskasrules_AWVALID;
    sc_out< sc_logic > s_axi_ziskasrules_AWREADY;
    sc_in< sc_uint<C_S_AXI_ZISKASRULES_ADDR_WIDTH> > s_axi_ziskasrules_AWADDR;
    sc_in< sc_logic > s_axi_ziskasrules_WVALID;
    sc_out< sc_logic > s_axi_ziskasrules_WREADY;
    sc_in< sc_uint<C_S_AXI_ZISKASRULES_DATA_WIDTH> > s_axi_ziskasrules_WDATA;
    sc_in< sc_uint<C_S_AXI_ZISKASRULES_DATA_WIDTH/8> > s_axi_ziskasrules_WSTRB;
    sc_in< sc_logic > s_axi_ziskasrules_ARVALID;
    sc_out< sc_logic > s_axi_ziskasrules_ARREADY;
    sc_in< sc_uint<C_S_AXI_ZISKASRULES_ADDR_WIDTH> > s_axi_ziskasrules_ARADDR;
    sc_out< sc_logic > s_axi_ziskasrules_RVALID;
    sc_in< sc_logic > s_axi_ziskasrules_RREADY;
    sc_out< sc_uint<C_S_AXI_ZISKASRULES_DATA_WIDTH> > s_axi_ziskasrules_RDATA;
    sc_out< sc_lv<2> > s_axi_ziskasrules_RRESP;
    sc_out< sc_logic > s_axi_ziskasrules_BVALID;
    sc_in< sc_logic > s_axi_ziskasrules_BREADY;
    sc_out< sc_lv<2> > s_axi_ziskasrules_BRESP;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<32> > slaveIn_TDATA;
    sc_in< sc_lv<4> > slaveIn_TSTRB;
    sc_in< sc_lv<1> > slaveIn_TLAST;
    sc_out< sc_lv<32> > masterOut_TDATA;
    sc_out< sc_lv<4> > masterOut_TSTRB;
    sc_out< sc_lv<1> > masterOut_TLAST;
    sc_in< sc_logic > slaveIn_TVALID;
    sc_out< sc_logic > slaveIn_TREADY;
    sc_out< sc_logic > masterOut_TVALID;
    sc_in< sc_logic > masterOut_TREADY;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    my_ip_hls(sc_module_name name);
    SC_HAS_PROCESS(my_ip_hls);

    ~my_ip_hls();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    my_ip_hls_ziskasrules_s_axi<C_S_AXI_ZISKASRULES_ADDR_WIDTH,C_S_AXI_ZISKASRULES_DATA_WIDTH>* my_ip_hls_ziskasrules_s_axi_U;
    my_ip_hls_entry3* my_ip_hls_entry3_U0;
    my_ip_hls_entry90* my_ip_hls_entry90_U0;
    Block_codeRepl6_proc* Block_codeRepl6_proc_U0;
    okanonas82* okanonas82_U0;
    okanonas83* okanonas83_U0;
    okanonas* okanonas_U0;
    ps2ip_fifo* ps2ip_fifo_U0;
    core* core_U0;
    okanonas284* okanonas284_U0;
    okanonas285* okanonas285_U0;
    okanonas2* okanonas2_U0;
    ip2ps_fifo* ip2ps_fifo_U0;
    fifo_w32_d1_A* rule1_V_c1_U;
    fifo_w32_d1_A* rule2_V_c2_U;
    fifo_w32_d1_A* rule3_V_c3_U;
    fifo_w32_d1_A* rule1cnt_V_c4_U;
    fifo_w32_d1_A* rule2cnt_V_c5_U;
    fifo_w32_d1_A* rule3cnt_V_c6_U;
    fifo_w32_d1_A* rule1_V_c_U;
    fifo_w32_d1_A* rule2_V_c_U;
    fifo_w32_d1_A* rule3_V_c_U;
    fifo_w32_d1_A* rule1cnt_V_c_U;
    fifo_w32_d1_A* rule2cnt_V_c_U;
    fifo_w32_d1_A* rule3cnt_V_c_U;
    fifo_w32_d1_A* rule3cnt_V_buf_c_U;
    fifo_w32_d1_A* rule2cnt_V_buf_c_U;
    fifo_w32_d1_A* rule1cnt_V_buf_c_U;
    fifo_w32_d2_A* regrule1_V_channel_U;
    fifo_w32_d2_A* regrule2_V_channel_U;
    fifo_w32_d2_A* regrule3_V_channel_U;
    fifo_w32_d64_A* ps2ipFifo_V_data_V_U;
    fifo_w4_d64_A* ps2ipFifo_V_strb_V_U;
    fifo_w1_d64_A* ps2ipFifo_V_last_V_U;
    fifo_w32_d1_A* rule1cnt_V_buf_c31_U;
    fifo_w32_d1_A* rule2cnt_V_buf_c32_U;
    fifo_w32_d1_A* rule3cnt_V_buf_c33_U;
    fifo_w32_d64_A* ip2psFifo_V_data_V_U;
    fifo_w4_d64_A* ip2psFifo_V_strb_V_U;
    fifo_w1_d64_A* ip2psFifo_V_last_V_U;
    start_for_my_ip_hbkb* start_for_my_ip_hbkb_U;
    start_for_Block_ccud* start_for_Block_ccud_U;
    start_for_okanonadEe* start_for_okanonadEe_U;
    start_for_okanonaeOg* start_for_okanonaeOg_U;
    start_for_okanonafYi* start_for_okanonafYi_U;
    start_for_okanonag8j* start_for_okanonag8j_U;
    start_for_okanonahbi* start_for_okanonahbi_U;
    start_for_okanonaibs* start_for_okanonaibs_U;
    start_for_ip2ps_fjbC* start_for_ip2ps_fjbC_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<32> > rule1_V;
    sc_signal< sc_lv<32> > rule2_V;
    sc_signal< sc_lv<32> > rule3_V;
    sc_signal< sc_lv<32> > rule1cnt_V;
    sc_signal< sc_lv<32> > rule2cnt_V;
    sc_signal< sc_lv<32> > rule3cnt_V;
    sc_signal< sc_logic > my_ip_hls_entry3_U0_ap_start;
    sc_signal< sc_logic > my_ip_hls_entry3_U0_ap_done;
    sc_signal< sc_logic > my_ip_hls_entry3_U0_ap_continue;
    sc_signal< sc_logic > my_ip_hls_entry3_U0_ap_idle;
    sc_signal< sc_logic > my_ip_hls_entry3_U0_ap_ready;
    sc_signal< sc_logic > my_ip_hls_entry3_U0_start_out;
    sc_signal< sc_logic > my_ip_hls_entry3_U0_start_write;
    sc_signal< sc_lv<32> > my_ip_hls_entry3_U0_rule1_V_out_din;
    sc_signal< sc_logic > my_ip_hls_entry3_U0_rule1_V_out_write;
    sc_signal< sc_lv<32> > my_ip_hls_entry3_U0_rule2_V_out_din;
    sc_signal< sc_logic > my_ip_hls_entry3_U0_rule2_V_out_write;
    sc_signal< sc_lv<32> > my_ip_hls_entry3_U0_rule3_V_out_din;
    sc_signal< sc_logic > my_ip_hls_entry3_U0_rule3_V_out_write;
    sc_signal< sc_lv<32> > my_ip_hls_entry3_U0_rule1cnt_V_out_din;
    sc_signal< sc_logic > my_ip_hls_entry3_U0_rule1cnt_V_out_write;
    sc_signal< sc_lv<32> > my_ip_hls_entry3_U0_rule2cnt_V_out_din;
    sc_signal< sc_logic > my_ip_hls_entry3_U0_rule2cnt_V_out_write;
    sc_signal< sc_lv<32> > my_ip_hls_entry3_U0_rule3cnt_V_out_din;
    sc_signal< sc_logic > my_ip_hls_entry3_U0_rule3cnt_V_out_write;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_ap_start;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_start_full_n;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_ap_done;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_ap_continue;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_ap_idle;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_ap_ready;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_start_out;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_start_write;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_rule1_V_read;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_rule2_V_read;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_rule3_V_read;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_rule1cnt_V_read;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_rule2cnt_V_read;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_rule3cnt_V_read;
    sc_signal< sc_lv<32> > my_ip_hls_entry90_U0_rule1_V_out_din;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_rule1_V_out_write;
    sc_signal< sc_lv<32> > my_ip_hls_entry90_U0_rule2_V_out_din;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_rule2_V_out_write;
    sc_signal< sc_lv<32> > my_ip_hls_entry90_U0_rule3_V_out_din;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_rule3_V_out_write;
    sc_signal< sc_lv<32> > my_ip_hls_entry90_U0_rule1cnt_V_out_din;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_rule1cnt_V_out_write;
    sc_signal< sc_lv<32> > my_ip_hls_entry90_U0_rule2cnt_V_out_din;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_rule2cnt_V_out_write;
    sc_signal< sc_lv<32> > my_ip_hls_entry90_U0_rule3cnt_V_out_din;
    sc_signal< sc_logic > my_ip_hls_entry90_U0_rule3cnt_V_out_write;
    sc_signal< sc_logic > Block_codeRepl6_proc_U0_ap_start;
    sc_signal< sc_logic > Block_codeRepl6_proc_U0_ap_done;
    sc_signal< sc_logic > Block_codeRepl6_proc_U0_ap_continue;
    sc_signal< sc_logic > Block_codeRepl6_proc_U0_ap_idle;
    sc_signal< sc_logic > Block_codeRepl6_proc_U0_ap_ready;
    sc_signal< sc_logic > Block_codeRepl6_proc_U0_rule3cnt_V_read;
    sc_signal< sc_logic > Block_codeRepl6_proc_U0_rule2cnt_V_read;
    sc_signal< sc_logic > Block_codeRepl6_proc_U0_rule1cnt_V_read;
    sc_signal< sc_lv<32> > Block_codeRepl6_proc_U0_rule3cnt_V_buf_out_din;
    sc_signal< sc_logic > Block_codeRepl6_proc_U0_rule3cnt_V_buf_out_write;
    sc_signal< sc_lv<32> > Block_codeRepl6_proc_U0_rule2cnt_V_buf_out_din;
    sc_signal< sc_logic > Block_codeRepl6_proc_U0_rule2cnt_V_buf_out_write;
    sc_signal< sc_lv<32> > Block_codeRepl6_proc_U0_rule1cnt_V_buf_out_din;
    sc_signal< sc_logic > Block_codeRepl6_proc_U0_rule1cnt_V_buf_out_write;
    sc_signal< sc_logic > okanonas82_U0_ap_start;
    sc_signal< sc_logic > okanonas82_U0_ap_done;
    sc_signal< sc_logic > okanonas82_U0_ap_continue;
    sc_signal< sc_logic > okanonas82_U0_ap_idle;
    sc_signal< sc_logic > okanonas82_U0_ap_ready;
    sc_signal< sc_logic > okanonas82_U0_rule_V_read;
    sc_signal< sc_lv<32> > okanonas82_U0_ap_return;
    sc_signal< sc_logic > ap_channel_done_regrule1_V_channel;
    sc_signal< sc_logic > regrule1_V_channel_full_n;
    sc_signal< sc_logic > okanonas83_U0_ap_start;
    sc_signal< sc_logic > okanonas83_U0_ap_done;
    sc_signal< sc_logic > okanonas83_U0_ap_continue;
    sc_signal< sc_logic > okanonas83_U0_ap_idle;
    sc_signal< sc_logic > okanonas83_U0_ap_ready;
    sc_signal< sc_logic > okanonas83_U0_rule_V_read;
    sc_signal< sc_lv<32> > okanonas83_U0_ap_return;
    sc_signal< sc_logic > ap_channel_done_regrule2_V_channel;
    sc_signal< sc_logic > regrule2_V_channel_full_n;
    sc_signal< sc_logic > okanonas_U0_ap_start;
    sc_signal< sc_logic > okanonas_U0_ap_done;
    sc_signal< sc_logic > okanonas_U0_ap_continue;
    sc_signal< sc_logic > okanonas_U0_ap_idle;
    sc_signal< sc_logic > okanonas_U0_ap_ready;
    sc_signal< sc_logic > okanonas_U0_rule_V_read;
    sc_signal< sc_lv<32> > okanonas_U0_ap_return;
    sc_signal< sc_logic > ap_channel_done_regrule3_V_channel;
    sc_signal< sc_logic > regrule3_V_channel_full_n;
    sc_signal< sc_logic > ps2ip_fifo_U0_ap_start;
    sc_signal< sc_logic > ps2ip_fifo_U0_ap_done;
    sc_signal< sc_logic > ps2ip_fifo_U0_ap_continue;
    sc_signal< sc_logic > ps2ip_fifo_U0_ap_idle;
    sc_signal< sc_logic > ps2ip_fifo_U0_ap_ready;
    sc_signal< sc_logic > ps2ip_fifo_U0_slaveIn_TREADY;
    sc_signal< sc_lv<32> > ps2ip_fifo_U0_ps2ipFifo_V_data_V_din;
    sc_signal< sc_logic > ps2ip_fifo_U0_ps2ipFifo_V_data_V_write;
    sc_signal< sc_lv<4> > ps2ip_fifo_U0_ps2ipFifo_V_strb_V_din;
    sc_signal< sc_logic > ps2ip_fifo_U0_ps2ipFifo_V_strb_V_write;
    sc_signal< sc_lv<1> > ps2ip_fifo_U0_ps2ipFifo_V_last_V_din;
    sc_signal< sc_logic > ps2ip_fifo_U0_ps2ipFifo_V_last_V_write;
    sc_signal< sc_logic > core_U0_ap_start;
    sc_signal< sc_logic > core_U0_start_full_n;
    sc_signal< sc_logic > core_U0_ap_done;
    sc_signal< sc_logic > core_U0_ap_continue;
    sc_signal< sc_logic > core_U0_ap_idle;
    sc_signal< sc_logic > core_U0_ap_ready;
    sc_signal< sc_logic > core_U0_rule1cnt_V_buf_read;
    sc_signal< sc_logic > core_U0_rule2cnt_V_buf_read;
    sc_signal< sc_logic > core_U0_rule3cnt_V_buf_read;
    sc_signal< sc_lv<32> > core_U0_rule1cnt_V_buf_out_din;
    sc_signal< sc_logic > core_U0_rule1cnt_V_buf_out_write;
    sc_signal< sc_lv<32> > core_U0_rule2cnt_V_buf_out_din;
    sc_signal< sc_logic > core_U0_rule2cnt_V_buf_out_write;
    sc_signal< sc_lv<32> > core_U0_rule3cnt_V_buf_out_din;
    sc_signal< sc_logic > core_U0_rule3cnt_V_buf_out_write;
    sc_signal< sc_logic > core_U0_start_out;
    sc_signal< sc_logic > core_U0_start_write;
    sc_signal< sc_logic > core_U0_ps2ipFifo_V_data_V_read;
    sc_signal< sc_logic > core_U0_ps2ipFifo_V_strb_V_read;
    sc_signal< sc_logic > core_U0_ps2ipFifo_V_last_V_read;
    sc_signal< sc_lv<32> > core_U0_ip2psFifo_V_data_V_din;
    sc_signal< sc_logic > core_U0_ip2psFifo_V_data_V_write;
    sc_signal< sc_lv<4> > core_U0_ip2psFifo_V_strb_V_din;
    sc_signal< sc_logic > core_U0_ip2psFifo_V_strb_V_write;
    sc_signal< sc_lv<1> > core_U0_ip2psFifo_V_last_V_din;
    sc_signal< sc_logic > core_U0_ip2psFifo_V_last_V_write;
    sc_signal< sc_logic > okanonas284_U0_ap_start;
    sc_signal< sc_logic > okanonas284_U0_ap_done;
    sc_signal< sc_logic > okanonas284_U0_ap_continue;
    sc_signal< sc_logic > okanonas284_U0_ap_idle;
    sc_signal< sc_logic > okanonas284_U0_ap_ready;
    sc_signal< sc_logic > okanonas284_U0_rule1cnt_V_buf_read;
    sc_signal< sc_logic > okanonas285_U0_ap_start;
    sc_signal< sc_logic > okanonas285_U0_ap_done;
    sc_signal< sc_logic > okanonas285_U0_ap_continue;
    sc_signal< sc_logic > okanonas285_U0_ap_idle;
    sc_signal< sc_logic > okanonas285_U0_ap_ready;
    sc_signal< sc_logic > okanonas285_U0_rule2cnt_V_buf_read;
    sc_signal< sc_logic > okanonas2_U0_ap_start;
    sc_signal< sc_logic > okanonas2_U0_ap_done;
    sc_signal< sc_logic > okanonas2_U0_ap_continue;
    sc_signal< sc_logic > okanonas2_U0_ap_idle;
    sc_signal< sc_logic > okanonas2_U0_ap_ready;
    sc_signal< sc_logic > okanonas2_U0_rule3cnt_V_buf_read;
    sc_signal< sc_logic > ip2ps_fifo_U0_ap_start;
    sc_signal< sc_logic > ip2ps_fifo_U0_ap_done;
    sc_signal< sc_logic > ip2ps_fifo_U0_ap_continue;
    sc_signal< sc_logic > ip2ps_fifo_U0_ap_idle;
    sc_signal< sc_logic > ip2ps_fifo_U0_ap_ready;
    sc_signal< sc_lv<32> > ip2ps_fifo_U0_masterOut_TDATA;
    sc_signal< sc_logic > ip2ps_fifo_U0_masterOut_TVALID;
    sc_signal< sc_lv<4> > ip2ps_fifo_U0_masterOut_TSTRB;
    sc_signal< sc_lv<1> > ip2ps_fifo_U0_masterOut_TLAST;
    sc_signal< sc_logic > ip2ps_fifo_U0_ip2psFifo_V_data_V_read;
    sc_signal< sc_logic > ip2ps_fifo_U0_ip2psFifo_V_strb_V_read;
    sc_signal< sc_logic > ip2ps_fifo_U0_ip2psFifo_V_last_V_read;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > rule1_V_c1_full_n;
    sc_signal< sc_lv<32> > rule1_V_c1_dout;
    sc_signal< sc_logic > rule1_V_c1_empty_n;
    sc_signal< sc_logic > rule2_V_c2_full_n;
    sc_signal< sc_lv<32> > rule2_V_c2_dout;
    sc_signal< sc_logic > rule2_V_c2_empty_n;
    sc_signal< sc_logic > rule3_V_c3_full_n;
    sc_signal< sc_lv<32> > rule3_V_c3_dout;
    sc_signal< sc_logic > rule3_V_c3_empty_n;
    sc_signal< sc_logic > rule1cnt_V_c4_full_n;
    sc_signal< sc_lv<32> > rule1cnt_V_c4_dout;
    sc_signal< sc_logic > rule1cnt_V_c4_empty_n;
    sc_signal< sc_logic > rule2cnt_V_c5_full_n;
    sc_signal< sc_lv<32> > rule2cnt_V_c5_dout;
    sc_signal< sc_logic > rule2cnt_V_c5_empty_n;
    sc_signal< sc_logic > rule3cnt_V_c6_full_n;
    sc_signal< sc_lv<32> > rule3cnt_V_c6_dout;
    sc_signal< sc_logic > rule3cnt_V_c6_empty_n;
    sc_signal< sc_logic > rule1_V_c_full_n;
    sc_signal< sc_lv<32> > rule1_V_c_dout;
    sc_signal< sc_logic > rule1_V_c_empty_n;
    sc_signal< sc_logic > rule2_V_c_full_n;
    sc_signal< sc_lv<32> > rule2_V_c_dout;
    sc_signal< sc_logic > rule2_V_c_empty_n;
    sc_signal< sc_logic > rule3_V_c_full_n;
    sc_signal< sc_lv<32> > rule3_V_c_dout;
    sc_signal< sc_logic > rule3_V_c_empty_n;
    sc_signal< sc_logic > rule1cnt_V_c_full_n;
    sc_signal< sc_lv<32> > rule1cnt_V_c_dout;
    sc_signal< sc_logic > rule1cnt_V_c_empty_n;
    sc_signal< sc_logic > rule2cnt_V_c_full_n;
    sc_signal< sc_lv<32> > rule2cnt_V_c_dout;
    sc_signal< sc_logic > rule2cnt_V_c_empty_n;
    sc_signal< sc_logic > rule3cnt_V_c_full_n;
    sc_signal< sc_lv<32> > rule3cnt_V_c_dout;
    sc_signal< sc_logic > rule3cnt_V_c_empty_n;
    sc_signal< sc_logic > rule3cnt_V_buf_c_full_n;
    sc_signal< sc_lv<32> > rule3cnt_V_buf_c_dout;
    sc_signal< sc_logic > rule3cnt_V_buf_c_empty_n;
    sc_signal< sc_logic > rule2cnt_V_buf_c_full_n;
    sc_signal< sc_lv<32> > rule2cnt_V_buf_c_dout;
    sc_signal< sc_logic > rule2cnt_V_buf_c_empty_n;
    sc_signal< sc_logic > rule1cnt_V_buf_c_full_n;
    sc_signal< sc_lv<32> > rule1cnt_V_buf_c_dout;
    sc_signal< sc_logic > rule1cnt_V_buf_c_empty_n;
    sc_signal< sc_lv<32> > regrule1_V_channel_dout;
    sc_signal< sc_logic > regrule1_V_channel_empty_n;
    sc_signal< sc_lv<32> > regrule2_V_channel_dout;
    sc_signal< sc_logic > regrule2_V_channel_empty_n;
    sc_signal< sc_lv<32> > regrule3_V_channel_dout;
    sc_signal< sc_logic > regrule3_V_channel_empty_n;
    sc_signal< sc_logic > ps2ipFifo_V_data_V_full_n;
    sc_signal< sc_lv<32> > ps2ipFifo_V_data_V_dout;
    sc_signal< sc_logic > ps2ipFifo_V_data_V_empty_n;
    sc_signal< sc_logic > ps2ipFifo_V_strb_V_full_n;
    sc_signal< sc_lv<4> > ps2ipFifo_V_strb_V_dout;
    sc_signal< sc_logic > ps2ipFifo_V_strb_V_empty_n;
    sc_signal< sc_logic > ps2ipFifo_V_last_V_full_n;
    sc_signal< sc_lv<1> > ps2ipFifo_V_last_V_dout;
    sc_signal< sc_logic > ps2ipFifo_V_last_V_empty_n;
    sc_signal< sc_logic > rule1cnt_V_buf_c31_full_n;
    sc_signal< sc_lv<32> > rule1cnt_V_buf_c31_dout;
    sc_signal< sc_logic > rule1cnt_V_buf_c31_empty_n;
    sc_signal< sc_logic > rule2cnt_V_buf_c32_full_n;
    sc_signal< sc_lv<32> > rule2cnt_V_buf_c32_dout;
    sc_signal< sc_logic > rule2cnt_V_buf_c32_empty_n;
    sc_signal< sc_logic > rule3cnt_V_buf_c33_full_n;
    sc_signal< sc_lv<32> > rule3cnt_V_buf_c33_dout;
    sc_signal< sc_logic > rule3cnt_V_buf_c33_empty_n;
    sc_signal< sc_logic > ip2psFifo_V_data_V_full_n;
    sc_signal< sc_lv<32> > ip2psFifo_V_data_V_dout;
    sc_signal< sc_logic > ip2psFifo_V_data_V_empty_n;
    sc_signal< sc_logic > ip2psFifo_V_strb_V_full_n;
    sc_signal< sc_lv<4> > ip2psFifo_V_strb_V_dout;
    sc_signal< sc_logic > ip2psFifo_V_strb_V_empty_n;
    sc_signal< sc_logic > ip2psFifo_V_last_V_full_n;
    sc_signal< sc_lv<1> > ip2psFifo_V_last_V_dout;
    sc_signal< sc_logic > ip2psFifo_V_last_V_empty_n;
    sc_signal< sc_lv<1> > start_for_my_ip_hls_entry90_U0_din;
    sc_signal< sc_logic > start_for_my_ip_hls_entry90_U0_full_n;
    sc_signal< sc_lv<1> > start_for_my_ip_hls_entry90_U0_dout;
    sc_signal< sc_logic > start_for_my_ip_hls_entry90_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_Block_codeRepl6_proc_U0_din;
    sc_signal< sc_logic > start_for_Block_codeRepl6_proc_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Block_codeRepl6_proc_U0_dout;
    sc_signal< sc_logic > start_for_Block_codeRepl6_proc_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_okanonas82_U0_din;
    sc_signal< sc_logic > start_for_okanonas82_U0_full_n;
    sc_signal< sc_lv<1> > start_for_okanonas82_U0_dout;
    sc_signal< sc_logic > start_for_okanonas82_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_okanonas83_U0_din;
    sc_signal< sc_logic > start_for_okanonas83_U0_full_n;
    sc_signal< sc_lv<1> > start_for_okanonas83_U0_dout;
    sc_signal< sc_logic > start_for_okanonas83_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_okanonas_U0_din;
    sc_signal< sc_logic > start_for_okanonas_U0_full_n;
    sc_signal< sc_lv<1> > start_for_okanonas_U0_dout;
    sc_signal< sc_logic > start_for_okanonas_U0_empty_n;
    sc_signal< sc_logic > Block_codeRepl6_proc_U0_start_full_n;
    sc_signal< sc_logic > Block_codeRepl6_proc_U0_start_write;
    sc_signal< sc_logic > okanonas82_U0_start_full_n;
    sc_signal< sc_logic > okanonas82_U0_start_write;
    sc_signal< sc_logic > okanonas83_U0_start_full_n;
    sc_signal< sc_logic > okanonas83_U0_start_write;
    sc_signal< sc_logic > okanonas_U0_start_full_n;
    sc_signal< sc_logic > okanonas_U0_start_write;
    sc_signal< sc_logic > ps2ip_fifo_U0_start_full_n;
    sc_signal< sc_logic > ps2ip_fifo_U0_start_write;
    sc_signal< sc_lv<1> > start_for_okanonas284_U0_din;
    sc_signal< sc_logic > start_for_okanonas284_U0_full_n;
    sc_signal< sc_lv<1> > start_for_okanonas284_U0_dout;
    sc_signal< sc_logic > start_for_okanonas284_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_okanonas285_U0_din;
    sc_signal< sc_logic > start_for_okanonas285_U0_full_n;
    sc_signal< sc_lv<1> > start_for_okanonas285_U0_dout;
    sc_signal< sc_logic > start_for_okanonas285_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_okanonas2_U0_din;
    sc_signal< sc_logic > start_for_okanonas2_U0_full_n;
    sc_signal< sc_lv<1> > start_for_okanonas2_U0_dout;
    sc_signal< sc_logic > start_for_okanonas2_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_ip2ps_fifo_U0_din;
    sc_signal< sc_logic > start_for_ip2ps_fifo_U0_full_n;
    sc_signal< sc_lv<1> > start_for_ip2ps_fifo_U0_dout;
    sc_signal< sc_logic > start_for_ip2ps_fifo_U0_empty_n;
    sc_signal< sc_logic > okanonas284_U0_start_full_n;
    sc_signal< sc_logic > okanonas284_U0_start_write;
    sc_signal< sc_logic > okanonas285_U0_start_full_n;
    sc_signal< sc_logic > okanonas285_U0_start_write;
    sc_signal< sc_logic > okanonas2_U0_start_full_n;
    sc_signal< sc_logic > okanonas2_U0_start_write;
    sc_signal< sc_logic > ip2ps_fifo_U0_start_full_n;
    sc_signal< sc_logic > ip2ps_fifo_U0_start_write;
    static const int C_S_AXI_DATA_WIDTH;
    static const int C_S_AXI_WSTRB_WIDTH;
    static const int C_S_AXI_ADDR_WIDTH;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_Block_codeRepl6_proc_U0_ap_continue();
    void thread_Block_codeRepl6_proc_U0_ap_start();
    void thread_Block_codeRepl6_proc_U0_start_full_n();
    void thread_Block_codeRepl6_proc_U0_start_write();
    void thread_ap_channel_done_regrule1_V_channel();
    void thread_ap_channel_done_regrule2_V_channel();
    void thread_ap_channel_done_regrule3_V_channel();
    void thread_ap_rst_n_inv();
    void thread_ap_sync_continue();
    void thread_core_U0_ap_continue();
    void thread_core_U0_ap_start();
    void thread_core_U0_start_full_n();
    void thread_ip2ps_fifo_U0_ap_continue();
    void thread_ip2ps_fifo_U0_ap_start();
    void thread_ip2ps_fifo_U0_start_full_n();
    void thread_ip2ps_fifo_U0_start_write();
    void thread_masterOut_TDATA();
    void thread_masterOut_TLAST();
    void thread_masterOut_TSTRB();
    void thread_masterOut_TVALID();
    void thread_my_ip_hls_entry3_U0_ap_continue();
    void thread_my_ip_hls_entry3_U0_ap_start();
    void thread_my_ip_hls_entry90_U0_ap_continue();
    void thread_my_ip_hls_entry90_U0_ap_start();
    void thread_my_ip_hls_entry90_U0_start_full_n();
    void thread_okanonas284_U0_ap_continue();
    void thread_okanonas284_U0_ap_start();
    void thread_okanonas284_U0_start_full_n();
    void thread_okanonas284_U0_start_write();
    void thread_okanonas285_U0_ap_continue();
    void thread_okanonas285_U0_ap_start();
    void thread_okanonas285_U0_start_full_n();
    void thread_okanonas285_U0_start_write();
    void thread_okanonas2_U0_ap_continue();
    void thread_okanonas2_U0_ap_start();
    void thread_okanonas2_U0_start_full_n();
    void thread_okanonas2_U0_start_write();
    void thread_okanonas82_U0_ap_continue();
    void thread_okanonas82_U0_ap_start();
    void thread_okanonas82_U0_start_full_n();
    void thread_okanonas82_U0_start_write();
    void thread_okanonas83_U0_ap_continue();
    void thread_okanonas83_U0_ap_start();
    void thread_okanonas83_U0_start_full_n();
    void thread_okanonas83_U0_start_write();
    void thread_okanonas_U0_ap_continue();
    void thread_okanonas_U0_ap_start();
    void thread_okanonas_U0_start_full_n();
    void thread_okanonas_U0_start_write();
    void thread_ps2ip_fifo_U0_ap_continue();
    void thread_ps2ip_fifo_U0_ap_start();
    void thread_ps2ip_fifo_U0_start_full_n();
    void thread_ps2ip_fifo_U0_start_write();
    void thread_slaveIn_TREADY();
    void thread_start_for_Block_codeRepl6_proc_U0_din();
    void thread_start_for_ip2ps_fifo_U0_din();
    void thread_start_for_my_ip_hls_entry90_U0_din();
    void thread_start_for_okanonas284_U0_din();
    void thread_start_for_okanonas285_U0_din();
    void thread_start_for_okanonas2_U0_din();
    void thread_start_for_okanonas82_U0_din();
    void thread_start_for_okanonas83_U0_din();
    void thread_start_for_okanonas_U0_din();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
