// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "my_ip_hls.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const int my_ip_hls::C_S_AXI_DATA_WIDTH = "100000";
const int my_ip_hls::C_S_AXI_WSTRB_WIDTH = "100";
const int my_ip_hls::C_S_AXI_ADDR_WIDTH = "100000";
const sc_logic my_ip_hls::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<32> my_ip_hls::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<4> my_ip_hls::ap_const_lv4_0 = "0000";
const sc_lv<1> my_ip_hls::ap_const_lv1_0 = "0";
const sc_logic my_ip_hls::ap_const_logic_0 = sc_dt::Log_0;

my_ip_hls::my_ip_hls(sc_module_name name) : sc_module(name), mVcdFile(0) {
    my_ip_hls_ziskasrules_s_axi_U = new my_ip_hls_ziskasrules_s_axi<C_S_AXI_ZISKASRULES_ADDR_WIDTH,C_S_AXI_ZISKASRULES_DATA_WIDTH>("my_ip_hls_ziskasrules_s_axi_U");
    my_ip_hls_ziskasrules_s_axi_U->AWVALID(s_axi_ziskasrules_AWVALID);
    my_ip_hls_ziskasrules_s_axi_U->AWREADY(s_axi_ziskasrules_AWREADY);
    my_ip_hls_ziskasrules_s_axi_U->AWADDR(s_axi_ziskasrules_AWADDR);
    my_ip_hls_ziskasrules_s_axi_U->WVALID(s_axi_ziskasrules_WVALID);
    my_ip_hls_ziskasrules_s_axi_U->WREADY(s_axi_ziskasrules_WREADY);
    my_ip_hls_ziskasrules_s_axi_U->WDATA(s_axi_ziskasrules_WDATA);
    my_ip_hls_ziskasrules_s_axi_U->WSTRB(s_axi_ziskasrules_WSTRB);
    my_ip_hls_ziskasrules_s_axi_U->ARVALID(s_axi_ziskasrules_ARVALID);
    my_ip_hls_ziskasrules_s_axi_U->ARREADY(s_axi_ziskasrules_ARREADY);
    my_ip_hls_ziskasrules_s_axi_U->ARADDR(s_axi_ziskasrules_ARADDR);
    my_ip_hls_ziskasrules_s_axi_U->RVALID(s_axi_ziskasrules_RVALID);
    my_ip_hls_ziskasrules_s_axi_U->RREADY(s_axi_ziskasrules_RREADY);
    my_ip_hls_ziskasrules_s_axi_U->RDATA(s_axi_ziskasrules_RDATA);
    my_ip_hls_ziskasrules_s_axi_U->RRESP(s_axi_ziskasrules_RRESP);
    my_ip_hls_ziskasrules_s_axi_U->BVALID(s_axi_ziskasrules_BVALID);
    my_ip_hls_ziskasrules_s_axi_U->BREADY(s_axi_ziskasrules_BREADY);
    my_ip_hls_ziskasrules_s_axi_U->BRESP(s_axi_ziskasrules_BRESP);
    my_ip_hls_ziskasrules_s_axi_U->ACLK(ap_clk);
    my_ip_hls_ziskasrules_s_axi_U->ARESET(ap_rst_n_inv);
    my_ip_hls_ziskasrules_s_axi_U->ACLK_EN(ap_var_for_const0);
    my_ip_hls_ziskasrules_s_axi_U->rule1_V(rule1_V);
    my_ip_hls_ziskasrules_s_axi_U->rule2_V(rule2_V);
    my_ip_hls_ziskasrules_s_axi_U->rule3_V(rule3_V);
    my_ip_hls_ziskasrules_s_axi_U->rule1cnt_V(rule1cnt_V);
    my_ip_hls_ziskasrules_s_axi_U->rule2cnt_V(rule2cnt_V);
    my_ip_hls_ziskasrules_s_axi_U->rule3cnt_V(rule3cnt_V);
    my_ip_hls_entry3_U0 = new my_ip_hls_entry3("my_ip_hls_entry3_U0");
    my_ip_hls_entry3_U0->ap_clk(ap_clk);
    my_ip_hls_entry3_U0->ap_rst(ap_rst_n_inv);
    my_ip_hls_entry3_U0->ap_start(my_ip_hls_entry3_U0_ap_start);
    my_ip_hls_entry3_U0->start_full_n(start_for_my_ip_hls_entry90_U0_full_n);
    my_ip_hls_entry3_U0->ap_done(my_ip_hls_entry3_U0_ap_done);
    my_ip_hls_entry3_U0->ap_continue(my_ip_hls_entry3_U0_ap_continue);
    my_ip_hls_entry3_U0->ap_idle(my_ip_hls_entry3_U0_ap_idle);
    my_ip_hls_entry3_U0->ap_ready(my_ip_hls_entry3_U0_ap_ready);
    my_ip_hls_entry3_U0->start_out(my_ip_hls_entry3_U0_start_out);
    my_ip_hls_entry3_U0->start_write(my_ip_hls_entry3_U0_start_write);
    my_ip_hls_entry3_U0->rule1_V(rule1_V);
    my_ip_hls_entry3_U0->rule2_V(rule2_V);
    my_ip_hls_entry3_U0->rule3_V(rule3_V);
    my_ip_hls_entry3_U0->rule1cnt_V(rule1cnt_V);
    my_ip_hls_entry3_U0->rule2cnt_V(rule2cnt_V);
    my_ip_hls_entry3_U0->rule3cnt_V(rule3cnt_V);
    my_ip_hls_entry3_U0->rule1_V_out_din(my_ip_hls_entry3_U0_rule1_V_out_din);
    my_ip_hls_entry3_U0->rule1_V_out_full_n(rule1_V_c1_full_n);
    my_ip_hls_entry3_U0->rule1_V_out_write(my_ip_hls_entry3_U0_rule1_V_out_write);
    my_ip_hls_entry3_U0->rule2_V_out_din(my_ip_hls_entry3_U0_rule2_V_out_din);
    my_ip_hls_entry3_U0->rule2_V_out_full_n(rule2_V_c2_full_n);
    my_ip_hls_entry3_U0->rule2_V_out_write(my_ip_hls_entry3_U0_rule2_V_out_write);
    my_ip_hls_entry3_U0->rule3_V_out_din(my_ip_hls_entry3_U0_rule3_V_out_din);
    my_ip_hls_entry3_U0->rule3_V_out_full_n(rule3_V_c3_full_n);
    my_ip_hls_entry3_U0->rule3_V_out_write(my_ip_hls_entry3_U0_rule3_V_out_write);
    my_ip_hls_entry3_U0->rule1cnt_V_out_din(my_ip_hls_entry3_U0_rule1cnt_V_out_din);
    my_ip_hls_entry3_U0->rule1cnt_V_out_full_n(rule1cnt_V_c4_full_n);
    my_ip_hls_entry3_U0->rule1cnt_V_out_write(my_ip_hls_entry3_U0_rule1cnt_V_out_write);
    my_ip_hls_entry3_U0->rule2cnt_V_out_din(my_ip_hls_entry3_U0_rule2cnt_V_out_din);
    my_ip_hls_entry3_U0->rule2cnt_V_out_full_n(rule2cnt_V_c5_full_n);
    my_ip_hls_entry3_U0->rule2cnt_V_out_write(my_ip_hls_entry3_U0_rule2cnt_V_out_write);
    my_ip_hls_entry3_U0->rule3cnt_V_out_din(my_ip_hls_entry3_U0_rule3cnt_V_out_din);
    my_ip_hls_entry3_U0->rule3cnt_V_out_full_n(rule3cnt_V_c6_full_n);
    my_ip_hls_entry3_U0->rule3cnt_V_out_write(my_ip_hls_entry3_U0_rule3cnt_V_out_write);
    my_ip_hls_entry90_U0 = new my_ip_hls_entry90("my_ip_hls_entry90_U0");
    my_ip_hls_entry90_U0->ap_clk(ap_clk);
    my_ip_hls_entry90_U0->ap_rst(ap_rst_n_inv);
    my_ip_hls_entry90_U0->ap_start(my_ip_hls_entry90_U0_ap_start);
    my_ip_hls_entry90_U0->start_full_n(my_ip_hls_entry90_U0_start_full_n);
    my_ip_hls_entry90_U0->ap_done(my_ip_hls_entry90_U0_ap_done);
    my_ip_hls_entry90_U0->ap_continue(my_ip_hls_entry90_U0_ap_continue);
    my_ip_hls_entry90_U0->ap_idle(my_ip_hls_entry90_U0_ap_idle);
    my_ip_hls_entry90_U0->ap_ready(my_ip_hls_entry90_U0_ap_ready);
    my_ip_hls_entry90_U0->start_out(my_ip_hls_entry90_U0_start_out);
    my_ip_hls_entry90_U0->start_write(my_ip_hls_entry90_U0_start_write);
    my_ip_hls_entry90_U0->rule1_V_dout(rule1_V_c1_dout);
    my_ip_hls_entry90_U0->rule1_V_empty_n(rule1_V_c1_empty_n);
    my_ip_hls_entry90_U0->rule1_V_read(my_ip_hls_entry90_U0_rule1_V_read);
    my_ip_hls_entry90_U0->rule2_V_dout(rule2_V_c2_dout);
    my_ip_hls_entry90_U0->rule2_V_empty_n(rule2_V_c2_empty_n);
    my_ip_hls_entry90_U0->rule2_V_read(my_ip_hls_entry90_U0_rule2_V_read);
    my_ip_hls_entry90_U0->rule3_V_dout(rule3_V_c3_dout);
    my_ip_hls_entry90_U0->rule3_V_empty_n(rule3_V_c3_empty_n);
    my_ip_hls_entry90_U0->rule3_V_read(my_ip_hls_entry90_U0_rule3_V_read);
    my_ip_hls_entry90_U0->rule1cnt_V_dout(rule1cnt_V_c4_dout);
    my_ip_hls_entry90_U0->rule1cnt_V_empty_n(rule1cnt_V_c4_empty_n);
    my_ip_hls_entry90_U0->rule1cnt_V_read(my_ip_hls_entry90_U0_rule1cnt_V_read);
    my_ip_hls_entry90_U0->rule2cnt_V_dout(rule2cnt_V_c5_dout);
    my_ip_hls_entry90_U0->rule2cnt_V_empty_n(rule2cnt_V_c5_empty_n);
    my_ip_hls_entry90_U0->rule2cnt_V_read(my_ip_hls_entry90_U0_rule2cnt_V_read);
    my_ip_hls_entry90_U0->rule3cnt_V_dout(rule3cnt_V_c6_dout);
    my_ip_hls_entry90_U0->rule3cnt_V_empty_n(rule3cnt_V_c6_empty_n);
    my_ip_hls_entry90_U0->rule3cnt_V_read(my_ip_hls_entry90_U0_rule3cnt_V_read);
    my_ip_hls_entry90_U0->rule1_V_out_din(my_ip_hls_entry90_U0_rule1_V_out_din);
    my_ip_hls_entry90_U0->rule1_V_out_full_n(rule1_V_c_full_n);
    my_ip_hls_entry90_U0->rule1_V_out_write(my_ip_hls_entry90_U0_rule1_V_out_write);
    my_ip_hls_entry90_U0->rule2_V_out_din(my_ip_hls_entry90_U0_rule2_V_out_din);
    my_ip_hls_entry90_U0->rule2_V_out_full_n(rule2_V_c_full_n);
    my_ip_hls_entry90_U0->rule2_V_out_write(my_ip_hls_entry90_U0_rule2_V_out_write);
    my_ip_hls_entry90_U0->rule3_V_out_din(my_ip_hls_entry90_U0_rule3_V_out_din);
    my_ip_hls_entry90_U0->rule3_V_out_full_n(rule3_V_c_full_n);
    my_ip_hls_entry90_U0->rule3_V_out_write(my_ip_hls_entry90_U0_rule3_V_out_write);
    my_ip_hls_entry90_U0->rule1cnt_V_out_din(my_ip_hls_entry90_U0_rule1cnt_V_out_din);
    my_ip_hls_entry90_U0->rule1cnt_V_out_full_n(rule1cnt_V_c_full_n);
    my_ip_hls_entry90_U0->rule1cnt_V_out_write(my_ip_hls_entry90_U0_rule1cnt_V_out_write);
    my_ip_hls_entry90_U0->rule2cnt_V_out_din(my_ip_hls_entry90_U0_rule2cnt_V_out_din);
    my_ip_hls_entry90_U0->rule2cnt_V_out_full_n(rule2cnt_V_c_full_n);
    my_ip_hls_entry90_U0->rule2cnt_V_out_write(my_ip_hls_entry90_U0_rule2cnt_V_out_write);
    my_ip_hls_entry90_U0->rule3cnt_V_out_din(my_ip_hls_entry90_U0_rule3cnt_V_out_din);
    my_ip_hls_entry90_U0->rule3cnt_V_out_full_n(rule3cnt_V_c_full_n);
    my_ip_hls_entry90_U0->rule3cnt_V_out_write(my_ip_hls_entry90_U0_rule3cnt_V_out_write);
    Block_codeRepl6_proc_U0 = new Block_codeRepl6_proc("Block_codeRepl6_proc_U0");
    Block_codeRepl6_proc_U0->ap_clk(ap_clk);
    Block_codeRepl6_proc_U0->ap_rst(ap_rst_n_inv);
    Block_codeRepl6_proc_U0->ap_start(Block_codeRepl6_proc_U0_ap_start);
    Block_codeRepl6_proc_U0->ap_done(Block_codeRepl6_proc_U0_ap_done);
    Block_codeRepl6_proc_U0->ap_continue(Block_codeRepl6_proc_U0_ap_continue);
    Block_codeRepl6_proc_U0->ap_idle(Block_codeRepl6_proc_U0_ap_idle);
    Block_codeRepl6_proc_U0->ap_ready(Block_codeRepl6_proc_U0_ap_ready);
    Block_codeRepl6_proc_U0->rule3cnt_V_dout(rule3cnt_V_c_dout);
    Block_codeRepl6_proc_U0->rule3cnt_V_empty_n(rule3cnt_V_c_empty_n);
    Block_codeRepl6_proc_U0->rule3cnt_V_read(Block_codeRepl6_proc_U0_rule3cnt_V_read);
    Block_codeRepl6_proc_U0->rule2cnt_V_dout(rule2cnt_V_c_dout);
    Block_codeRepl6_proc_U0->rule2cnt_V_empty_n(rule2cnt_V_c_empty_n);
    Block_codeRepl6_proc_U0->rule2cnt_V_read(Block_codeRepl6_proc_U0_rule2cnt_V_read);
    Block_codeRepl6_proc_U0->rule1cnt_V_dout(rule1cnt_V_c_dout);
    Block_codeRepl6_proc_U0->rule1cnt_V_empty_n(rule1cnt_V_c_empty_n);
    Block_codeRepl6_proc_U0->rule1cnt_V_read(Block_codeRepl6_proc_U0_rule1cnt_V_read);
    Block_codeRepl6_proc_U0->rule3cnt_V_buf_out_din(Block_codeRepl6_proc_U0_rule3cnt_V_buf_out_din);
    Block_codeRepl6_proc_U0->rule3cnt_V_buf_out_full_n(rule3cnt_V_buf_c_full_n);
    Block_codeRepl6_proc_U0->rule3cnt_V_buf_out_write(Block_codeRepl6_proc_U0_rule3cnt_V_buf_out_write);
    Block_codeRepl6_proc_U0->rule2cnt_V_buf_out_din(Block_codeRepl6_proc_U0_rule2cnt_V_buf_out_din);
    Block_codeRepl6_proc_U0->rule2cnt_V_buf_out_full_n(rule2cnt_V_buf_c_full_n);
    Block_codeRepl6_proc_U0->rule2cnt_V_buf_out_write(Block_codeRepl6_proc_U0_rule2cnt_V_buf_out_write);
    Block_codeRepl6_proc_U0->rule1cnt_V_buf_out_din(Block_codeRepl6_proc_U0_rule1cnt_V_buf_out_din);
    Block_codeRepl6_proc_U0->rule1cnt_V_buf_out_full_n(rule1cnt_V_buf_c_full_n);
    Block_codeRepl6_proc_U0->rule1cnt_V_buf_out_write(Block_codeRepl6_proc_U0_rule1cnt_V_buf_out_write);
    okanonas82_U0 = new okanonas82("okanonas82_U0");
    okanonas82_U0->ap_clk(ap_clk);
    okanonas82_U0->ap_rst(ap_rst_n_inv);
    okanonas82_U0->ap_start(okanonas82_U0_ap_start);
    okanonas82_U0->ap_done(okanonas82_U0_ap_done);
    okanonas82_U0->ap_continue(okanonas82_U0_ap_continue);
    okanonas82_U0->ap_idle(okanonas82_U0_ap_idle);
    okanonas82_U0->ap_ready(okanonas82_U0_ap_ready);
    okanonas82_U0->rule_V_dout(rule1_V_c_dout);
    okanonas82_U0->rule_V_empty_n(rule1_V_c_empty_n);
    okanonas82_U0->rule_V_read(okanonas82_U0_rule_V_read);
    okanonas82_U0->ap_return(okanonas82_U0_ap_return);
    okanonas83_U0 = new okanonas83("okanonas83_U0");
    okanonas83_U0->ap_clk(ap_clk);
    okanonas83_U0->ap_rst(ap_rst_n_inv);
    okanonas83_U0->ap_start(okanonas83_U0_ap_start);
    okanonas83_U0->ap_done(okanonas83_U0_ap_done);
    okanonas83_U0->ap_continue(okanonas83_U0_ap_continue);
    okanonas83_U0->ap_idle(okanonas83_U0_ap_idle);
    okanonas83_U0->ap_ready(okanonas83_U0_ap_ready);
    okanonas83_U0->rule_V_dout(rule2_V_c_dout);
    okanonas83_U0->rule_V_empty_n(rule2_V_c_empty_n);
    okanonas83_U0->rule_V_read(okanonas83_U0_rule_V_read);
    okanonas83_U0->ap_return(okanonas83_U0_ap_return);
    okanonas_U0 = new okanonas("okanonas_U0");
    okanonas_U0->ap_clk(ap_clk);
    okanonas_U0->ap_rst(ap_rst_n_inv);
    okanonas_U0->ap_start(okanonas_U0_ap_start);
    okanonas_U0->ap_done(okanonas_U0_ap_done);
    okanonas_U0->ap_continue(okanonas_U0_ap_continue);
    okanonas_U0->ap_idle(okanonas_U0_ap_idle);
    okanonas_U0->ap_ready(okanonas_U0_ap_ready);
    okanonas_U0->rule_V_dout(rule3_V_c_dout);
    okanonas_U0->rule_V_empty_n(rule3_V_c_empty_n);
    okanonas_U0->rule_V_read(okanonas_U0_rule_V_read);
    okanonas_U0->ap_return(okanonas_U0_ap_return);
    ps2ip_fifo_U0 = new ps2ip_fifo("ps2ip_fifo_U0");
    ps2ip_fifo_U0->ap_clk(ap_clk);
    ps2ip_fifo_U0->ap_rst(ap_rst_n_inv);
    ps2ip_fifo_U0->ap_start(ps2ip_fifo_U0_ap_start);
    ps2ip_fifo_U0->ap_done(ps2ip_fifo_U0_ap_done);
    ps2ip_fifo_U0->ap_continue(ps2ip_fifo_U0_ap_continue);
    ps2ip_fifo_U0->ap_idle(ps2ip_fifo_U0_ap_idle);
    ps2ip_fifo_U0->ap_ready(ps2ip_fifo_U0_ap_ready);
    ps2ip_fifo_U0->slaveIn_TVALID(slaveIn_TVALID);
    ps2ip_fifo_U0->slaveIn_TDATA(slaveIn_TDATA);
    ps2ip_fifo_U0->slaveIn_TREADY(ps2ip_fifo_U0_slaveIn_TREADY);
    ps2ip_fifo_U0->slaveIn_TSTRB(slaveIn_TSTRB);
    ps2ip_fifo_U0->slaveIn_TLAST(slaveIn_TLAST);
    ps2ip_fifo_U0->ps2ipFifo_V_data_V_din(ps2ip_fifo_U0_ps2ipFifo_V_data_V_din);
    ps2ip_fifo_U0->ps2ipFifo_V_data_V_full_n(ps2ipFifo_V_data_V_full_n);
    ps2ip_fifo_U0->ps2ipFifo_V_data_V_write(ps2ip_fifo_U0_ps2ipFifo_V_data_V_write);
    ps2ip_fifo_U0->ps2ipFifo_V_strb_V_din(ps2ip_fifo_U0_ps2ipFifo_V_strb_V_din);
    ps2ip_fifo_U0->ps2ipFifo_V_strb_V_full_n(ps2ipFifo_V_strb_V_full_n);
    ps2ip_fifo_U0->ps2ipFifo_V_strb_V_write(ps2ip_fifo_U0_ps2ipFifo_V_strb_V_write);
    ps2ip_fifo_U0->ps2ipFifo_V_last_V_din(ps2ip_fifo_U0_ps2ipFifo_V_last_V_din);
    ps2ip_fifo_U0->ps2ipFifo_V_last_V_full_n(ps2ipFifo_V_last_V_full_n);
    ps2ip_fifo_U0->ps2ipFifo_V_last_V_write(ps2ip_fifo_U0_ps2ipFifo_V_last_V_write);
    core_U0 = new core("core_U0");
    core_U0->ap_clk(ap_clk);
    core_U0->ap_rst(ap_rst_n_inv);
    core_U0->ap_start(core_U0_ap_start);
    core_U0->start_full_n(core_U0_start_full_n);
    core_U0->ap_done(core_U0_ap_done);
    core_U0->ap_continue(core_U0_ap_continue);
    core_U0->ap_idle(core_U0_ap_idle);
    core_U0->ap_ready(core_U0_ap_ready);
    core_U0->rule1cnt_V_buf_dout(rule1cnt_V_buf_c_dout);
    core_U0->rule1cnt_V_buf_empty_n(rule1cnt_V_buf_c_empty_n);
    core_U0->rule1cnt_V_buf_read(core_U0_rule1cnt_V_buf_read);
    core_U0->rule2cnt_V_buf_dout(rule2cnt_V_buf_c_dout);
    core_U0->rule2cnt_V_buf_empty_n(rule2cnt_V_buf_c_empty_n);
    core_U0->rule2cnt_V_buf_read(core_U0_rule2cnt_V_buf_read);
    core_U0->rule3cnt_V_buf_dout(rule3cnt_V_buf_c_dout);
    core_U0->rule3cnt_V_buf_empty_n(rule3cnt_V_buf_c_empty_n);
    core_U0->rule3cnt_V_buf_read(core_U0_rule3cnt_V_buf_read);
    core_U0->rule1cnt_V_buf_out_din(core_U0_rule1cnt_V_buf_out_din);
    core_U0->rule1cnt_V_buf_out_full_n(rule1cnt_V_buf_c31_full_n);
    core_U0->rule1cnt_V_buf_out_write(core_U0_rule1cnt_V_buf_out_write);
    core_U0->rule2cnt_V_buf_out_din(core_U0_rule2cnt_V_buf_out_din);
    core_U0->rule2cnt_V_buf_out_full_n(rule2cnt_V_buf_c32_full_n);
    core_U0->rule2cnt_V_buf_out_write(core_U0_rule2cnt_V_buf_out_write);
    core_U0->rule3cnt_V_buf_out_din(core_U0_rule3cnt_V_buf_out_din);
    core_U0->rule3cnt_V_buf_out_full_n(rule3cnt_V_buf_c33_full_n);
    core_U0->rule3cnt_V_buf_out_write(core_U0_rule3cnt_V_buf_out_write);
    core_U0->start_out(core_U0_start_out);
    core_U0->start_write(core_U0_start_write);
    core_U0->p_read(regrule1_V_channel_dout);
    core_U0->p_read1(regrule2_V_channel_dout);
    core_U0->p_read2(regrule3_V_channel_dout);
    core_U0->ps2ipFifo_V_data_V_dout(ps2ipFifo_V_data_V_dout);
    core_U0->ps2ipFifo_V_data_V_empty_n(ps2ipFifo_V_data_V_empty_n);
    core_U0->ps2ipFifo_V_data_V_read(core_U0_ps2ipFifo_V_data_V_read);
    core_U0->ps2ipFifo_V_strb_V_dout(ps2ipFifo_V_strb_V_dout);
    core_U0->ps2ipFifo_V_strb_V_empty_n(ps2ipFifo_V_strb_V_empty_n);
    core_U0->ps2ipFifo_V_strb_V_read(core_U0_ps2ipFifo_V_strb_V_read);
    core_U0->ps2ipFifo_V_last_V_dout(ps2ipFifo_V_last_V_dout);
    core_U0->ps2ipFifo_V_last_V_empty_n(ps2ipFifo_V_last_V_empty_n);
    core_U0->ps2ipFifo_V_last_V_read(core_U0_ps2ipFifo_V_last_V_read);
    core_U0->ip2psFifo_V_data_V_din(core_U0_ip2psFifo_V_data_V_din);
    core_U0->ip2psFifo_V_data_V_full_n(ip2psFifo_V_data_V_full_n);
    core_U0->ip2psFifo_V_data_V_write(core_U0_ip2psFifo_V_data_V_write);
    core_U0->ip2psFifo_V_strb_V_din(core_U0_ip2psFifo_V_strb_V_din);
    core_U0->ip2psFifo_V_strb_V_full_n(ip2psFifo_V_strb_V_full_n);
    core_U0->ip2psFifo_V_strb_V_write(core_U0_ip2psFifo_V_strb_V_write);
    core_U0->ip2psFifo_V_last_V_din(core_U0_ip2psFifo_V_last_V_din);
    core_U0->ip2psFifo_V_last_V_full_n(ip2psFifo_V_last_V_full_n);
    core_U0->ip2psFifo_V_last_V_write(core_U0_ip2psFifo_V_last_V_write);
    okanonas284_U0 = new okanonas284("okanonas284_U0");
    okanonas284_U0->ap_clk(ap_clk);
    okanonas284_U0->ap_rst(ap_rst_n_inv);
    okanonas284_U0->ap_start(okanonas284_U0_ap_start);
    okanonas284_U0->ap_done(okanonas284_U0_ap_done);
    okanonas284_U0->ap_continue(okanonas284_U0_ap_continue);
    okanonas284_U0->ap_idle(okanonas284_U0_ap_idle);
    okanonas284_U0->ap_ready(okanonas284_U0_ap_ready);
    okanonas284_U0->rule1cnt_V_buf_dout(rule1cnt_V_buf_c31_dout);
    okanonas284_U0->rule1cnt_V_buf_empty_n(rule1cnt_V_buf_c31_empty_n);
    okanonas284_U0->rule1cnt_V_buf_read(okanonas284_U0_rule1cnt_V_buf_read);
    okanonas285_U0 = new okanonas285("okanonas285_U0");
    okanonas285_U0->ap_clk(ap_clk);
    okanonas285_U0->ap_rst(ap_rst_n_inv);
    okanonas285_U0->ap_start(okanonas285_U0_ap_start);
    okanonas285_U0->ap_done(okanonas285_U0_ap_done);
    okanonas285_U0->ap_continue(okanonas285_U0_ap_continue);
    okanonas285_U0->ap_idle(okanonas285_U0_ap_idle);
    okanonas285_U0->ap_ready(okanonas285_U0_ap_ready);
    okanonas285_U0->rule2cnt_V_buf_dout(rule2cnt_V_buf_c32_dout);
    okanonas285_U0->rule2cnt_V_buf_empty_n(rule2cnt_V_buf_c32_empty_n);
    okanonas285_U0->rule2cnt_V_buf_read(okanonas285_U0_rule2cnt_V_buf_read);
    okanonas2_U0 = new okanonas2("okanonas2_U0");
    okanonas2_U0->ap_clk(ap_clk);
    okanonas2_U0->ap_rst(ap_rst_n_inv);
    okanonas2_U0->ap_start(okanonas2_U0_ap_start);
    okanonas2_U0->ap_done(okanonas2_U0_ap_done);
    okanonas2_U0->ap_continue(okanonas2_U0_ap_continue);
    okanonas2_U0->ap_idle(okanonas2_U0_ap_idle);
    okanonas2_U0->ap_ready(okanonas2_U0_ap_ready);
    okanonas2_U0->rule3cnt_V_buf_dout(rule3cnt_V_buf_c33_dout);
    okanonas2_U0->rule3cnt_V_buf_empty_n(rule3cnt_V_buf_c33_empty_n);
    okanonas2_U0->rule3cnt_V_buf_read(okanonas2_U0_rule3cnt_V_buf_read);
    ip2ps_fifo_U0 = new ip2ps_fifo("ip2ps_fifo_U0");
    ip2ps_fifo_U0->ap_clk(ap_clk);
    ip2ps_fifo_U0->ap_rst(ap_rst_n_inv);
    ip2ps_fifo_U0->ap_start(ip2ps_fifo_U0_ap_start);
    ip2ps_fifo_U0->ap_done(ip2ps_fifo_U0_ap_done);
    ip2ps_fifo_U0->ap_continue(ip2ps_fifo_U0_ap_continue);
    ip2ps_fifo_U0->ap_idle(ip2ps_fifo_U0_ap_idle);
    ip2ps_fifo_U0->ap_ready(ip2ps_fifo_U0_ap_ready);
    ip2ps_fifo_U0->masterOut_TREADY(masterOut_TREADY);
    ip2ps_fifo_U0->masterOut_TDATA(ip2ps_fifo_U0_masterOut_TDATA);
    ip2ps_fifo_U0->masterOut_TVALID(ip2ps_fifo_U0_masterOut_TVALID);
    ip2ps_fifo_U0->masterOut_TSTRB(ip2ps_fifo_U0_masterOut_TSTRB);
    ip2ps_fifo_U0->masterOut_TLAST(ip2ps_fifo_U0_masterOut_TLAST);
    ip2ps_fifo_U0->ip2psFifo_V_data_V_dout(ip2psFifo_V_data_V_dout);
    ip2ps_fifo_U0->ip2psFifo_V_data_V_empty_n(ip2psFifo_V_data_V_empty_n);
    ip2ps_fifo_U0->ip2psFifo_V_data_V_read(ip2ps_fifo_U0_ip2psFifo_V_data_V_read);
    ip2ps_fifo_U0->ip2psFifo_V_strb_V_dout(ip2psFifo_V_strb_V_dout);
    ip2ps_fifo_U0->ip2psFifo_V_strb_V_empty_n(ip2psFifo_V_strb_V_empty_n);
    ip2ps_fifo_U0->ip2psFifo_V_strb_V_read(ip2ps_fifo_U0_ip2psFifo_V_strb_V_read);
    ip2ps_fifo_U0->ip2psFifo_V_last_V_dout(ip2psFifo_V_last_V_dout);
    ip2ps_fifo_U0->ip2psFifo_V_last_V_empty_n(ip2psFifo_V_last_V_empty_n);
    ip2ps_fifo_U0->ip2psFifo_V_last_V_read(ip2ps_fifo_U0_ip2psFifo_V_last_V_read);
    rule1_V_c1_U = new fifo_w32_d1_A("rule1_V_c1_U");
    rule1_V_c1_U->clk(ap_clk);
    rule1_V_c1_U->reset(ap_rst_n_inv);
    rule1_V_c1_U->if_read_ce(ap_var_for_const0);
    rule1_V_c1_U->if_write_ce(ap_var_for_const0);
    rule1_V_c1_U->if_din(my_ip_hls_entry3_U0_rule1_V_out_din);
    rule1_V_c1_U->if_full_n(rule1_V_c1_full_n);
    rule1_V_c1_U->if_write(my_ip_hls_entry3_U0_rule1_V_out_write);
    rule1_V_c1_U->if_dout(rule1_V_c1_dout);
    rule1_V_c1_U->if_empty_n(rule1_V_c1_empty_n);
    rule1_V_c1_U->if_read(my_ip_hls_entry90_U0_rule1_V_read);
    rule2_V_c2_U = new fifo_w32_d1_A("rule2_V_c2_U");
    rule2_V_c2_U->clk(ap_clk);
    rule2_V_c2_U->reset(ap_rst_n_inv);
    rule2_V_c2_U->if_read_ce(ap_var_for_const0);
    rule2_V_c2_U->if_write_ce(ap_var_for_const0);
    rule2_V_c2_U->if_din(my_ip_hls_entry3_U0_rule2_V_out_din);
    rule2_V_c2_U->if_full_n(rule2_V_c2_full_n);
    rule2_V_c2_U->if_write(my_ip_hls_entry3_U0_rule2_V_out_write);
    rule2_V_c2_U->if_dout(rule2_V_c2_dout);
    rule2_V_c2_U->if_empty_n(rule2_V_c2_empty_n);
    rule2_V_c2_U->if_read(my_ip_hls_entry90_U0_rule2_V_read);
    rule3_V_c3_U = new fifo_w32_d1_A("rule3_V_c3_U");
    rule3_V_c3_U->clk(ap_clk);
    rule3_V_c3_U->reset(ap_rst_n_inv);
    rule3_V_c3_U->if_read_ce(ap_var_for_const0);
    rule3_V_c3_U->if_write_ce(ap_var_for_const0);
    rule3_V_c3_U->if_din(my_ip_hls_entry3_U0_rule3_V_out_din);
    rule3_V_c3_U->if_full_n(rule3_V_c3_full_n);
    rule3_V_c3_U->if_write(my_ip_hls_entry3_U0_rule3_V_out_write);
    rule3_V_c3_U->if_dout(rule3_V_c3_dout);
    rule3_V_c3_U->if_empty_n(rule3_V_c3_empty_n);
    rule3_V_c3_U->if_read(my_ip_hls_entry90_U0_rule3_V_read);
    rule1cnt_V_c4_U = new fifo_w32_d1_A("rule1cnt_V_c4_U");
    rule1cnt_V_c4_U->clk(ap_clk);
    rule1cnt_V_c4_U->reset(ap_rst_n_inv);
    rule1cnt_V_c4_U->if_read_ce(ap_var_for_const0);
    rule1cnt_V_c4_U->if_write_ce(ap_var_for_const0);
    rule1cnt_V_c4_U->if_din(my_ip_hls_entry3_U0_rule1cnt_V_out_din);
    rule1cnt_V_c4_U->if_full_n(rule1cnt_V_c4_full_n);
    rule1cnt_V_c4_U->if_write(my_ip_hls_entry3_U0_rule1cnt_V_out_write);
    rule1cnt_V_c4_U->if_dout(rule1cnt_V_c4_dout);
    rule1cnt_V_c4_U->if_empty_n(rule1cnt_V_c4_empty_n);
    rule1cnt_V_c4_U->if_read(my_ip_hls_entry90_U0_rule1cnt_V_read);
    rule2cnt_V_c5_U = new fifo_w32_d1_A("rule2cnt_V_c5_U");
    rule2cnt_V_c5_U->clk(ap_clk);
    rule2cnt_V_c5_U->reset(ap_rst_n_inv);
    rule2cnt_V_c5_U->if_read_ce(ap_var_for_const0);
    rule2cnt_V_c5_U->if_write_ce(ap_var_for_const0);
    rule2cnt_V_c5_U->if_din(my_ip_hls_entry3_U0_rule2cnt_V_out_din);
    rule2cnt_V_c5_U->if_full_n(rule2cnt_V_c5_full_n);
    rule2cnt_V_c5_U->if_write(my_ip_hls_entry3_U0_rule2cnt_V_out_write);
    rule2cnt_V_c5_U->if_dout(rule2cnt_V_c5_dout);
    rule2cnt_V_c5_U->if_empty_n(rule2cnt_V_c5_empty_n);
    rule2cnt_V_c5_U->if_read(my_ip_hls_entry90_U0_rule2cnt_V_read);
    rule3cnt_V_c6_U = new fifo_w32_d1_A("rule3cnt_V_c6_U");
    rule3cnt_V_c6_U->clk(ap_clk);
    rule3cnt_V_c6_U->reset(ap_rst_n_inv);
    rule3cnt_V_c6_U->if_read_ce(ap_var_for_const0);
    rule3cnt_V_c6_U->if_write_ce(ap_var_for_const0);
    rule3cnt_V_c6_U->if_din(my_ip_hls_entry3_U0_rule3cnt_V_out_din);
    rule3cnt_V_c6_U->if_full_n(rule3cnt_V_c6_full_n);
    rule3cnt_V_c6_U->if_write(my_ip_hls_entry3_U0_rule3cnt_V_out_write);
    rule3cnt_V_c6_U->if_dout(rule3cnt_V_c6_dout);
    rule3cnt_V_c6_U->if_empty_n(rule3cnt_V_c6_empty_n);
    rule3cnt_V_c6_U->if_read(my_ip_hls_entry90_U0_rule3cnt_V_read);
    rule1_V_c_U = new fifo_w32_d1_A("rule1_V_c_U");
    rule1_V_c_U->clk(ap_clk);
    rule1_V_c_U->reset(ap_rst_n_inv);
    rule1_V_c_U->if_read_ce(ap_var_for_const0);
    rule1_V_c_U->if_write_ce(ap_var_for_const0);
    rule1_V_c_U->if_din(my_ip_hls_entry90_U0_rule1_V_out_din);
    rule1_V_c_U->if_full_n(rule1_V_c_full_n);
    rule1_V_c_U->if_write(my_ip_hls_entry90_U0_rule1_V_out_write);
    rule1_V_c_U->if_dout(rule1_V_c_dout);
    rule1_V_c_U->if_empty_n(rule1_V_c_empty_n);
    rule1_V_c_U->if_read(okanonas82_U0_rule_V_read);
    rule2_V_c_U = new fifo_w32_d1_A("rule2_V_c_U");
    rule2_V_c_U->clk(ap_clk);
    rule2_V_c_U->reset(ap_rst_n_inv);
    rule2_V_c_U->if_read_ce(ap_var_for_const0);
    rule2_V_c_U->if_write_ce(ap_var_for_const0);
    rule2_V_c_U->if_din(my_ip_hls_entry90_U0_rule2_V_out_din);
    rule2_V_c_U->if_full_n(rule2_V_c_full_n);
    rule2_V_c_U->if_write(my_ip_hls_entry90_U0_rule2_V_out_write);
    rule2_V_c_U->if_dout(rule2_V_c_dout);
    rule2_V_c_U->if_empty_n(rule2_V_c_empty_n);
    rule2_V_c_U->if_read(okanonas83_U0_rule_V_read);
    rule3_V_c_U = new fifo_w32_d1_A("rule3_V_c_U");
    rule3_V_c_U->clk(ap_clk);
    rule3_V_c_U->reset(ap_rst_n_inv);
    rule3_V_c_U->if_read_ce(ap_var_for_const0);
    rule3_V_c_U->if_write_ce(ap_var_for_const0);
    rule3_V_c_U->if_din(my_ip_hls_entry90_U0_rule3_V_out_din);
    rule3_V_c_U->if_full_n(rule3_V_c_full_n);
    rule3_V_c_U->if_write(my_ip_hls_entry90_U0_rule3_V_out_write);
    rule3_V_c_U->if_dout(rule3_V_c_dout);
    rule3_V_c_U->if_empty_n(rule3_V_c_empty_n);
    rule3_V_c_U->if_read(okanonas_U0_rule_V_read);
    rule1cnt_V_c_U = new fifo_w32_d1_A("rule1cnt_V_c_U");
    rule1cnt_V_c_U->clk(ap_clk);
    rule1cnt_V_c_U->reset(ap_rst_n_inv);
    rule1cnt_V_c_U->if_read_ce(ap_var_for_const0);
    rule1cnt_V_c_U->if_write_ce(ap_var_for_const0);
    rule1cnt_V_c_U->if_din(my_ip_hls_entry90_U0_rule1cnt_V_out_din);
    rule1cnt_V_c_U->if_full_n(rule1cnt_V_c_full_n);
    rule1cnt_V_c_U->if_write(my_ip_hls_entry90_U0_rule1cnt_V_out_write);
    rule1cnt_V_c_U->if_dout(rule1cnt_V_c_dout);
    rule1cnt_V_c_U->if_empty_n(rule1cnt_V_c_empty_n);
    rule1cnt_V_c_U->if_read(Block_codeRepl6_proc_U0_rule1cnt_V_read);
    rule2cnt_V_c_U = new fifo_w32_d1_A("rule2cnt_V_c_U");
    rule2cnt_V_c_U->clk(ap_clk);
    rule2cnt_V_c_U->reset(ap_rst_n_inv);
    rule2cnt_V_c_U->if_read_ce(ap_var_for_const0);
    rule2cnt_V_c_U->if_write_ce(ap_var_for_const0);
    rule2cnt_V_c_U->if_din(my_ip_hls_entry90_U0_rule2cnt_V_out_din);
    rule2cnt_V_c_U->if_full_n(rule2cnt_V_c_full_n);
    rule2cnt_V_c_U->if_write(my_ip_hls_entry90_U0_rule2cnt_V_out_write);
    rule2cnt_V_c_U->if_dout(rule2cnt_V_c_dout);
    rule2cnt_V_c_U->if_empty_n(rule2cnt_V_c_empty_n);
    rule2cnt_V_c_U->if_read(Block_codeRepl6_proc_U0_rule2cnt_V_read);
    rule3cnt_V_c_U = new fifo_w32_d1_A("rule3cnt_V_c_U");
    rule3cnt_V_c_U->clk(ap_clk);
    rule3cnt_V_c_U->reset(ap_rst_n_inv);
    rule3cnt_V_c_U->if_read_ce(ap_var_for_const0);
    rule3cnt_V_c_U->if_write_ce(ap_var_for_const0);
    rule3cnt_V_c_U->if_din(my_ip_hls_entry90_U0_rule3cnt_V_out_din);
    rule3cnt_V_c_U->if_full_n(rule3cnt_V_c_full_n);
    rule3cnt_V_c_U->if_write(my_ip_hls_entry90_U0_rule3cnt_V_out_write);
    rule3cnt_V_c_U->if_dout(rule3cnt_V_c_dout);
    rule3cnt_V_c_U->if_empty_n(rule3cnt_V_c_empty_n);
    rule3cnt_V_c_U->if_read(Block_codeRepl6_proc_U0_rule3cnt_V_read);
    rule3cnt_V_buf_c_U = new fifo_w32_d1_A("rule3cnt_V_buf_c_U");
    rule3cnt_V_buf_c_U->clk(ap_clk);
    rule3cnt_V_buf_c_U->reset(ap_rst_n_inv);
    rule3cnt_V_buf_c_U->if_read_ce(ap_var_for_const0);
    rule3cnt_V_buf_c_U->if_write_ce(ap_var_for_const0);
    rule3cnt_V_buf_c_U->if_din(Block_codeRepl6_proc_U0_rule3cnt_V_buf_out_din);
    rule3cnt_V_buf_c_U->if_full_n(rule3cnt_V_buf_c_full_n);
    rule3cnt_V_buf_c_U->if_write(Block_codeRepl6_proc_U0_rule3cnt_V_buf_out_write);
    rule3cnt_V_buf_c_U->if_dout(rule3cnt_V_buf_c_dout);
    rule3cnt_V_buf_c_U->if_empty_n(rule3cnt_V_buf_c_empty_n);
    rule3cnt_V_buf_c_U->if_read(core_U0_rule3cnt_V_buf_read);
    rule2cnt_V_buf_c_U = new fifo_w32_d1_A("rule2cnt_V_buf_c_U");
    rule2cnt_V_buf_c_U->clk(ap_clk);
    rule2cnt_V_buf_c_U->reset(ap_rst_n_inv);
    rule2cnt_V_buf_c_U->if_read_ce(ap_var_for_const0);
    rule2cnt_V_buf_c_U->if_write_ce(ap_var_for_const0);
    rule2cnt_V_buf_c_U->if_din(Block_codeRepl6_proc_U0_rule2cnt_V_buf_out_din);
    rule2cnt_V_buf_c_U->if_full_n(rule2cnt_V_buf_c_full_n);
    rule2cnt_V_buf_c_U->if_write(Block_codeRepl6_proc_U0_rule2cnt_V_buf_out_write);
    rule2cnt_V_buf_c_U->if_dout(rule2cnt_V_buf_c_dout);
    rule2cnt_V_buf_c_U->if_empty_n(rule2cnt_V_buf_c_empty_n);
    rule2cnt_V_buf_c_U->if_read(core_U0_rule2cnt_V_buf_read);
    rule1cnt_V_buf_c_U = new fifo_w32_d1_A("rule1cnt_V_buf_c_U");
    rule1cnt_V_buf_c_U->clk(ap_clk);
    rule1cnt_V_buf_c_U->reset(ap_rst_n_inv);
    rule1cnt_V_buf_c_U->if_read_ce(ap_var_for_const0);
    rule1cnt_V_buf_c_U->if_write_ce(ap_var_for_const0);
    rule1cnt_V_buf_c_U->if_din(Block_codeRepl6_proc_U0_rule1cnt_V_buf_out_din);
    rule1cnt_V_buf_c_U->if_full_n(rule1cnt_V_buf_c_full_n);
    rule1cnt_V_buf_c_U->if_write(Block_codeRepl6_proc_U0_rule1cnt_V_buf_out_write);
    rule1cnt_V_buf_c_U->if_dout(rule1cnt_V_buf_c_dout);
    rule1cnt_V_buf_c_U->if_empty_n(rule1cnt_V_buf_c_empty_n);
    rule1cnt_V_buf_c_U->if_read(core_U0_rule1cnt_V_buf_read);
    regrule1_V_channel_U = new fifo_w32_d2_A("regrule1_V_channel_U");
    regrule1_V_channel_U->clk(ap_clk);
    regrule1_V_channel_U->reset(ap_rst_n_inv);
    regrule1_V_channel_U->if_read_ce(ap_var_for_const0);
    regrule1_V_channel_U->if_write_ce(ap_var_for_const0);
    regrule1_V_channel_U->if_din(okanonas82_U0_ap_return);
    regrule1_V_channel_U->if_full_n(regrule1_V_channel_full_n);
    regrule1_V_channel_U->if_write(okanonas82_U0_ap_done);
    regrule1_V_channel_U->if_dout(regrule1_V_channel_dout);
    regrule1_V_channel_U->if_empty_n(regrule1_V_channel_empty_n);
    regrule1_V_channel_U->if_read(core_U0_ap_ready);
    regrule2_V_channel_U = new fifo_w32_d2_A("regrule2_V_channel_U");
    regrule2_V_channel_U->clk(ap_clk);
    regrule2_V_channel_U->reset(ap_rst_n_inv);
    regrule2_V_channel_U->if_read_ce(ap_var_for_const0);
    regrule2_V_channel_U->if_write_ce(ap_var_for_const0);
    regrule2_V_channel_U->if_din(okanonas83_U0_ap_return);
    regrule2_V_channel_U->if_full_n(regrule2_V_channel_full_n);
    regrule2_V_channel_U->if_write(okanonas83_U0_ap_done);
    regrule2_V_channel_U->if_dout(regrule2_V_channel_dout);
    regrule2_V_channel_U->if_empty_n(regrule2_V_channel_empty_n);
    regrule2_V_channel_U->if_read(core_U0_ap_ready);
    regrule3_V_channel_U = new fifo_w32_d2_A("regrule3_V_channel_U");
    regrule3_V_channel_U->clk(ap_clk);
    regrule3_V_channel_U->reset(ap_rst_n_inv);
    regrule3_V_channel_U->if_read_ce(ap_var_for_const0);
    regrule3_V_channel_U->if_write_ce(ap_var_for_const0);
    regrule3_V_channel_U->if_din(okanonas_U0_ap_return);
    regrule3_V_channel_U->if_full_n(regrule3_V_channel_full_n);
    regrule3_V_channel_U->if_write(okanonas_U0_ap_done);
    regrule3_V_channel_U->if_dout(regrule3_V_channel_dout);
    regrule3_V_channel_U->if_empty_n(regrule3_V_channel_empty_n);
    regrule3_V_channel_U->if_read(core_U0_ap_ready);
    ps2ipFifo_V_data_V_U = new fifo_w32_d64_A("ps2ipFifo_V_data_V_U");
    ps2ipFifo_V_data_V_U->clk(ap_clk);
    ps2ipFifo_V_data_V_U->reset(ap_rst_n_inv);
    ps2ipFifo_V_data_V_U->if_read_ce(ap_var_for_const0);
    ps2ipFifo_V_data_V_U->if_write_ce(ap_var_for_const0);
    ps2ipFifo_V_data_V_U->if_din(ps2ip_fifo_U0_ps2ipFifo_V_data_V_din);
    ps2ipFifo_V_data_V_U->if_full_n(ps2ipFifo_V_data_V_full_n);
    ps2ipFifo_V_data_V_U->if_write(ps2ip_fifo_U0_ps2ipFifo_V_data_V_write);
    ps2ipFifo_V_data_V_U->if_dout(ps2ipFifo_V_data_V_dout);
    ps2ipFifo_V_data_V_U->if_empty_n(ps2ipFifo_V_data_V_empty_n);
    ps2ipFifo_V_data_V_U->if_read(core_U0_ps2ipFifo_V_data_V_read);
    ps2ipFifo_V_strb_V_U = new fifo_w4_d64_A("ps2ipFifo_V_strb_V_U");
    ps2ipFifo_V_strb_V_U->clk(ap_clk);
    ps2ipFifo_V_strb_V_U->reset(ap_rst_n_inv);
    ps2ipFifo_V_strb_V_U->if_read_ce(ap_var_for_const0);
    ps2ipFifo_V_strb_V_U->if_write_ce(ap_var_for_const0);
    ps2ipFifo_V_strb_V_U->if_din(ps2ip_fifo_U0_ps2ipFifo_V_strb_V_din);
    ps2ipFifo_V_strb_V_U->if_full_n(ps2ipFifo_V_strb_V_full_n);
    ps2ipFifo_V_strb_V_U->if_write(ps2ip_fifo_U0_ps2ipFifo_V_strb_V_write);
    ps2ipFifo_V_strb_V_U->if_dout(ps2ipFifo_V_strb_V_dout);
    ps2ipFifo_V_strb_V_U->if_empty_n(ps2ipFifo_V_strb_V_empty_n);
    ps2ipFifo_V_strb_V_U->if_read(core_U0_ps2ipFifo_V_strb_V_read);
    ps2ipFifo_V_last_V_U = new fifo_w1_d64_A("ps2ipFifo_V_last_V_U");
    ps2ipFifo_V_last_V_U->clk(ap_clk);
    ps2ipFifo_V_last_V_U->reset(ap_rst_n_inv);
    ps2ipFifo_V_last_V_U->if_read_ce(ap_var_for_const0);
    ps2ipFifo_V_last_V_U->if_write_ce(ap_var_for_const0);
    ps2ipFifo_V_last_V_U->if_din(ps2ip_fifo_U0_ps2ipFifo_V_last_V_din);
    ps2ipFifo_V_last_V_U->if_full_n(ps2ipFifo_V_last_V_full_n);
    ps2ipFifo_V_last_V_U->if_write(ps2ip_fifo_U0_ps2ipFifo_V_last_V_write);
    ps2ipFifo_V_last_V_U->if_dout(ps2ipFifo_V_last_V_dout);
    ps2ipFifo_V_last_V_U->if_empty_n(ps2ipFifo_V_last_V_empty_n);
    ps2ipFifo_V_last_V_U->if_read(core_U0_ps2ipFifo_V_last_V_read);
    rule1cnt_V_buf_c31_U = new fifo_w32_d1_A("rule1cnt_V_buf_c31_U");
    rule1cnt_V_buf_c31_U->clk(ap_clk);
    rule1cnt_V_buf_c31_U->reset(ap_rst_n_inv);
    rule1cnt_V_buf_c31_U->if_read_ce(ap_var_for_const0);
    rule1cnt_V_buf_c31_U->if_write_ce(ap_var_for_const0);
    rule1cnt_V_buf_c31_U->if_din(core_U0_rule1cnt_V_buf_out_din);
    rule1cnt_V_buf_c31_U->if_full_n(rule1cnt_V_buf_c31_full_n);
    rule1cnt_V_buf_c31_U->if_write(core_U0_rule1cnt_V_buf_out_write);
    rule1cnt_V_buf_c31_U->if_dout(rule1cnt_V_buf_c31_dout);
    rule1cnt_V_buf_c31_U->if_empty_n(rule1cnt_V_buf_c31_empty_n);
    rule1cnt_V_buf_c31_U->if_read(okanonas284_U0_rule1cnt_V_buf_read);
    rule2cnt_V_buf_c32_U = new fifo_w32_d1_A("rule2cnt_V_buf_c32_U");
    rule2cnt_V_buf_c32_U->clk(ap_clk);
    rule2cnt_V_buf_c32_U->reset(ap_rst_n_inv);
    rule2cnt_V_buf_c32_U->if_read_ce(ap_var_for_const0);
    rule2cnt_V_buf_c32_U->if_write_ce(ap_var_for_const0);
    rule2cnt_V_buf_c32_U->if_din(core_U0_rule2cnt_V_buf_out_din);
    rule2cnt_V_buf_c32_U->if_full_n(rule2cnt_V_buf_c32_full_n);
    rule2cnt_V_buf_c32_U->if_write(core_U0_rule2cnt_V_buf_out_write);
    rule2cnt_V_buf_c32_U->if_dout(rule2cnt_V_buf_c32_dout);
    rule2cnt_V_buf_c32_U->if_empty_n(rule2cnt_V_buf_c32_empty_n);
    rule2cnt_V_buf_c32_U->if_read(okanonas285_U0_rule2cnt_V_buf_read);
    rule3cnt_V_buf_c33_U = new fifo_w32_d1_A("rule3cnt_V_buf_c33_U");
    rule3cnt_V_buf_c33_U->clk(ap_clk);
    rule3cnt_V_buf_c33_U->reset(ap_rst_n_inv);
    rule3cnt_V_buf_c33_U->if_read_ce(ap_var_for_const0);
    rule3cnt_V_buf_c33_U->if_write_ce(ap_var_for_const0);
    rule3cnt_V_buf_c33_U->if_din(core_U0_rule3cnt_V_buf_out_din);
    rule3cnt_V_buf_c33_U->if_full_n(rule3cnt_V_buf_c33_full_n);
    rule3cnt_V_buf_c33_U->if_write(core_U0_rule3cnt_V_buf_out_write);
    rule3cnt_V_buf_c33_U->if_dout(rule3cnt_V_buf_c33_dout);
    rule3cnt_V_buf_c33_U->if_empty_n(rule3cnt_V_buf_c33_empty_n);
    rule3cnt_V_buf_c33_U->if_read(okanonas2_U0_rule3cnt_V_buf_read);
    ip2psFifo_V_data_V_U = new fifo_w32_d64_A("ip2psFifo_V_data_V_U");
    ip2psFifo_V_data_V_U->clk(ap_clk);
    ip2psFifo_V_data_V_U->reset(ap_rst_n_inv);
    ip2psFifo_V_data_V_U->if_read_ce(ap_var_for_const0);
    ip2psFifo_V_data_V_U->if_write_ce(ap_var_for_const0);
    ip2psFifo_V_data_V_U->if_din(core_U0_ip2psFifo_V_data_V_din);
    ip2psFifo_V_data_V_U->if_full_n(ip2psFifo_V_data_V_full_n);
    ip2psFifo_V_data_V_U->if_write(core_U0_ip2psFifo_V_data_V_write);
    ip2psFifo_V_data_V_U->if_dout(ip2psFifo_V_data_V_dout);
    ip2psFifo_V_data_V_U->if_empty_n(ip2psFifo_V_data_V_empty_n);
    ip2psFifo_V_data_V_U->if_read(ip2ps_fifo_U0_ip2psFifo_V_data_V_read);
    ip2psFifo_V_strb_V_U = new fifo_w4_d64_A("ip2psFifo_V_strb_V_U");
    ip2psFifo_V_strb_V_U->clk(ap_clk);
    ip2psFifo_V_strb_V_U->reset(ap_rst_n_inv);
    ip2psFifo_V_strb_V_U->if_read_ce(ap_var_for_const0);
    ip2psFifo_V_strb_V_U->if_write_ce(ap_var_for_const0);
    ip2psFifo_V_strb_V_U->if_din(core_U0_ip2psFifo_V_strb_V_din);
    ip2psFifo_V_strb_V_U->if_full_n(ip2psFifo_V_strb_V_full_n);
    ip2psFifo_V_strb_V_U->if_write(core_U0_ip2psFifo_V_strb_V_write);
    ip2psFifo_V_strb_V_U->if_dout(ip2psFifo_V_strb_V_dout);
    ip2psFifo_V_strb_V_U->if_empty_n(ip2psFifo_V_strb_V_empty_n);
    ip2psFifo_V_strb_V_U->if_read(ip2ps_fifo_U0_ip2psFifo_V_strb_V_read);
    ip2psFifo_V_last_V_U = new fifo_w1_d64_A("ip2psFifo_V_last_V_U");
    ip2psFifo_V_last_V_U->clk(ap_clk);
    ip2psFifo_V_last_V_U->reset(ap_rst_n_inv);
    ip2psFifo_V_last_V_U->if_read_ce(ap_var_for_const0);
    ip2psFifo_V_last_V_U->if_write_ce(ap_var_for_const0);
    ip2psFifo_V_last_V_U->if_din(core_U0_ip2psFifo_V_last_V_din);
    ip2psFifo_V_last_V_U->if_full_n(ip2psFifo_V_last_V_full_n);
    ip2psFifo_V_last_V_U->if_write(core_U0_ip2psFifo_V_last_V_write);
    ip2psFifo_V_last_V_U->if_dout(ip2psFifo_V_last_V_dout);
    ip2psFifo_V_last_V_U->if_empty_n(ip2psFifo_V_last_V_empty_n);
    ip2psFifo_V_last_V_U->if_read(ip2ps_fifo_U0_ip2psFifo_V_last_V_read);
    start_for_my_ip_hbkb_U = new start_for_my_ip_hbkb("start_for_my_ip_hbkb_U");
    start_for_my_ip_hbkb_U->clk(ap_clk);
    start_for_my_ip_hbkb_U->reset(ap_rst_n_inv);
    start_for_my_ip_hbkb_U->if_read_ce(ap_var_for_const0);
    start_for_my_ip_hbkb_U->if_write_ce(ap_var_for_const0);
    start_for_my_ip_hbkb_U->if_din(start_for_my_ip_hls_entry90_U0_din);
    start_for_my_ip_hbkb_U->if_full_n(start_for_my_ip_hls_entry90_U0_full_n);
    start_for_my_ip_hbkb_U->if_write(my_ip_hls_entry3_U0_start_write);
    start_for_my_ip_hbkb_U->if_dout(start_for_my_ip_hls_entry90_U0_dout);
    start_for_my_ip_hbkb_U->if_empty_n(start_for_my_ip_hls_entry90_U0_empty_n);
    start_for_my_ip_hbkb_U->if_read(my_ip_hls_entry90_U0_ap_ready);
    start_for_Block_ccud_U = new start_for_Block_ccud("start_for_Block_ccud_U");
    start_for_Block_ccud_U->clk(ap_clk);
    start_for_Block_ccud_U->reset(ap_rst_n_inv);
    start_for_Block_ccud_U->if_read_ce(ap_var_for_const0);
    start_for_Block_ccud_U->if_write_ce(ap_var_for_const0);
    start_for_Block_ccud_U->if_din(start_for_Block_codeRepl6_proc_U0_din);
    start_for_Block_ccud_U->if_full_n(start_for_Block_codeRepl6_proc_U0_full_n);
    start_for_Block_ccud_U->if_write(my_ip_hls_entry90_U0_start_write);
    start_for_Block_ccud_U->if_dout(start_for_Block_codeRepl6_proc_U0_dout);
    start_for_Block_ccud_U->if_empty_n(start_for_Block_codeRepl6_proc_U0_empty_n);
    start_for_Block_ccud_U->if_read(Block_codeRepl6_proc_U0_ap_ready);
    start_for_okanonadEe_U = new start_for_okanonadEe("start_for_okanonadEe_U");
    start_for_okanonadEe_U->clk(ap_clk);
    start_for_okanonadEe_U->reset(ap_rst_n_inv);
    start_for_okanonadEe_U->if_read_ce(ap_var_for_const0);
    start_for_okanonadEe_U->if_write_ce(ap_var_for_const0);
    start_for_okanonadEe_U->if_din(start_for_okanonas82_U0_din);
    start_for_okanonadEe_U->if_full_n(start_for_okanonas82_U0_full_n);
    start_for_okanonadEe_U->if_write(my_ip_hls_entry90_U0_start_write);
    start_for_okanonadEe_U->if_dout(start_for_okanonas82_U0_dout);
    start_for_okanonadEe_U->if_empty_n(start_for_okanonas82_U0_empty_n);
    start_for_okanonadEe_U->if_read(okanonas82_U0_ap_ready);
    start_for_okanonaeOg_U = new start_for_okanonaeOg("start_for_okanonaeOg_U");
    start_for_okanonaeOg_U->clk(ap_clk);
    start_for_okanonaeOg_U->reset(ap_rst_n_inv);
    start_for_okanonaeOg_U->if_read_ce(ap_var_for_const0);
    start_for_okanonaeOg_U->if_write_ce(ap_var_for_const0);
    start_for_okanonaeOg_U->if_din(start_for_okanonas83_U0_din);
    start_for_okanonaeOg_U->if_full_n(start_for_okanonas83_U0_full_n);
    start_for_okanonaeOg_U->if_write(my_ip_hls_entry90_U0_start_write);
    start_for_okanonaeOg_U->if_dout(start_for_okanonas83_U0_dout);
    start_for_okanonaeOg_U->if_empty_n(start_for_okanonas83_U0_empty_n);
    start_for_okanonaeOg_U->if_read(okanonas83_U0_ap_ready);
    start_for_okanonafYi_U = new start_for_okanonafYi("start_for_okanonafYi_U");
    start_for_okanonafYi_U->clk(ap_clk);
    start_for_okanonafYi_U->reset(ap_rst_n_inv);
    start_for_okanonafYi_U->if_read_ce(ap_var_for_const0);
    start_for_okanonafYi_U->if_write_ce(ap_var_for_const0);
    start_for_okanonafYi_U->if_din(start_for_okanonas_U0_din);
    start_for_okanonafYi_U->if_full_n(start_for_okanonas_U0_full_n);
    start_for_okanonafYi_U->if_write(my_ip_hls_entry90_U0_start_write);
    start_for_okanonafYi_U->if_dout(start_for_okanonas_U0_dout);
    start_for_okanonafYi_U->if_empty_n(start_for_okanonas_U0_empty_n);
    start_for_okanonafYi_U->if_read(okanonas_U0_ap_ready);
    start_for_okanonag8j_U = new start_for_okanonag8j("start_for_okanonag8j_U");
    start_for_okanonag8j_U->clk(ap_clk);
    start_for_okanonag8j_U->reset(ap_rst_n_inv);
    start_for_okanonag8j_U->if_read_ce(ap_var_for_const0);
    start_for_okanonag8j_U->if_write_ce(ap_var_for_const0);
    start_for_okanonag8j_U->if_din(start_for_okanonas284_U0_din);
    start_for_okanonag8j_U->if_full_n(start_for_okanonas284_U0_full_n);
    start_for_okanonag8j_U->if_write(core_U0_start_write);
    start_for_okanonag8j_U->if_dout(start_for_okanonas284_U0_dout);
    start_for_okanonag8j_U->if_empty_n(start_for_okanonas284_U0_empty_n);
    start_for_okanonag8j_U->if_read(okanonas284_U0_ap_ready);
    start_for_okanonahbi_U = new start_for_okanonahbi("start_for_okanonahbi_U");
    start_for_okanonahbi_U->clk(ap_clk);
    start_for_okanonahbi_U->reset(ap_rst_n_inv);
    start_for_okanonahbi_U->if_read_ce(ap_var_for_const0);
    start_for_okanonahbi_U->if_write_ce(ap_var_for_const0);
    start_for_okanonahbi_U->if_din(start_for_okanonas285_U0_din);
    start_for_okanonahbi_U->if_full_n(start_for_okanonas285_U0_full_n);
    start_for_okanonahbi_U->if_write(core_U0_start_write);
    start_for_okanonahbi_U->if_dout(start_for_okanonas285_U0_dout);
    start_for_okanonahbi_U->if_empty_n(start_for_okanonas285_U0_empty_n);
    start_for_okanonahbi_U->if_read(okanonas285_U0_ap_ready);
    start_for_okanonaibs_U = new start_for_okanonaibs("start_for_okanonaibs_U");
    start_for_okanonaibs_U->clk(ap_clk);
    start_for_okanonaibs_U->reset(ap_rst_n_inv);
    start_for_okanonaibs_U->if_read_ce(ap_var_for_const0);
    start_for_okanonaibs_U->if_write_ce(ap_var_for_const0);
    start_for_okanonaibs_U->if_din(start_for_okanonas2_U0_din);
    start_for_okanonaibs_U->if_full_n(start_for_okanonas2_U0_full_n);
    start_for_okanonaibs_U->if_write(core_U0_start_write);
    start_for_okanonaibs_U->if_dout(start_for_okanonas2_U0_dout);
    start_for_okanonaibs_U->if_empty_n(start_for_okanonas2_U0_empty_n);
    start_for_okanonaibs_U->if_read(okanonas2_U0_ap_ready);
    start_for_ip2ps_fjbC_U = new start_for_ip2ps_fjbC("start_for_ip2ps_fjbC_U");
    start_for_ip2ps_fjbC_U->clk(ap_clk);
    start_for_ip2ps_fjbC_U->reset(ap_rst_n_inv);
    start_for_ip2ps_fjbC_U->if_read_ce(ap_var_for_const0);
    start_for_ip2ps_fjbC_U->if_write_ce(ap_var_for_const0);
    start_for_ip2ps_fjbC_U->if_din(start_for_ip2ps_fifo_U0_din);
    start_for_ip2ps_fjbC_U->if_full_n(start_for_ip2ps_fifo_U0_full_n);
    start_for_ip2ps_fjbC_U->if_write(core_U0_start_write);
    start_for_ip2ps_fjbC_U->if_dout(start_for_ip2ps_fifo_U0_dout);
    start_for_ip2ps_fjbC_U->if_empty_n(start_for_ip2ps_fifo_U0_empty_n);
    start_for_ip2ps_fjbC_U->if_read(ip2ps_fifo_U0_ap_ready);

    SC_METHOD(thread_Block_codeRepl6_proc_U0_ap_continue);

    SC_METHOD(thread_Block_codeRepl6_proc_U0_ap_start);
    sensitive << ( start_for_Block_codeRepl6_proc_U0_empty_n );

    SC_METHOD(thread_Block_codeRepl6_proc_U0_start_full_n);

    SC_METHOD(thread_Block_codeRepl6_proc_U0_start_write);

    SC_METHOD(thread_ap_channel_done_regrule1_V_channel);
    sensitive << ( okanonas82_U0_ap_done );

    SC_METHOD(thread_ap_channel_done_regrule2_V_channel);
    sensitive << ( okanonas83_U0_ap_done );

    SC_METHOD(thread_ap_channel_done_regrule3_V_channel);
    sensitive << ( okanonas_U0_ap_done );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_core_U0_ap_continue);

    SC_METHOD(thread_core_U0_ap_start);
    sensitive << ( regrule1_V_channel_empty_n );
    sensitive << ( regrule2_V_channel_empty_n );
    sensitive << ( regrule3_V_channel_empty_n );

    SC_METHOD(thread_core_U0_start_full_n);
    sensitive << ( start_for_okanonas284_U0_full_n );
    sensitive << ( start_for_okanonas285_U0_full_n );
    sensitive << ( start_for_okanonas2_U0_full_n );
    sensitive << ( start_for_ip2ps_fifo_U0_full_n );

    SC_METHOD(thread_ip2ps_fifo_U0_ap_continue);

    SC_METHOD(thread_ip2ps_fifo_U0_ap_start);
    sensitive << ( start_for_ip2ps_fifo_U0_empty_n );

    SC_METHOD(thread_ip2ps_fifo_U0_start_full_n);

    SC_METHOD(thread_ip2ps_fifo_U0_start_write);

    SC_METHOD(thread_masterOut_TDATA);
    sensitive << ( ip2ps_fifo_U0_masterOut_TDATA );

    SC_METHOD(thread_masterOut_TLAST);
    sensitive << ( ip2ps_fifo_U0_masterOut_TLAST );

    SC_METHOD(thread_masterOut_TSTRB);
    sensitive << ( ip2ps_fifo_U0_masterOut_TSTRB );

    SC_METHOD(thread_masterOut_TVALID);
    sensitive << ( ip2ps_fifo_U0_masterOut_TVALID );

    SC_METHOD(thread_my_ip_hls_entry3_U0_ap_continue);

    SC_METHOD(thread_my_ip_hls_entry3_U0_ap_start);

    SC_METHOD(thread_my_ip_hls_entry90_U0_ap_continue);

    SC_METHOD(thread_my_ip_hls_entry90_U0_ap_start);
    sensitive << ( start_for_my_ip_hls_entry90_U0_empty_n );

    SC_METHOD(thread_my_ip_hls_entry90_U0_start_full_n);
    sensitive << ( start_for_Block_codeRepl6_proc_U0_full_n );
    sensitive << ( start_for_okanonas82_U0_full_n );
    sensitive << ( start_for_okanonas83_U0_full_n );
    sensitive << ( start_for_okanonas_U0_full_n );

    SC_METHOD(thread_okanonas284_U0_ap_continue);

    SC_METHOD(thread_okanonas284_U0_ap_start);
    sensitive << ( start_for_okanonas284_U0_empty_n );

    SC_METHOD(thread_okanonas284_U0_start_full_n);

    SC_METHOD(thread_okanonas284_U0_start_write);

    SC_METHOD(thread_okanonas285_U0_ap_continue);

    SC_METHOD(thread_okanonas285_U0_ap_start);
    sensitive << ( start_for_okanonas285_U0_empty_n );

    SC_METHOD(thread_okanonas285_U0_start_full_n);

    SC_METHOD(thread_okanonas285_U0_start_write);

    SC_METHOD(thread_okanonas2_U0_ap_continue);

    SC_METHOD(thread_okanonas2_U0_ap_start);
    sensitive << ( start_for_okanonas2_U0_empty_n );

    SC_METHOD(thread_okanonas2_U0_start_full_n);

    SC_METHOD(thread_okanonas2_U0_start_write);

    SC_METHOD(thread_okanonas82_U0_ap_continue);
    sensitive << ( regrule1_V_channel_full_n );

    SC_METHOD(thread_okanonas82_U0_ap_start);
    sensitive << ( start_for_okanonas82_U0_empty_n );

    SC_METHOD(thread_okanonas82_U0_start_full_n);

    SC_METHOD(thread_okanonas82_U0_start_write);

    SC_METHOD(thread_okanonas83_U0_ap_continue);
    sensitive << ( regrule2_V_channel_full_n );

    SC_METHOD(thread_okanonas83_U0_ap_start);
    sensitive << ( start_for_okanonas83_U0_empty_n );

    SC_METHOD(thread_okanonas83_U0_start_full_n);

    SC_METHOD(thread_okanonas83_U0_start_write);

    SC_METHOD(thread_okanonas_U0_ap_continue);
    sensitive << ( regrule3_V_channel_full_n );

    SC_METHOD(thread_okanonas_U0_ap_start);
    sensitive << ( start_for_okanonas_U0_empty_n );

    SC_METHOD(thread_okanonas_U0_start_full_n);

    SC_METHOD(thread_okanonas_U0_start_write);

    SC_METHOD(thread_ps2ip_fifo_U0_ap_continue);

    SC_METHOD(thread_ps2ip_fifo_U0_ap_start);

    SC_METHOD(thread_ps2ip_fifo_U0_start_full_n);

    SC_METHOD(thread_ps2ip_fifo_U0_start_write);

    SC_METHOD(thread_slaveIn_TREADY);
    sensitive << ( ps2ip_fifo_U0_slaveIn_TREADY );

    SC_METHOD(thread_start_for_Block_codeRepl6_proc_U0_din);

    SC_METHOD(thread_start_for_ip2ps_fifo_U0_din);

    SC_METHOD(thread_start_for_my_ip_hls_entry90_U0_din);

    SC_METHOD(thread_start_for_okanonas284_U0_din);

    SC_METHOD(thread_start_for_okanonas285_U0_din);

    SC_METHOD(thread_start_for_okanonas2_U0_din);

    SC_METHOD(thread_start_for_okanonas82_U0_din);

    SC_METHOD(thread_start_for_okanonas83_U0_din);

    SC_METHOD(thread_start_for_okanonas_U0_din);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "my_ip_hls_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, s_axi_ziskasrules_AWVALID, "(port)s_axi_ziskasrules_AWVALID");
    sc_trace(mVcdFile, s_axi_ziskasrules_AWREADY, "(port)s_axi_ziskasrules_AWREADY");
    sc_trace(mVcdFile, s_axi_ziskasrules_AWADDR, "(port)s_axi_ziskasrules_AWADDR");
    sc_trace(mVcdFile, s_axi_ziskasrules_WVALID, "(port)s_axi_ziskasrules_WVALID");
    sc_trace(mVcdFile, s_axi_ziskasrules_WREADY, "(port)s_axi_ziskasrules_WREADY");
    sc_trace(mVcdFile, s_axi_ziskasrules_WDATA, "(port)s_axi_ziskasrules_WDATA");
    sc_trace(mVcdFile, s_axi_ziskasrules_WSTRB, "(port)s_axi_ziskasrules_WSTRB");
    sc_trace(mVcdFile, s_axi_ziskasrules_ARVALID, "(port)s_axi_ziskasrules_ARVALID");
    sc_trace(mVcdFile, s_axi_ziskasrules_ARREADY, "(port)s_axi_ziskasrules_ARREADY");
    sc_trace(mVcdFile, s_axi_ziskasrules_ARADDR, "(port)s_axi_ziskasrules_ARADDR");
    sc_trace(mVcdFile, s_axi_ziskasrules_RVALID, "(port)s_axi_ziskasrules_RVALID");
    sc_trace(mVcdFile, s_axi_ziskasrules_RREADY, "(port)s_axi_ziskasrules_RREADY");
    sc_trace(mVcdFile, s_axi_ziskasrules_RDATA, "(port)s_axi_ziskasrules_RDATA");
    sc_trace(mVcdFile, s_axi_ziskasrules_RRESP, "(port)s_axi_ziskasrules_RRESP");
    sc_trace(mVcdFile, s_axi_ziskasrules_BVALID, "(port)s_axi_ziskasrules_BVALID");
    sc_trace(mVcdFile, s_axi_ziskasrules_BREADY, "(port)s_axi_ziskasrules_BREADY");
    sc_trace(mVcdFile, s_axi_ziskasrules_BRESP, "(port)s_axi_ziskasrules_BRESP");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, slaveIn_TDATA, "(port)slaveIn_TDATA");
    sc_trace(mVcdFile, slaveIn_TSTRB, "(port)slaveIn_TSTRB");
    sc_trace(mVcdFile, slaveIn_TLAST, "(port)slaveIn_TLAST");
    sc_trace(mVcdFile, masterOut_TDATA, "(port)masterOut_TDATA");
    sc_trace(mVcdFile, masterOut_TSTRB, "(port)masterOut_TSTRB");
    sc_trace(mVcdFile, masterOut_TLAST, "(port)masterOut_TLAST");
    sc_trace(mVcdFile, slaveIn_TVALID, "(port)slaveIn_TVALID");
    sc_trace(mVcdFile, slaveIn_TREADY, "(port)slaveIn_TREADY");
    sc_trace(mVcdFile, masterOut_TVALID, "(port)masterOut_TVALID");
    sc_trace(mVcdFile, masterOut_TREADY, "(port)masterOut_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, rule1_V, "rule1_V");
    sc_trace(mVcdFile, rule2_V, "rule2_V");
    sc_trace(mVcdFile, rule3_V, "rule3_V");
    sc_trace(mVcdFile, rule1cnt_V, "rule1cnt_V");
    sc_trace(mVcdFile, rule2cnt_V, "rule2cnt_V");
    sc_trace(mVcdFile, rule3cnt_V, "rule3cnt_V");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_ap_start, "my_ip_hls_entry3_U0_ap_start");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_ap_done, "my_ip_hls_entry3_U0_ap_done");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_ap_continue, "my_ip_hls_entry3_U0_ap_continue");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_ap_idle, "my_ip_hls_entry3_U0_ap_idle");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_ap_ready, "my_ip_hls_entry3_U0_ap_ready");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_start_out, "my_ip_hls_entry3_U0_start_out");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_start_write, "my_ip_hls_entry3_U0_start_write");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_rule1_V_out_din, "my_ip_hls_entry3_U0_rule1_V_out_din");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_rule1_V_out_write, "my_ip_hls_entry3_U0_rule1_V_out_write");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_rule2_V_out_din, "my_ip_hls_entry3_U0_rule2_V_out_din");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_rule2_V_out_write, "my_ip_hls_entry3_U0_rule2_V_out_write");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_rule3_V_out_din, "my_ip_hls_entry3_U0_rule3_V_out_din");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_rule3_V_out_write, "my_ip_hls_entry3_U0_rule3_V_out_write");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_rule1cnt_V_out_din, "my_ip_hls_entry3_U0_rule1cnt_V_out_din");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_rule1cnt_V_out_write, "my_ip_hls_entry3_U0_rule1cnt_V_out_write");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_rule2cnt_V_out_din, "my_ip_hls_entry3_U0_rule2cnt_V_out_din");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_rule2cnt_V_out_write, "my_ip_hls_entry3_U0_rule2cnt_V_out_write");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_rule3cnt_V_out_din, "my_ip_hls_entry3_U0_rule3cnt_V_out_din");
    sc_trace(mVcdFile, my_ip_hls_entry3_U0_rule3cnt_V_out_write, "my_ip_hls_entry3_U0_rule3cnt_V_out_write");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_ap_start, "my_ip_hls_entry90_U0_ap_start");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_start_full_n, "my_ip_hls_entry90_U0_start_full_n");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_ap_done, "my_ip_hls_entry90_U0_ap_done");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_ap_continue, "my_ip_hls_entry90_U0_ap_continue");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_ap_idle, "my_ip_hls_entry90_U0_ap_idle");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_ap_ready, "my_ip_hls_entry90_U0_ap_ready");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_start_out, "my_ip_hls_entry90_U0_start_out");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_start_write, "my_ip_hls_entry90_U0_start_write");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_rule1_V_read, "my_ip_hls_entry90_U0_rule1_V_read");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_rule2_V_read, "my_ip_hls_entry90_U0_rule2_V_read");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_rule3_V_read, "my_ip_hls_entry90_U0_rule3_V_read");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_rule1cnt_V_read, "my_ip_hls_entry90_U0_rule1cnt_V_read");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_rule2cnt_V_read, "my_ip_hls_entry90_U0_rule2cnt_V_read");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_rule3cnt_V_read, "my_ip_hls_entry90_U0_rule3cnt_V_read");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_rule1_V_out_din, "my_ip_hls_entry90_U0_rule1_V_out_din");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_rule1_V_out_write, "my_ip_hls_entry90_U0_rule1_V_out_write");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_rule2_V_out_din, "my_ip_hls_entry90_U0_rule2_V_out_din");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_rule2_V_out_write, "my_ip_hls_entry90_U0_rule2_V_out_write");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_rule3_V_out_din, "my_ip_hls_entry90_U0_rule3_V_out_din");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_rule3_V_out_write, "my_ip_hls_entry90_U0_rule3_V_out_write");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_rule1cnt_V_out_din, "my_ip_hls_entry90_U0_rule1cnt_V_out_din");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_rule1cnt_V_out_write, "my_ip_hls_entry90_U0_rule1cnt_V_out_write");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_rule2cnt_V_out_din, "my_ip_hls_entry90_U0_rule2cnt_V_out_din");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_rule2cnt_V_out_write, "my_ip_hls_entry90_U0_rule2cnt_V_out_write");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_rule3cnt_V_out_din, "my_ip_hls_entry90_U0_rule3cnt_V_out_din");
    sc_trace(mVcdFile, my_ip_hls_entry90_U0_rule3cnt_V_out_write, "my_ip_hls_entry90_U0_rule3cnt_V_out_write");
    sc_trace(mVcdFile, Block_codeRepl6_proc_U0_ap_start, "Block_codeRepl6_proc_U0_ap_start");
    sc_trace(mVcdFile, Block_codeRepl6_proc_U0_ap_done, "Block_codeRepl6_proc_U0_ap_done");
    sc_trace(mVcdFile, Block_codeRepl6_proc_U0_ap_continue, "Block_codeRepl6_proc_U0_ap_continue");
    sc_trace(mVcdFile, Block_codeRepl6_proc_U0_ap_idle, "Block_codeRepl6_proc_U0_ap_idle");
    sc_trace(mVcdFile, Block_codeRepl6_proc_U0_ap_ready, "Block_codeRepl6_proc_U0_ap_ready");
    sc_trace(mVcdFile, Block_codeRepl6_proc_U0_rule3cnt_V_read, "Block_codeRepl6_proc_U0_rule3cnt_V_read");
    sc_trace(mVcdFile, Block_codeRepl6_proc_U0_rule2cnt_V_read, "Block_codeRepl6_proc_U0_rule2cnt_V_read");
    sc_trace(mVcdFile, Block_codeRepl6_proc_U0_rule1cnt_V_read, "Block_codeRepl6_proc_U0_rule1cnt_V_read");
    sc_trace(mVcdFile, Block_codeRepl6_proc_U0_rule3cnt_V_buf_out_din, "Block_codeRepl6_proc_U0_rule3cnt_V_buf_out_din");
    sc_trace(mVcdFile, Block_codeRepl6_proc_U0_rule3cnt_V_buf_out_write, "Block_codeRepl6_proc_U0_rule3cnt_V_buf_out_write");
    sc_trace(mVcdFile, Block_codeRepl6_proc_U0_rule2cnt_V_buf_out_din, "Block_codeRepl6_proc_U0_rule2cnt_V_buf_out_din");
    sc_trace(mVcdFile, Block_codeRepl6_proc_U0_rule2cnt_V_buf_out_write, "Block_codeRepl6_proc_U0_rule2cnt_V_buf_out_write");
    sc_trace(mVcdFile, Block_codeRepl6_proc_U0_rule1cnt_V_buf_out_din, "Block_codeRepl6_proc_U0_rule1cnt_V_buf_out_din");
    sc_trace(mVcdFile, Block_codeRepl6_proc_U0_rule1cnt_V_buf_out_write, "Block_codeRepl6_proc_U0_rule1cnt_V_buf_out_write");
    sc_trace(mVcdFile, okanonas82_U0_ap_start, "okanonas82_U0_ap_start");
    sc_trace(mVcdFile, okanonas82_U0_ap_done, "okanonas82_U0_ap_done");
    sc_trace(mVcdFile, okanonas82_U0_ap_continue, "okanonas82_U0_ap_continue");
    sc_trace(mVcdFile, okanonas82_U0_ap_idle, "okanonas82_U0_ap_idle");
    sc_trace(mVcdFile, okanonas82_U0_ap_ready, "okanonas82_U0_ap_ready");
    sc_trace(mVcdFile, okanonas82_U0_rule_V_read, "okanonas82_U0_rule_V_read");
    sc_trace(mVcdFile, okanonas82_U0_ap_return, "okanonas82_U0_ap_return");
    sc_trace(mVcdFile, ap_channel_done_regrule1_V_channel, "ap_channel_done_regrule1_V_channel");
    sc_trace(mVcdFile, regrule1_V_channel_full_n, "regrule1_V_channel_full_n");
    sc_trace(mVcdFile, okanonas83_U0_ap_start, "okanonas83_U0_ap_start");
    sc_trace(mVcdFile, okanonas83_U0_ap_done, "okanonas83_U0_ap_done");
    sc_trace(mVcdFile, okanonas83_U0_ap_continue, "okanonas83_U0_ap_continue");
    sc_trace(mVcdFile, okanonas83_U0_ap_idle, "okanonas83_U0_ap_idle");
    sc_trace(mVcdFile, okanonas83_U0_ap_ready, "okanonas83_U0_ap_ready");
    sc_trace(mVcdFile, okanonas83_U0_rule_V_read, "okanonas83_U0_rule_V_read");
    sc_trace(mVcdFile, okanonas83_U0_ap_return, "okanonas83_U0_ap_return");
    sc_trace(mVcdFile, ap_channel_done_regrule2_V_channel, "ap_channel_done_regrule2_V_channel");
    sc_trace(mVcdFile, regrule2_V_channel_full_n, "regrule2_V_channel_full_n");
    sc_trace(mVcdFile, okanonas_U0_ap_start, "okanonas_U0_ap_start");
    sc_trace(mVcdFile, okanonas_U0_ap_done, "okanonas_U0_ap_done");
    sc_trace(mVcdFile, okanonas_U0_ap_continue, "okanonas_U0_ap_continue");
    sc_trace(mVcdFile, okanonas_U0_ap_idle, "okanonas_U0_ap_idle");
    sc_trace(mVcdFile, okanonas_U0_ap_ready, "okanonas_U0_ap_ready");
    sc_trace(mVcdFile, okanonas_U0_rule_V_read, "okanonas_U0_rule_V_read");
    sc_trace(mVcdFile, okanonas_U0_ap_return, "okanonas_U0_ap_return");
    sc_trace(mVcdFile, ap_channel_done_regrule3_V_channel, "ap_channel_done_regrule3_V_channel");
    sc_trace(mVcdFile, regrule3_V_channel_full_n, "regrule3_V_channel_full_n");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ap_start, "ps2ip_fifo_U0_ap_start");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ap_done, "ps2ip_fifo_U0_ap_done");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ap_continue, "ps2ip_fifo_U0_ap_continue");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ap_idle, "ps2ip_fifo_U0_ap_idle");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ap_ready, "ps2ip_fifo_U0_ap_ready");
    sc_trace(mVcdFile, ps2ip_fifo_U0_slaveIn_TREADY, "ps2ip_fifo_U0_slaveIn_TREADY");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ps2ipFifo_V_data_V_din, "ps2ip_fifo_U0_ps2ipFifo_V_data_V_din");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ps2ipFifo_V_data_V_write, "ps2ip_fifo_U0_ps2ipFifo_V_data_V_write");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ps2ipFifo_V_strb_V_din, "ps2ip_fifo_U0_ps2ipFifo_V_strb_V_din");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ps2ipFifo_V_strb_V_write, "ps2ip_fifo_U0_ps2ipFifo_V_strb_V_write");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ps2ipFifo_V_last_V_din, "ps2ip_fifo_U0_ps2ipFifo_V_last_V_din");
    sc_trace(mVcdFile, ps2ip_fifo_U0_ps2ipFifo_V_last_V_write, "ps2ip_fifo_U0_ps2ipFifo_V_last_V_write");
    sc_trace(mVcdFile, core_U0_ap_start, "core_U0_ap_start");
    sc_trace(mVcdFile, core_U0_start_full_n, "core_U0_start_full_n");
    sc_trace(mVcdFile, core_U0_ap_done, "core_U0_ap_done");
    sc_trace(mVcdFile, core_U0_ap_continue, "core_U0_ap_continue");
    sc_trace(mVcdFile, core_U0_ap_idle, "core_U0_ap_idle");
    sc_trace(mVcdFile, core_U0_ap_ready, "core_U0_ap_ready");
    sc_trace(mVcdFile, core_U0_rule1cnt_V_buf_read, "core_U0_rule1cnt_V_buf_read");
    sc_trace(mVcdFile, core_U0_rule2cnt_V_buf_read, "core_U0_rule2cnt_V_buf_read");
    sc_trace(mVcdFile, core_U0_rule3cnt_V_buf_read, "core_U0_rule3cnt_V_buf_read");
    sc_trace(mVcdFile, core_U0_rule1cnt_V_buf_out_din, "core_U0_rule1cnt_V_buf_out_din");
    sc_trace(mVcdFile, core_U0_rule1cnt_V_buf_out_write, "core_U0_rule1cnt_V_buf_out_write");
    sc_trace(mVcdFile, core_U0_rule2cnt_V_buf_out_din, "core_U0_rule2cnt_V_buf_out_din");
    sc_trace(mVcdFile, core_U0_rule2cnt_V_buf_out_write, "core_U0_rule2cnt_V_buf_out_write");
    sc_trace(mVcdFile, core_U0_rule3cnt_V_buf_out_din, "core_U0_rule3cnt_V_buf_out_din");
    sc_trace(mVcdFile, core_U0_rule3cnt_V_buf_out_write, "core_U0_rule3cnt_V_buf_out_write");
    sc_trace(mVcdFile, core_U0_start_out, "core_U0_start_out");
    sc_trace(mVcdFile, core_U0_start_write, "core_U0_start_write");
    sc_trace(mVcdFile, core_U0_ps2ipFifo_V_data_V_read, "core_U0_ps2ipFifo_V_data_V_read");
    sc_trace(mVcdFile, core_U0_ps2ipFifo_V_strb_V_read, "core_U0_ps2ipFifo_V_strb_V_read");
    sc_trace(mVcdFile, core_U0_ps2ipFifo_V_last_V_read, "core_U0_ps2ipFifo_V_last_V_read");
    sc_trace(mVcdFile, core_U0_ip2psFifo_V_data_V_din, "core_U0_ip2psFifo_V_data_V_din");
    sc_trace(mVcdFile, core_U0_ip2psFifo_V_data_V_write, "core_U0_ip2psFifo_V_data_V_write");
    sc_trace(mVcdFile, core_U0_ip2psFifo_V_strb_V_din, "core_U0_ip2psFifo_V_strb_V_din");
    sc_trace(mVcdFile, core_U0_ip2psFifo_V_strb_V_write, "core_U0_ip2psFifo_V_strb_V_write");
    sc_trace(mVcdFile, core_U0_ip2psFifo_V_last_V_din, "core_U0_ip2psFifo_V_last_V_din");
    sc_trace(mVcdFile, core_U0_ip2psFifo_V_last_V_write, "core_U0_ip2psFifo_V_last_V_write");
    sc_trace(mVcdFile, okanonas284_U0_ap_start, "okanonas284_U0_ap_start");
    sc_trace(mVcdFile, okanonas284_U0_ap_done, "okanonas284_U0_ap_done");
    sc_trace(mVcdFile, okanonas284_U0_ap_continue, "okanonas284_U0_ap_continue");
    sc_trace(mVcdFile, okanonas284_U0_ap_idle, "okanonas284_U0_ap_idle");
    sc_trace(mVcdFile, okanonas284_U0_ap_ready, "okanonas284_U0_ap_ready");
    sc_trace(mVcdFile, okanonas284_U0_rule1cnt_V_buf_read, "okanonas284_U0_rule1cnt_V_buf_read");
    sc_trace(mVcdFile, okanonas285_U0_ap_start, "okanonas285_U0_ap_start");
    sc_trace(mVcdFile, okanonas285_U0_ap_done, "okanonas285_U0_ap_done");
    sc_trace(mVcdFile, okanonas285_U0_ap_continue, "okanonas285_U0_ap_continue");
    sc_trace(mVcdFile, okanonas285_U0_ap_idle, "okanonas285_U0_ap_idle");
    sc_trace(mVcdFile, okanonas285_U0_ap_ready, "okanonas285_U0_ap_ready");
    sc_trace(mVcdFile, okanonas285_U0_rule2cnt_V_buf_read, "okanonas285_U0_rule2cnt_V_buf_read");
    sc_trace(mVcdFile, okanonas2_U0_ap_start, "okanonas2_U0_ap_start");
    sc_trace(mVcdFile, okanonas2_U0_ap_done, "okanonas2_U0_ap_done");
    sc_trace(mVcdFile, okanonas2_U0_ap_continue, "okanonas2_U0_ap_continue");
    sc_trace(mVcdFile, okanonas2_U0_ap_idle, "okanonas2_U0_ap_idle");
    sc_trace(mVcdFile, okanonas2_U0_ap_ready, "okanonas2_U0_ap_ready");
    sc_trace(mVcdFile, okanonas2_U0_rule3cnt_V_buf_read, "okanonas2_U0_rule3cnt_V_buf_read");
    sc_trace(mVcdFile, ip2ps_fifo_U0_ap_start, "ip2ps_fifo_U0_ap_start");
    sc_trace(mVcdFile, ip2ps_fifo_U0_ap_done, "ip2ps_fifo_U0_ap_done");
    sc_trace(mVcdFile, ip2ps_fifo_U0_ap_continue, "ip2ps_fifo_U0_ap_continue");
    sc_trace(mVcdFile, ip2ps_fifo_U0_ap_idle, "ip2ps_fifo_U0_ap_idle");
    sc_trace(mVcdFile, ip2ps_fifo_U0_ap_ready, "ip2ps_fifo_U0_ap_ready");
    sc_trace(mVcdFile, ip2ps_fifo_U0_masterOut_TDATA, "ip2ps_fifo_U0_masterOut_TDATA");
    sc_trace(mVcdFile, ip2ps_fifo_U0_masterOut_TVALID, "ip2ps_fifo_U0_masterOut_TVALID");
    sc_trace(mVcdFile, ip2ps_fifo_U0_masterOut_TSTRB, "ip2ps_fifo_U0_masterOut_TSTRB");
    sc_trace(mVcdFile, ip2ps_fifo_U0_masterOut_TLAST, "ip2ps_fifo_U0_masterOut_TLAST");
    sc_trace(mVcdFile, ip2ps_fifo_U0_ip2psFifo_V_data_V_read, "ip2ps_fifo_U0_ip2psFifo_V_data_V_read");
    sc_trace(mVcdFile, ip2ps_fifo_U0_ip2psFifo_V_strb_V_read, "ip2ps_fifo_U0_ip2psFifo_V_strb_V_read");
    sc_trace(mVcdFile, ip2ps_fifo_U0_ip2psFifo_V_last_V_read, "ip2ps_fifo_U0_ip2psFifo_V_last_V_read");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, rule1_V_c1_full_n, "rule1_V_c1_full_n");
    sc_trace(mVcdFile, rule1_V_c1_dout, "rule1_V_c1_dout");
    sc_trace(mVcdFile, rule1_V_c1_empty_n, "rule1_V_c1_empty_n");
    sc_trace(mVcdFile, rule2_V_c2_full_n, "rule2_V_c2_full_n");
    sc_trace(mVcdFile, rule2_V_c2_dout, "rule2_V_c2_dout");
    sc_trace(mVcdFile, rule2_V_c2_empty_n, "rule2_V_c2_empty_n");
    sc_trace(mVcdFile, rule3_V_c3_full_n, "rule3_V_c3_full_n");
    sc_trace(mVcdFile, rule3_V_c3_dout, "rule3_V_c3_dout");
    sc_trace(mVcdFile, rule3_V_c3_empty_n, "rule3_V_c3_empty_n");
    sc_trace(mVcdFile, rule1cnt_V_c4_full_n, "rule1cnt_V_c4_full_n");
    sc_trace(mVcdFile, rule1cnt_V_c4_dout, "rule1cnt_V_c4_dout");
    sc_trace(mVcdFile, rule1cnt_V_c4_empty_n, "rule1cnt_V_c4_empty_n");
    sc_trace(mVcdFile, rule2cnt_V_c5_full_n, "rule2cnt_V_c5_full_n");
    sc_trace(mVcdFile, rule2cnt_V_c5_dout, "rule2cnt_V_c5_dout");
    sc_trace(mVcdFile, rule2cnt_V_c5_empty_n, "rule2cnt_V_c5_empty_n");
    sc_trace(mVcdFile, rule3cnt_V_c6_full_n, "rule3cnt_V_c6_full_n");
    sc_trace(mVcdFile, rule3cnt_V_c6_dout, "rule3cnt_V_c6_dout");
    sc_trace(mVcdFile, rule3cnt_V_c6_empty_n, "rule3cnt_V_c6_empty_n");
    sc_trace(mVcdFile, rule1_V_c_full_n, "rule1_V_c_full_n");
    sc_trace(mVcdFile, rule1_V_c_dout, "rule1_V_c_dout");
    sc_trace(mVcdFile, rule1_V_c_empty_n, "rule1_V_c_empty_n");
    sc_trace(mVcdFile, rule2_V_c_full_n, "rule2_V_c_full_n");
    sc_trace(mVcdFile, rule2_V_c_dout, "rule2_V_c_dout");
    sc_trace(mVcdFile, rule2_V_c_empty_n, "rule2_V_c_empty_n");
    sc_trace(mVcdFile, rule3_V_c_full_n, "rule3_V_c_full_n");
    sc_trace(mVcdFile, rule3_V_c_dout, "rule3_V_c_dout");
    sc_trace(mVcdFile, rule3_V_c_empty_n, "rule3_V_c_empty_n");
    sc_trace(mVcdFile, rule1cnt_V_c_full_n, "rule1cnt_V_c_full_n");
    sc_trace(mVcdFile, rule1cnt_V_c_dout, "rule1cnt_V_c_dout");
    sc_trace(mVcdFile, rule1cnt_V_c_empty_n, "rule1cnt_V_c_empty_n");
    sc_trace(mVcdFile, rule2cnt_V_c_full_n, "rule2cnt_V_c_full_n");
    sc_trace(mVcdFile, rule2cnt_V_c_dout, "rule2cnt_V_c_dout");
    sc_trace(mVcdFile, rule2cnt_V_c_empty_n, "rule2cnt_V_c_empty_n");
    sc_trace(mVcdFile, rule3cnt_V_c_full_n, "rule3cnt_V_c_full_n");
    sc_trace(mVcdFile, rule3cnt_V_c_dout, "rule3cnt_V_c_dout");
    sc_trace(mVcdFile, rule3cnt_V_c_empty_n, "rule3cnt_V_c_empty_n");
    sc_trace(mVcdFile, rule3cnt_V_buf_c_full_n, "rule3cnt_V_buf_c_full_n");
    sc_trace(mVcdFile, rule3cnt_V_buf_c_dout, "rule3cnt_V_buf_c_dout");
    sc_trace(mVcdFile, rule3cnt_V_buf_c_empty_n, "rule3cnt_V_buf_c_empty_n");
    sc_trace(mVcdFile, rule2cnt_V_buf_c_full_n, "rule2cnt_V_buf_c_full_n");
    sc_trace(mVcdFile, rule2cnt_V_buf_c_dout, "rule2cnt_V_buf_c_dout");
    sc_trace(mVcdFile, rule2cnt_V_buf_c_empty_n, "rule2cnt_V_buf_c_empty_n");
    sc_trace(mVcdFile, rule1cnt_V_buf_c_full_n, "rule1cnt_V_buf_c_full_n");
    sc_trace(mVcdFile, rule1cnt_V_buf_c_dout, "rule1cnt_V_buf_c_dout");
    sc_trace(mVcdFile, rule1cnt_V_buf_c_empty_n, "rule1cnt_V_buf_c_empty_n");
    sc_trace(mVcdFile, regrule1_V_channel_dout, "regrule1_V_channel_dout");
    sc_trace(mVcdFile, regrule1_V_channel_empty_n, "regrule1_V_channel_empty_n");
    sc_trace(mVcdFile, regrule2_V_channel_dout, "regrule2_V_channel_dout");
    sc_trace(mVcdFile, regrule2_V_channel_empty_n, "regrule2_V_channel_empty_n");
    sc_trace(mVcdFile, regrule3_V_channel_dout, "regrule3_V_channel_dout");
    sc_trace(mVcdFile, regrule3_V_channel_empty_n, "regrule3_V_channel_empty_n");
    sc_trace(mVcdFile, ps2ipFifo_V_data_V_full_n, "ps2ipFifo_V_data_V_full_n");
    sc_trace(mVcdFile, ps2ipFifo_V_data_V_dout, "ps2ipFifo_V_data_V_dout");
    sc_trace(mVcdFile, ps2ipFifo_V_data_V_empty_n, "ps2ipFifo_V_data_V_empty_n");
    sc_trace(mVcdFile, ps2ipFifo_V_strb_V_full_n, "ps2ipFifo_V_strb_V_full_n");
    sc_trace(mVcdFile, ps2ipFifo_V_strb_V_dout, "ps2ipFifo_V_strb_V_dout");
    sc_trace(mVcdFile, ps2ipFifo_V_strb_V_empty_n, "ps2ipFifo_V_strb_V_empty_n");
    sc_trace(mVcdFile, ps2ipFifo_V_last_V_full_n, "ps2ipFifo_V_last_V_full_n");
    sc_trace(mVcdFile, ps2ipFifo_V_last_V_dout, "ps2ipFifo_V_last_V_dout");
    sc_trace(mVcdFile, ps2ipFifo_V_last_V_empty_n, "ps2ipFifo_V_last_V_empty_n");
    sc_trace(mVcdFile, rule1cnt_V_buf_c31_full_n, "rule1cnt_V_buf_c31_full_n");
    sc_trace(mVcdFile, rule1cnt_V_buf_c31_dout, "rule1cnt_V_buf_c31_dout");
    sc_trace(mVcdFile, rule1cnt_V_buf_c31_empty_n, "rule1cnt_V_buf_c31_empty_n");
    sc_trace(mVcdFile, rule2cnt_V_buf_c32_full_n, "rule2cnt_V_buf_c32_full_n");
    sc_trace(mVcdFile, rule2cnt_V_buf_c32_dout, "rule2cnt_V_buf_c32_dout");
    sc_trace(mVcdFile, rule2cnt_V_buf_c32_empty_n, "rule2cnt_V_buf_c32_empty_n");
    sc_trace(mVcdFile, rule3cnt_V_buf_c33_full_n, "rule3cnt_V_buf_c33_full_n");
    sc_trace(mVcdFile, rule3cnt_V_buf_c33_dout, "rule3cnt_V_buf_c33_dout");
    sc_trace(mVcdFile, rule3cnt_V_buf_c33_empty_n, "rule3cnt_V_buf_c33_empty_n");
    sc_trace(mVcdFile, ip2psFifo_V_data_V_full_n, "ip2psFifo_V_data_V_full_n");
    sc_trace(mVcdFile, ip2psFifo_V_data_V_dout, "ip2psFifo_V_data_V_dout");
    sc_trace(mVcdFile, ip2psFifo_V_data_V_empty_n, "ip2psFifo_V_data_V_empty_n");
    sc_trace(mVcdFile, ip2psFifo_V_strb_V_full_n, "ip2psFifo_V_strb_V_full_n");
    sc_trace(mVcdFile, ip2psFifo_V_strb_V_dout, "ip2psFifo_V_strb_V_dout");
    sc_trace(mVcdFile, ip2psFifo_V_strb_V_empty_n, "ip2psFifo_V_strb_V_empty_n");
    sc_trace(mVcdFile, ip2psFifo_V_last_V_full_n, "ip2psFifo_V_last_V_full_n");
    sc_trace(mVcdFile, ip2psFifo_V_last_V_dout, "ip2psFifo_V_last_V_dout");
    sc_trace(mVcdFile, ip2psFifo_V_last_V_empty_n, "ip2psFifo_V_last_V_empty_n");
    sc_trace(mVcdFile, start_for_my_ip_hls_entry90_U0_din, "start_for_my_ip_hls_entry90_U0_din");
    sc_trace(mVcdFile, start_for_my_ip_hls_entry90_U0_full_n, "start_for_my_ip_hls_entry90_U0_full_n");
    sc_trace(mVcdFile, start_for_my_ip_hls_entry90_U0_dout, "start_for_my_ip_hls_entry90_U0_dout");
    sc_trace(mVcdFile, start_for_my_ip_hls_entry90_U0_empty_n, "start_for_my_ip_hls_entry90_U0_empty_n");
    sc_trace(mVcdFile, start_for_Block_codeRepl6_proc_U0_din, "start_for_Block_codeRepl6_proc_U0_din");
    sc_trace(mVcdFile, start_for_Block_codeRepl6_proc_U0_full_n, "start_for_Block_codeRepl6_proc_U0_full_n");
    sc_trace(mVcdFile, start_for_Block_codeRepl6_proc_U0_dout, "start_for_Block_codeRepl6_proc_U0_dout");
    sc_trace(mVcdFile, start_for_Block_codeRepl6_proc_U0_empty_n, "start_for_Block_codeRepl6_proc_U0_empty_n");
    sc_trace(mVcdFile, start_for_okanonas82_U0_din, "start_for_okanonas82_U0_din");
    sc_trace(mVcdFile, start_for_okanonas82_U0_full_n, "start_for_okanonas82_U0_full_n");
    sc_trace(mVcdFile, start_for_okanonas82_U0_dout, "start_for_okanonas82_U0_dout");
    sc_trace(mVcdFile, start_for_okanonas82_U0_empty_n, "start_for_okanonas82_U0_empty_n");
    sc_trace(mVcdFile, start_for_okanonas83_U0_din, "start_for_okanonas83_U0_din");
    sc_trace(mVcdFile, start_for_okanonas83_U0_full_n, "start_for_okanonas83_U0_full_n");
    sc_trace(mVcdFile, start_for_okanonas83_U0_dout, "start_for_okanonas83_U0_dout");
    sc_trace(mVcdFile, start_for_okanonas83_U0_empty_n, "start_for_okanonas83_U0_empty_n");
    sc_trace(mVcdFile, start_for_okanonas_U0_din, "start_for_okanonas_U0_din");
    sc_trace(mVcdFile, start_for_okanonas_U0_full_n, "start_for_okanonas_U0_full_n");
    sc_trace(mVcdFile, start_for_okanonas_U0_dout, "start_for_okanonas_U0_dout");
    sc_trace(mVcdFile, start_for_okanonas_U0_empty_n, "start_for_okanonas_U0_empty_n");
    sc_trace(mVcdFile, Block_codeRepl6_proc_U0_start_full_n, "Block_codeRepl6_proc_U0_start_full_n");
    sc_trace(mVcdFile, Block_codeRepl6_proc_U0_start_write, "Block_codeRepl6_proc_U0_start_write");
    sc_trace(mVcdFile, okanonas82_U0_start_full_n, "okanonas82_U0_start_full_n");
    sc_trace(mVcdFile, okanonas82_U0_start_write, "okanonas82_U0_start_write");
    sc_trace(mVcdFile, okanonas83_U0_start_full_n, "okanonas83_U0_start_full_n");
    sc_trace(mVcdFile, okanonas83_U0_start_write, "okanonas83_U0_start_write");
    sc_trace(mVcdFile, okanonas_U0_start_full_n, "okanonas_U0_start_full_n");
    sc_trace(mVcdFile, okanonas_U0_start_write, "okanonas_U0_start_write");
    sc_trace(mVcdFile, ps2ip_fifo_U0_start_full_n, "ps2ip_fifo_U0_start_full_n");
    sc_trace(mVcdFile, ps2ip_fifo_U0_start_write, "ps2ip_fifo_U0_start_write");
    sc_trace(mVcdFile, start_for_okanonas284_U0_din, "start_for_okanonas284_U0_din");
    sc_trace(mVcdFile, start_for_okanonas284_U0_full_n, "start_for_okanonas284_U0_full_n");
    sc_trace(mVcdFile, start_for_okanonas284_U0_dout, "start_for_okanonas284_U0_dout");
    sc_trace(mVcdFile, start_for_okanonas284_U0_empty_n, "start_for_okanonas284_U0_empty_n");
    sc_trace(mVcdFile, start_for_okanonas285_U0_din, "start_for_okanonas285_U0_din");
    sc_trace(mVcdFile, start_for_okanonas285_U0_full_n, "start_for_okanonas285_U0_full_n");
    sc_trace(mVcdFile, start_for_okanonas285_U0_dout, "start_for_okanonas285_U0_dout");
    sc_trace(mVcdFile, start_for_okanonas285_U0_empty_n, "start_for_okanonas285_U0_empty_n");
    sc_trace(mVcdFile, start_for_okanonas2_U0_din, "start_for_okanonas2_U0_din");
    sc_trace(mVcdFile, start_for_okanonas2_U0_full_n, "start_for_okanonas2_U0_full_n");
    sc_trace(mVcdFile, start_for_okanonas2_U0_dout, "start_for_okanonas2_U0_dout");
    sc_trace(mVcdFile, start_for_okanonas2_U0_empty_n, "start_for_okanonas2_U0_empty_n");
    sc_trace(mVcdFile, start_for_ip2ps_fifo_U0_din, "start_for_ip2ps_fifo_U0_din");
    sc_trace(mVcdFile, start_for_ip2ps_fifo_U0_full_n, "start_for_ip2ps_fifo_U0_full_n");
    sc_trace(mVcdFile, start_for_ip2ps_fifo_U0_dout, "start_for_ip2ps_fifo_U0_dout");
    sc_trace(mVcdFile, start_for_ip2ps_fifo_U0_empty_n, "start_for_ip2ps_fifo_U0_empty_n");
    sc_trace(mVcdFile, okanonas284_U0_start_full_n, "okanonas284_U0_start_full_n");
    sc_trace(mVcdFile, okanonas284_U0_start_write, "okanonas284_U0_start_write");
    sc_trace(mVcdFile, okanonas285_U0_start_full_n, "okanonas285_U0_start_full_n");
    sc_trace(mVcdFile, okanonas285_U0_start_write, "okanonas285_U0_start_write");
    sc_trace(mVcdFile, okanonas2_U0_start_full_n, "okanonas2_U0_start_full_n");
    sc_trace(mVcdFile, okanonas2_U0_start_write, "okanonas2_U0_start_write");
    sc_trace(mVcdFile, ip2ps_fifo_U0_start_full_n, "ip2ps_fifo_U0_start_full_n");
    sc_trace(mVcdFile, ip2ps_fifo_U0_start_write, "ip2ps_fifo_U0_start_write");
#endif

    }
    mHdltvinHandle.open("my_ip_hls.hdltvin.dat");
    mHdltvoutHandle.open("my_ip_hls.hdltvout.dat");
}

my_ip_hls::~my_ip_hls() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete my_ip_hls_ziskasrules_s_axi_U;
    delete my_ip_hls_entry3_U0;
    delete my_ip_hls_entry90_U0;
    delete Block_codeRepl6_proc_U0;
    delete okanonas82_U0;
    delete okanonas83_U0;
    delete okanonas_U0;
    delete ps2ip_fifo_U0;
    delete core_U0;
    delete okanonas284_U0;
    delete okanonas285_U0;
    delete okanonas2_U0;
    delete ip2ps_fifo_U0;
    delete rule1_V_c1_U;
    delete rule2_V_c2_U;
    delete rule3_V_c3_U;
    delete rule1cnt_V_c4_U;
    delete rule2cnt_V_c5_U;
    delete rule3cnt_V_c6_U;
    delete rule1_V_c_U;
    delete rule2_V_c_U;
    delete rule3_V_c_U;
    delete rule1cnt_V_c_U;
    delete rule2cnt_V_c_U;
    delete rule3cnt_V_c_U;
    delete rule3cnt_V_buf_c_U;
    delete rule2cnt_V_buf_c_U;
    delete rule1cnt_V_buf_c_U;
    delete regrule1_V_channel_U;
    delete regrule2_V_channel_U;
    delete regrule3_V_channel_U;
    delete ps2ipFifo_V_data_V_U;
    delete ps2ipFifo_V_strb_V_U;
    delete ps2ipFifo_V_last_V_U;
    delete rule1cnt_V_buf_c31_U;
    delete rule2cnt_V_buf_c32_U;
    delete rule3cnt_V_buf_c33_U;
    delete ip2psFifo_V_data_V_U;
    delete ip2psFifo_V_strb_V_U;
    delete ip2psFifo_V_last_V_U;
    delete start_for_my_ip_hbkb_U;
    delete start_for_Block_ccud_U;
    delete start_for_okanonadEe_U;
    delete start_for_okanonaeOg_U;
    delete start_for_okanonafYi_U;
    delete start_for_okanonag8j_U;
    delete start_for_okanonahbi_U;
    delete start_for_okanonaibs_U;
    delete start_for_ip2ps_fjbC_U;
}

void my_ip_hls::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void my_ip_hls::thread_Block_codeRepl6_proc_U0_ap_continue() {
    Block_codeRepl6_proc_U0_ap_continue = ap_const_logic_1;
}

void my_ip_hls::thread_Block_codeRepl6_proc_U0_ap_start() {
    Block_codeRepl6_proc_U0_ap_start = start_for_Block_codeRepl6_proc_U0_empty_n.read();
}

void my_ip_hls::thread_Block_codeRepl6_proc_U0_start_full_n() {
    Block_codeRepl6_proc_U0_start_full_n = ap_const_logic_1;
}

void my_ip_hls::thread_Block_codeRepl6_proc_U0_start_write() {
    Block_codeRepl6_proc_U0_start_write = ap_const_logic_0;
}

void my_ip_hls::thread_ap_channel_done_regrule1_V_channel() {
    ap_channel_done_regrule1_V_channel = okanonas82_U0_ap_done.read();
}

void my_ip_hls::thread_ap_channel_done_regrule2_V_channel() {
    ap_channel_done_regrule2_V_channel = okanonas83_U0_ap_done.read();
}

void my_ip_hls::thread_ap_channel_done_regrule3_V_channel() {
    ap_channel_done_regrule3_V_channel = okanonas_U0_ap_done.read();
}

void my_ip_hls::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void my_ip_hls::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_0;
}

void my_ip_hls::thread_core_U0_ap_continue() {
    core_U0_ap_continue = ap_const_logic_1;
}

void my_ip_hls::thread_core_U0_ap_start() {
    core_U0_ap_start = (regrule1_V_channel_empty_n.read() & regrule2_V_channel_empty_n.read() & regrule3_V_channel_empty_n.read());
}

void my_ip_hls::thread_core_U0_start_full_n() {
    core_U0_start_full_n = (start_for_okanonas284_U0_full_n.read() & start_for_okanonas285_U0_full_n.read() & start_for_okanonas2_U0_full_n.read() & start_for_ip2ps_fifo_U0_full_n.read());
}

void my_ip_hls::thread_ip2ps_fifo_U0_ap_continue() {
    ip2ps_fifo_U0_ap_continue = ap_const_logic_1;
}

void my_ip_hls::thread_ip2ps_fifo_U0_ap_start() {
    ip2ps_fifo_U0_ap_start = start_for_ip2ps_fifo_U0_empty_n.read();
}

void my_ip_hls::thread_ip2ps_fifo_U0_start_full_n() {
    ip2ps_fifo_U0_start_full_n = ap_const_logic_1;
}

void my_ip_hls::thread_ip2ps_fifo_U0_start_write() {
    ip2ps_fifo_U0_start_write = ap_const_logic_0;
}

void my_ip_hls::thread_masterOut_TDATA() {
    masterOut_TDATA = ip2ps_fifo_U0_masterOut_TDATA.read();
}

void my_ip_hls::thread_masterOut_TLAST() {
    masterOut_TLAST = ip2ps_fifo_U0_masterOut_TLAST.read();
}

void my_ip_hls::thread_masterOut_TSTRB() {
    masterOut_TSTRB = ip2ps_fifo_U0_masterOut_TSTRB.read();
}

void my_ip_hls::thread_masterOut_TVALID() {
    masterOut_TVALID = ip2ps_fifo_U0_masterOut_TVALID.read();
}

void my_ip_hls::thread_my_ip_hls_entry3_U0_ap_continue() {
    my_ip_hls_entry3_U0_ap_continue = ap_const_logic_1;
}

void my_ip_hls::thread_my_ip_hls_entry3_U0_ap_start() {
    my_ip_hls_entry3_U0_ap_start = ap_const_logic_1;
}

void my_ip_hls::thread_my_ip_hls_entry90_U0_ap_continue() {
    my_ip_hls_entry90_U0_ap_continue = ap_const_logic_1;
}

void my_ip_hls::thread_my_ip_hls_entry90_U0_ap_start() {
    my_ip_hls_entry90_U0_ap_start = start_for_my_ip_hls_entry90_U0_empty_n.read();
}

void my_ip_hls::thread_my_ip_hls_entry90_U0_start_full_n() {
    my_ip_hls_entry90_U0_start_full_n = (start_for_Block_codeRepl6_proc_U0_full_n.read() & start_for_okanonas82_U0_full_n.read() & start_for_okanonas83_U0_full_n.read() & start_for_okanonas_U0_full_n.read());
}

void my_ip_hls::thread_okanonas284_U0_ap_continue() {
    okanonas284_U0_ap_continue = ap_const_logic_1;
}

void my_ip_hls::thread_okanonas284_U0_ap_start() {
    okanonas284_U0_ap_start = start_for_okanonas284_U0_empty_n.read();
}

void my_ip_hls::thread_okanonas284_U0_start_full_n() {
    okanonas284_U0_start_full_n = ap_const_logic_1;
}

void my_ip_hls::thread_okanonas284_U0_start_write() {
    okanonas284_U0_start_write = ap_const_logic_0;
}

void my_ip_hls::thread_okanonas285_U0_ap_continue() {
    okanonas285_U0_ap_continue = ap_const_logic_1;
}

void my_ip_hls::thread_okanonas285_U0_ap_start() {
    okanonas285_U0_ap_start = start_for_okanonas285_U0_empty_n.read();
}

void my_ip_hls::thread_okanonas285_U0_start_full_n() {
    okanonas285_U0_start_full_n = ap_const_logic_1;
}

void my_ip_hls::thread_okanonas285_U0_start_write() {
    okanonas285_U0_start_write = ap_const_logic_0;
}

void my_ip_hls::thread_okanonas2_U0_ap_continue() {
    okanonas2_U0_ap_continue = ap_const_logic_1;
}

void my_ip_hls::thread_okanonas2_U0_ap_start() {
    okanonas2_U0_ap_start = start_for_okanonas2_U0_empty_n.read();
}

void my_ip_hls::thread_okanonas2_U0_start_full_n() {
    okanonas2_U0_start_full_n = ap_const_logic_1;
}

void my_ip_hls::thread_okanonas2_U0_start_write() {
    okanonas2_U0_start_write = ap_const_logic_0;
}

void my_ip_hls::thread_okanonas82_U0_ap_continue() {
    okanonas82_U0_ap_continue = regrule1_V_channel_full_n.read();
}

void my_ip_hls::thread_okanonas82_U0_ap_start() {
    okanonas82_U0_ap_start = start_for_okanonas82_U0_empty_n.read();
}

void my_ip_hls::thread_okanonas82_U0_start_full_n() {
    okanonas82_U0_start_full_n = ap_const_logic_1;
}

void my_ip_hls::thread_okanonas82_U0_start_write() {
    okanonas82_U0_start_write = ap_const_logic_0;
}

void my_ip_hls::thread_okanonas83_U0_ap_continue() {
    okanonas83_U0_ap_continue = regrule2_V_channel_full_n.read();
}

void my_ip_hls::thread_okanonas83_U0_ap_start() {
    okanonas83_U0_ap_start = start_for_okanonas83_U0_empty_n.read();
}

void my_ip_hls::thread_okanonas83_U0_start_full_n() {
    okanonas83_U0_start_full_n = ap_const_logic_1;
}

void my_ip_hls::thread_okanonas83_U0_start_write() {
    okanonas83_U0_start_write = ap_const_logic_0;
}

void my_ip_hls::thread_okanonas_U0_ap_continue() {
    okanonas_U0_ap_continue = regrule3_V_channel_full_n.read();
}

void my_ip_hls::thread_okanonas_U0_ap_start() {
    okanonas_U0_ap_start = start_for_okanonas_U0_empty_n.read();
}

void my_ip_hls::thread_okanonas_U0_start_full_n() {
    okanonas_U0_start_full_n = ap_const_logic_1;
}

void my_ip_hls::thread_okanonas_U0_start_write() {
    okanonas_U0_start_write = ap_const_logic_0;
}

void my_ip_hls::thread_ps2ip_fifo_U0_ap_continue() {
    ps2ip_fifo_U0_ap_continue = ap_const_logic_1;
}

void my_ip_hls::thread_ps2ip_fifo_U0_ap_start() {
    ps2ip_fifo_U0_ap_start = ap_const_logic_1;
}

void my_ip_hls::thread_ps2ip_fifo_U0_start_full_n() {
    ps2ip_fifo_U0_start_full_n = ap_const_logic_1;
}

void my_ip_hls::thread_ps2ip_fifo_U0_start_write() {
    ps2ip_fifo_U0_start_write = ap_const_logic_0;
}

void my_ip_hls::thread_slaveIn_TREADY() {
    slaveIn_TREADY = ps2ip_fifo_U0_slaveIn_TREADY.read();
}

void my_ip_hls::thread_start_for_Block_codeRepl6_proc_U0_din() {
    start_for_Block_codeRepl6_proc_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void my_ip_hls::thread_start_for_ip2ps_fifo_U0_din() {
    start_for_ip2ps_fifo_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void my_ip_hls::thread_start_for_my_ip_hls_entry90_U0_din() {
    start_for_my_ip_hls_entry90_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void my_ip_hls::thread_start_for_okanonas284_U0_din() {
    start_for_okanonas284_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void my_ip_hls::thread_start_for_okanonas285_U0_din() {
    start_for_okanonas285_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void my_ip_hls::thread_start_for_okanonas2_U0_din() {
    start_for_okanonas2_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void my_ip_hls::thread_start_for_okanonas82_U0_din() {
    start_for_okanonas82_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void my_ip_hls::thread_start_for_okanonas83_U0_din() {
    start_for_okanonas83_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void my_ip_hls::thread_start_for_okanonas_U0_din() {
    start_for_okanonas_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void my_ip_hls::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"s_axi_ziskasrules_AWVALID\" :  \"" << s_axi_ziskasrules_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_ziskasrules_AWREADY\" :  \"" << s_axi_ziskasrules_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_ziskasrules_AWADDR\" :  \"" << s_axi_ziskasrules_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_ziskasrules_WVALID\" :  \"" << s_axi_ziskasrules_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_ziskasrules_WREADY\" :  \"" << s_axi_ziskasrules_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_ziskasrules_WDATA\" :  \"" << s_axi_ziskasrules_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_ziskasrules_WSTRB\" :  \"" << s_axi_ziskasrules_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_ziskasrules_ARVALID\" :  \"" << s_axi_ziskasrules_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_ziskasrules_ARREADY\" :  \"" << s_axi_ziskasrules_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_ziskasrules_ARADDR\" :  \"" << s_axi_ziskasrules_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_ziskasrules_RVALID\" :  \"" << s_axi_ziskasrules_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_ziskasrules_RREADY\" :  \"" << s_axi_ziskasrules_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_ziskasrules_RDATA\" :  \"" << s_axi_ziskasrules_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_ziskasrules_RRESP\" :  \"" << s_axi_ziskasrules_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_ziskasrules_BVALID\" :  \"" << s_axi_ziskasrules_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_ziskasrules_BREADY\" :  \"" << s_axi_ziskasrules_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_ziskasrules_BRESP\" :  \"" << s_axi_ziskasrules_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"slaveIn_TDATA\" :  \"" << slaveIn_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"slaveIn_TSTRB\" :  \"" << slaveIn_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"slaveIn_TLAST\" :  \"" << slaveIn_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"masterOut_TDATA\" :  \"" << masterOut_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"masterOut_TSTRB\" :  \"" << masterOut_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"masterOut_TLAST\" :  \"" << masterOut_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"slaveIn_TVALID\" :  \"" << slaveIn_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"slaveIn_TREADY\" :  \"" << slaveIn_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"masterOut_TVALID\" :  \"" << masterOut_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"masterOut_TREADY\" :  \"" << masterOut_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

