// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _okanonas2_HH_
#define _okanonas2_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct okanonas2 : public sc_module {
    // Port declarations 10
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > rule3cnt_V_buf_dout;
    sc_in< sc_logic > rule3cnt_V_buf_empty_n;
    sc_out< sc_logic > rule3cnt_V_buf_read;


    // Module declarations
    okanonas2(sc_module_name name);
    SC_HAS_PROCESS(okanonas2);

    ~okanonas2();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > num3_V;
    sc_signal< sc_logic > rule3cnt_V_buf_blk_n;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<32> > exodos2_V_assign_i_i_fu_28_p2;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_fsm_state1;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_block_state1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_exodos2_V_assign_i_i_fu_28_p2();
    void thread_rule3cnt_V_buf_blk_n();
    void thread_rule3cnt_V_buf_read();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
