// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="my_ip_hls,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z045ffg900-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.950000,HLS_SYN_LAT=7,HLS_SYN_TPT=1,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=1019,HLS_SYN_LUT=2829}" *)

module my_ip_hls (
        s_axi_ziskasrules_AWVALID,
        s_axi_ziskasrules_AWREADY,
        s_axi_ziskasrules_AWADDR,
        s_axi_ziskasrules_WVALID,
        s_axi_ziskasrules_WREADY,
        s_axi_ziskasrules_WDATA,
        s_axi_ziskasrules_WSTRB,
        s_axi_ziskasrules_ARVALID,
        s_axi_ziskasrules_ARREADY,
        s_axi_ziskasrules_ARADDR,
        s_axi_ziskasrules_RVALID,
        s_axi_ziskasrules_RREADY,
        s_axi_ziskasrules_RDATA,
        s_axi_ziskasrules_RRESP,
        s_axi_ziskasrules_BVALID,
        s_axi_ziskasrules_BREADY,
        s_axi_ziskasrules_BRESP,
        ap_clk,
        ap_rst_n,
        slaveIn_TDATA,
        slaveIn_TSTRB,
        slaveIn_TLAST,
        masterOut_TDATA,
        masterOut_TSTRB,
        masterOut_TLAST,
        slaveIn_TVALID,
        slaveIn_TREADY,
        masterOut_TVALID,
        masterOut_TREADY
);

parameter    C_S_AXI_ZISKASRULES_DATA_WIDTH = 32;
parameter    C_S_AXI_ZISKASRULES_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;

parameter C_S_AXI_ZISKASRULES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_ziskasrules_AWVALID;
output   s_axi_ziskasrules_AWREADY;
input  [C_S_AXI_ZISKASRULES_ADDR_WIDTH - 1:0] s_axi_ziskasrules_AWADDR;
input   s_axi_ziskasrules_WVALID;
output   s_axi_ziskasrules_WREADY;
input  [C_S_AXI_ZISKASRULES_DATA_WIDTH - 1:0] s_axi_ziskasrules_WDATA;
input  [C_S_AXI_ZISKASRULES_WSTRB_WIDTH - 1:0] s_axi_ziskasrules_WSTRB;
input   s_axi_ziskasrules_ARVALID;
output   s_axi_ziskasrules_ARREADY;
input  [C_S_AXI_ZISKASRULES_ADDR_WIDTH - 1:0] s_axi_ziskasrules_ARADDR;
output   s_axi_ziskasrules_RVALID;
input   s_axi_ziskasrules_RREADY;
output  [C_S_AXI_ZISKASRULES_DATA_WIDTH - 1:0] s_axi_ziskasrules_RDATA;
output  [1:0] s_axi_ziskasrules_RRESP;
output   s_axi_ziskasrules_BVALID;
input   s_axi_ziskasrules_BREADY;
output  [1:0] s_axi_ziskasrules_BRESP;
input   ap_clk;
input   ap_rst_n;
input  [31:0] slaveIn_TDATA;
input  [3:0] slaveIn_TSTRB;
input  [0:0] slaveIn_TLAST;
output  [31:0] masterOut_TDATA;
output  [3:0] masterOut_TSTRB;
output  [0:0] masterOut_TLAST;
input   slaveIn_TVALID;
output   slaveIn_TREADY;
output   masterOut_TVALID;
input   masterOut_TREADY;

reg    ap_rst_n_inv;
wire   [31:0] rule1_V;
wire   [31:0] rule2_V;
wire   [31:0] rule3_V;
wire   [31:0] rule1cnt_V;
wire   [31:0] rule2cnt_V;
wire   [31:0] rule3cnt_V;
wire    my_ip_hls_entry3_U0_ap_start;
wire    my_ip_hls_entry3_U0_ap_done;
wire    my_ip_hls_entry3_U0_ap_continue;
wire    my_ip_hls_entry3_U0_ap_idle;
wire    my_ip_hls_entry3_U0_ap_ready;
wire    my_ip_hls_entry3_U0_start_out;
wire    my_ip_hls_entry3_U0_start_write;
wire   [31:0] my_ip_hls_entry3_U0_rule1_V_out_din;
wire    my_ip_hls_entry3_U0_rule1_V_out_write;
wire   [31:0] my_ip_hls_entry3_U0_rule2_V_out_din;
wire    my_ip_hls_entry3_U0_rule2_V_out_write;
wire   [31:0] my_ip_hls_entry3_U0_rule3_V_out_din;
wire    my_ip_hls_entry3_U0_rule3_V_out_write;
wire   [31:0] my_ip_hls_entry3_U0_rule1cnt_V_out_din;
wire    my_ip_hls_entry3_U0_rule1cnt_V_out_write;
wire   [31:0] my_ip_hls_entry3_U0_rule2cnt_V_out_din;
wire    my_ip_hls_entry3_U0_rule2cnt_V_out_write;
wire   [31:0] my_ip_hls_entry3_U0_rule3cnt_V_out_din;
wire    my_ip_hls_entry3_U0_rule3cnt_V_out_write;
wire    my_ip_hls_entry90_U0_ap_start;
wire    my_ip_hls_entry90_U0_start_full_n;
wire    my_ip_hls_entry90_U0_ap_done;
wire    my_ip_hls_entry90_U0_ap_continue;
wire    my_ip_hls_entry90_U0_ap_idle;
wire    my_ip_hls_entry90_U0_ap_ready;
wire    my_ip_hls_entry90_U0_start_out;
wire    my_ip_hls_entry90_U0_start_write;
wire    my_ip_hls_entry90_U0_rule1_V_read;
wire    my_ip_hls_entry90_U0_rule2_V_read;
wire    my_ip_hls_entry90_U0_rule3_V_read;
wire    my_ip_hls_entry90_U0_rule1cnt_V_read;
wire    my_ip_hls_entry90_U0_rule2cnt_V_read;
wire    my_ip_hls_entry90_U0_rule3cnt_V_read;
wire   [31:0] my_ip_hls_entry90_U0_rule1_V_out_din;
wire    my_ip_hls_entry90_U0_rule1_V_out_write;
wire   [31:0] my_ip_hls_entry90_U0_rule2_V_out_din;
wire    my_ip_hls_entry90_U0_rule2_V_out_write;
wire   [31:0] my_ip_hls_entry90_U0_rule3_V_out_din;
wire    my_ip_hls_entry90_U0_rule3_V_out_write;
wire   [31:0] my_ip_hls_entry90_U0_rule1cnt_V_out_din;
wire    my_ip_hls_entry90_U0_rule1cnt_V_out_write;
wire   [31:0] my_ip_hls_entry90_U0_rule2cnt_V_out_din;
wire    my_ip_hls_entry90_U0_rule2cnt_V_out_write;
wire   [31:0] my_ip_hls_entry90_U0_rule3cnt_V_out_din;
wire    my_ip_hls_entry90_U0_rule3cnt_V_out_write;
wire    Block_codeRepl6_proc_U0_ap_start;
wire    Block_codeRepl6_proc_U0_ap_done;
wire    Block_codeRepl6_proc_U0_ap_continue;
wire    Block_codeRepl6_proc_U0_ap_idle;
wire    Block_codeRepl6_proc_U0_ap_ready;
wire    Block_codeRepl6_proc_U0_rule3cnt_V_read;
wire    Block_codeRepl6_proc_U0_rule2cnt_V_read;
wire    Block_codeRepl6_proc_U0_rule1cnt_V_read;
wire   [31:0] Block_codeRepl6_proc_U0_rule3cnt_V_buf_out_din;
wire    Block_codeRepl6_proc_U0_rule3cnt_V_buf_out_write;
wire   [31:0] Block_codeRepl6_proc_U0_rule2cnt_V_buf_out_din;
wire    Block_codeRepl6_proc_U0_rule2cnt_V_buf_out_write;
wire   [31:0] Block_codeRepl6_proc_U0_rule1cnt_V_buf_out_din;
wire    Block_codeRepl6_proc_U0_rule1cnt_V_buf_out_write;
wire    okanonas82_U0_ap_start;
wire    okanonas82_U0_ap_done;
wire    okanonas82_U0_ap_continue;
wire    okanonas82_U0_ap_idle;
wire    okanonas82_U0_ap_ready;
wire    okanonas82_U0_rule_V_read;
wire   [31:0] okanonas82_U0_ap_return;
wire    ap_channel_done_regrule1_V_channel;
wire    regrule1_V_channel_full_n;
wire    okanonas83_U0_ap_start;
wire    okanonas83_U0_ap_done;
wire    okanonas83_U0_ap_continue;
wire    okanonas83_U0_ap_idle;
wire    okanonas83_U0_ap_ready;
wire    okanonas83_U0_rule_V_read;
wire   [31:0] okanonas83_U0_ap_return;
wire    ap_channel_done_regrule2_V_channel;
wire    regrule2_V_channel_full_n;
wire    okanonas_U0_ap_start;
wire    okanonas_U0_ap_done;
wire    okanonas_U0_ap_continue;
wire    okanonas_U0_ap_idle;
wire    okanonas_U0_ap_ready;
wire    okanonas_U0_rule_V_read;
wire   [31:0] okanonas_U0_ap_return;
wire    ap_channel_done_regrule3_V_channel;
wire    regrule3_V_channel_full_n;
wire    ps2ip_fifo_U0_ap_start;
wire    ps2ip_fifo_U0_ap_done;
wire    ps2ip_fifo_U0_ap_continue;
wire    ps2ip_fifo_U0_ap_idle;
wire    ps2ip_fifo_U0_ap_ready;
wire    ps2ip_fifo_U0_slaveIn_TREADY;
wire   [31:0] ps2ip_fifo_U0_ps2ipFifo_V_data_V_din;
wire    ps2ip_fifo_U0_ps2ipFifo_V_data_V_write;
wire   [3:0] ps2ip_fifo_U0_ps2ipFifo_V_strb_V_din;
wire    ps2ip_fifo_U0_ps2ipFifo_V_strb_V_write;
wire   [0:0] ps2ip_fifo_U0_ps2ipFifo_V_last_V_din;
wire    ps2ip_fifo_U0_ps2ipFifo_V_last_V_write;
wire    core_U0_ap_start;
wire    core_U0_start_full_n;
wire    core_U0_ap_done;
wire    core_U0_ap_continue;
wire    core_U0_ap_idle;
wire    core_U0_ap_ready;
wire    core_U0_rule1cnt_V_buf_read;
wire    core_U0_rule2cnt_V_buf_read;
wire    core_U0_rule3cnt_V_buf_read;
wire   [31:0] core_U0_rule1cnt_V_buf_out_din;
wire    core_U0_rule1cnt_V_buf_out_write;
wire   [31:0] core_U0_rule2cnt_V_buf_out_din;
wire    core_U0_rule2cnt_V_buf_out_write;
wire   [31:0] core_U0_rule3cnt_V_buf_out_din;
wire    core_U0_rule3cnt_V_buf_out_write;
wire    core_U0_start_out;
wire    core_U0_start_write;
wire    core_U0_ps2ipFifo_V_data_V_read;
wire    core_U0_ps2ipFifo_V_strb_V_read;
wire    core_U0_ps2ipFifo_V_last_V_read;
wire   [31:0] core_U0_ip2psFifo_V_data_V_din;
wire    core_U0_ip2psFifo_V_data_V_write;
wire   [3:0] core_U0_ip2psFifo_V_strb_V_din;
wire    core_U0_ip2psFifo_V_strb_V_write;
wire   [0:0] core_U0_ip2psFifo_V_last_V_din;
wire    core_U0_ip2psFifo_V_last_V_write;
wire    okanonas284_U0_ap_start;
wire    okanonas284_U0_ap_done;
wire    okanonas284_U0_ap_continue;
wire    okanonas284_U0_ap_idle;
wire    okanonas284_U0_ap_ready;
wire    okanonas284_U0_rule1cnt_V_buf_read;
wire    okanonas285_U0_ap_start;
wire    okanonas285_U0_ap_done;
wire    okanonas285_U0_ap_continue;
wire    okanonas285_U0_ap_idle;
wire    okanonas285_U0_ap_ready;
wire    okanonas285_U0_rule2cnt_V_buf_read;
wire    okanonas2_U0_ap_start;
wire    okanonas2_U0_ap_done;
wire    okanonas2_U0_ap_continue;
wire    okanonas2_U0_ap_idle;
wire    okanonas2_U0_ap_ready;
wire    okanonas2_U0_rule3cnt_V_buf_read;
wire    ip2ps_fifo_U0_ap_start;
wire    ip2ps_fifo_U0_ap_done;
wire    ip2ps_fifo_U0_ap_continue;
wire    ip2ps_fifo_U0_ap_idle;
wire    ip2ps_fifo_U0_ap_ready;
wire   [31:0] ip2ps_fifo_U0_masterOut_TDATA;
wire    ip2ps_fifo_U0_masterOut_TVALID;
wire   [3:0] ip2ps_fifo_U0_masterOut_TSTRB;
wire   [0:0] ip2ps_fifo_U0_masterOut_TLAST;
wire    ip2ps_fifo_U0_ip2psFifo_V_data_V_read;
wire    ip2ps_fifo_U0_ip2psFifo_V_strb_V_read;
wire    ip2ps_fifo_U0_ip2psFifo_V_last_V_read;
wire    ap_sync_continue;
wire    rule1_V_c1_full_n;
wire   [31:0] rule1_V_c1_dout;
wire    rule1_V_c1_empty_n;
wire    rule2_V_c2_full_n;
wire   [31:0] rule2_V_c2_dout;
wire    rule2_V_c2_empty_n;
wire    rule3_V_c3_full_n;
wire   [31:0] rule3_V_c3_dout;
wire    rule3_V_c3_empty_n;
wire    rule1cnt_V_c4_full_n;
wire   [31:0] rule1cnt_V_c4_dout;
wire    rule1cnt_V_c4_empty_n;
wire    rule2cnt_V_c5_full_n;
wire   [31:0] rule2cnt_V_c5_dout;
wire    rule2cnt_V_c5_empty_n;
wire    rule3cnt_V_c6_full_n;
wire   [31:0] rule3cnt_V_c6_dout;
wire    rule3cnt_V_c6_empty_n;
wire    rule1_V_c_full_n;
wire   [31:0] rule1_V_c_dout;
wire    rule1_V_c_empty_n;
wire    rule2_V_c_full_n;
wire   [31:0] rule2_V_c_dout;
wire    rule2_V_c_empty_n;
wire    rule3_V_c_full_n;
wire   [31:0] rule3_V_c_dout;
wire    rule3_V_c_empty_n;
wire    rule1cnt_V_c_full_n;
wire   [31:0] rule1cnt_V_c_dout;
wire    rule1cnt_V_c_empty_n;
wire    rule2cnt_V_c_full_n;
wire   [31:0] rule2cnt_V_c_dout;
wire    rule2cnt_V_c_empty_n;
wire    rule3cnt_V_c_full_n;
wire   [31:0] rule3cnt_V_c_dout;
wire    rule3cnt_V_c_empty_n;
wire    rule3cnt_V_buf_c_full_n;
wire   [31:0] rule3cnt_V_buf_c_dout;
wire    rule3cnt_V_buf_c_empty_n;
wire    rule2cnt_V_buf_c_full_n;
wire   [31:0] rule2cnt_V_buf_c_dout;
wire    rule2cnt_V_buf_c_empty_n;
wire    rule1cnt_V_buf_c_full_n;
wire   [31:0] rule1cnt_V_buf_c_dout;
wire    rule1cnt_V_buf_c_empty_n;
wire   [31:0] regrule1_V_channel_dout;
wire    regrule1_V_channel_empty_n;
wire   [31:0] regrule2_V_channel_dout;
wire    regrule2_V_channel_empty_n;
wire   [31:0] regrule3_V_channel_dout;
wire    regrule3_V_channel_empty_n;
wire    ps2ipFifo_V_data_V_full_n;
wire   [31:0] ps2ipFifo_V_data_V_dout;
wire    ps2ipFifo_V_data_V_empty_n;
wire    ps2ipFifo_V_strb_V_full_n;
wire   [3:0] ps2ipFifo_V_strb_V_dout;
wire    ps2ipFifo_V_strb_V_empty_n;
wire    ps2ipFifo_V_last_V_full_n;
wire   [0:0] ps2ipFifo_V_last_V_dout;
wire    ps2ipFifo_V_last_V_empty_n;
wire    rule1cnt_V_buf_c31_full_n;
wire   [31:0] rule1cnt_V_buf_c31_dout;
wire    rule1cnt_V_buf_c31_empty_n;
wire    rule2cnt_V_buf_c32_full_n;
wire   [31:0] rule2cnt_V_buf_c32_dout;
wire    rule2cnt_V_buf_c32_empty_n;
wire    rule3cnt_V_buf_c33_full_n;
wire   [31:0] rule3cnt_V_buf_c33_dout;
wire    rule3cnt_V_buf_c33_empty_n;
wire    ip2psFifo_V_data_V_full_n;
wire   [31:0] ip2psFifo_V_data_V_dout;
wire    ip2psFifo_V_data_V_empty_n;
wire    ip2psFifo_V_strb_V_full_n;
wire   [3:0] ip2psFifo_V_strb_V_dout;
wire    ip2psFifo_V_strb_V_empty_n;
wire    ip2psFifo_V_last_V_full_n;
wire   [0:0] ip2psFifo_V_last_V_dout;
wire    ip2psFifo_V_last_V_empty_n;
wire   [0:0] start_for_my_ip_hls_entry90_U0_din;
wire    start_for_my_ip_hls_entry90_U0_full_n;
wire   [0:0] start_for_my_ip_hls_entry90_U0_dout;
wire    start_for_my_ip_hls_entry90_U0_empty_n;
wire   [0:0] start_for_Block_codeRepl6_proc_U0_din;
wire    start_for_Block_codeRepl6_proc_U0_full_n;
wire   [0:0] start_for_Block_codeRepl6_proc_U0_dout;
wire    start_for_Block_codeRepl6_proc_U0_empty_n;
wire   [0:0] start_for_okanonas82_U0_din;
wire    start_for_okanonas82_U0_full_n;
wire   [0:0] start_for_okanonas82_U0_dout;
wire    start_for_okanonas82_U0_empty_n;
wire   [0:0] start_for_okanonas83_U0_din;
wire    start_for_okanonas83_U0_full_n;
wire   [0:0] start_for_okanonas83_U0_dout;
wire    start_for_okanonas83_U0_empty_n;
wire   [0:0] start_for_okanonas_U0_din;
wire    start_for_okanonas_U0_full_n;
wire   [0:0] start_for_okanonas_U0_dout;
wire    start_for_okanonas_U0_empty_n;
wire    Block_codeRepl6_proc_U0_start_full_n;
wire    Block_codeRepl6_proc_U0_start_write;
wire    okanonas82_U0_start_full_n;
wire    okanonas82_U0_start_write;
wire    okanonas83_U0_start_full_n;
wire    okanonas83_U0_start_write;
wire    okanonas_U0_start_full_n;
wire    okanonas_U0_start_write;
wire    ps2ip_fifo_U0_start_full_n;
wire    ps2ip_fifo_U0_start_write;
wire   [0:0] start_for_okanonas284_U0_din;
wire    start_for_okanonas284_U0_full_n;
wire   [0:0] start_for_okanonas284_U0_dout;
wire    start_for_okanonas284_U0_empty_n;
wire   [0:0] start_for_okanonas285_U0_din;
wire    start_for_okanonas285_U0_full_n;
wire   [0:0] start_for_okanonas285_U0_dout;
wire    start_for_okanonas285_U0_empty_n;
wire   [0:0] start_for_okanonas2_U0_din;
wire    start_for_okanonas2_U0_full_n;
wire   [0:0] start_for_okanonas2_U0_dout;
wire    start_for_okanonas2_U0_empty_n;
wire   [0:0] start_for_ip2ps_fifo_U0_din;
wire    start_for_ip2ps_fifo_U0_full_n;
wire   [0:0] start_for_ip2ps_fifo_U0_dout;
wire    start_for_ip2ps_fifo_U0_empty_n;
wire    okanonas284_U0_start_full_n;
wire    okanonas284_U0_start_write;
wire    okanonas285_U0_start_full_n;
wire    okanonas285_U0_start_write;
wire    okanonas2_U0_start_full_n;
wire    okanonas2_U0_start_write;
wire    ip2ps_fifo_U0_start_full_n;
wire    ip2ps_fifo_U0_start_write;

my_ip_hls_ziskasrules_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_ZISKASRULES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_ZISKASRULES_DATA_WIDTH ))
my_ip_hls_ziskasrules_s_axi_U(
    .AWVALID(s_axi_ziskasrules_AWVALID),
    .AWREADY(s_axi_ziskasrules_AWREADY),
    .AWADDR(s_axi_ziskasrules_AWADDR),
    .WVALID(s_axi_ziskasrules_WVALID),
    .WREADY(s_axi_ziskasrules_WREADY),
    .WDATA(s_axi_ziskasrules_WDATA),
    .WSTRB(s_axi_ziskasrules_WSTRB),
    .ARVALID(s_axi_ziskasrules_ARVALID),
    .ARREADY(s_axi_ziskasrules_ARREADY),
    .ARADDR(s_axi_ziskasrules_ARADDR),
    .RVALID(s_axi_ziskasrules_RVALID),
    .RREADY(s_axi_ziskasrules_RREADY),
    .RDATA(s_axi_ziskasrules_RDATA),
    .RRESP(s_axi_ziskasrules_RRESP),
    .BVALID(s_axi_ziskasrules_BVALID),
    .BREADY(s_axi_ziskasrules_BREADY),
    .BRESP(s_axi_ziskasrules_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .rule1_V(rule1_V),
    .rule2_V(rule2_V),
    .rule3_V(rule3_V),
    .rule1cnt_V(rule1cnt_V),
    .rule2cnt_V(rule2cnt_V),
    .rule3cnt_V(rule3cnt_V)
);

my_ip_hls_entry3 my_ip_hls_entry3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(my_ip_hls_entry3_U0_ap_start),
    .start_full_n(start_for_my_ip_hls_entry90_U0_full_n),
    .ap_done(my_ip_hls_entry3_U0_ap_done),
    .ap_continue(my_ip_hls_entry3_U0_ap_continue),
    .ap_idle(my_ip_hls_entry3_U0_ap_idle),
    .ap_ready(my_ip_hls_entry3_U0_ap_ready),
    .start_out(my_ip_hls_entry3_U0_start_out),
    .start_write(my_ip_hls_entry3_U0_start_write),
    .rule1_V(rule1_V),
    .rule2_V(rule2_V),
    .rule3_V(rule3_V),
    .rule1cnt_V(rule1cnt_V),
    .rule2cnt_V(rule2cnt_V),
    .rule3cnt_V(rule3cnt_V),
    .rule1_V_out_din(my_ip_hls_entry3_U0_rule1_V_out_din),
    .rule1_V_out_full_n(rule1_V_c1_full_n),
    .rule1_V_out_write(my_ip_hls_entry3_U0_rule1_V_out_write),
    .rule2_V_out_din(my_ip_hls_entry3_U0_rule2_V_out_din),
    .rule2_V_out_full_n(rule2_V_c2_full_n),
    .rule2_V_out_write(my_ip_hls_entry3_U0_rule2_V_out_write),
    .rule3_V_out_din(my_ip_hls_entry3_U0_rule3_V_out_din),
    .rule3_V_out_full_n(rule3_V_c3_full_n),
    .rule3_V_out_write(my_ip_hls_entry3_U0_rule3_V_out_write),
    .rule1cnt_V_out_din(my_ip_hls_entry3_U0_rule1cnt_V_out_din),
    .rule1cnt_V_out_full_n(rule1cnt_V_c4_full_n),
    .rule1cnt_V_out_write(my_ip_hls_entry3_U0_rule1cnt_V_out_write),
    .rule2cnt_V_out_din(my_ip_hls_entry3_U0_rule2cnt_V_out_din),
    .rule2cnt_V_out_full_n(rule2cnt_V_c5_full_n),
    .rule2cnt_V_out_write(my_ip_hls_entry3_U0_rule2cnt_V_out_write),
    .rule3cnt_V_out_din(my_ip_hls_entry3_U0_rule3cnt_V_out_din),
    .rule3cnt_V_out_full_n(rule3cnt_V_c6_full_n),
    .rule3cnt_V_out_write(my_ip_hls_entry3_U0_rule3cnt_V_out_write)
);

my_ip_hls_entry90 my_ip_hls_entry90_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(my_ip_hls_entry90_U0_ap_start),
    .start_full_n(my_ip_hls_entry90_U0_start_full_n),
    .ap_done(my_ip_hls_entry90_U0_ap_done),
    .ap_continue(my_ip_hls_entry90_U0_ap_continue),
    .ap_idle(my_ip_hls_entry90_U0_ap_idle),
    .ap_ready(my_ip_hls_entry90_U0_ap_ready),
    .start_out(my_ip_hls_entry90_U0_start_out),
    .start_write(my_ip_hls_entry90_U0_start_write),
    .rule1_V_dout(rule1_V_c1_dout),
    .rule1_V_empty_n(rule1_V_c1_empty_n),
    .rule1_V_read(my_ip_hls_entry90_U0_rule1_V_read),
    .rule2_V_dout(rule2_V_c2_dout),
    .rule2_V_empty_n(rule2_V_c2_empty_n),
    .rule2_V_read(my_ip_hls_entry90_U0_rule2_V_read),
    .rule3_V_dout(rule3_V_c3_dout),
    .rule3_V_empty_n(rule3_V_c3_empty_n),
    .rule3_V_read(my_ip_hls_entry90_U0_rule3_V_read),
    .rule1cnt_V_dout(rule1cnt_V_c4_dout),
    .rule1cnt_V_empty_n(rule1cnt_V_c4_empty_n),
    .rule1cnt_V_read(my_ip_hls_entry90_U0_rule1cnt_V_read),
    .rule2cnt_V_dout(rule2cnt_V_c5_dout),
    .rule2cnt_V_empty_n(rule2cnt_V_c5_empty_n),
    .rule2cnt_V_read(my_ip_hls_entry90_U0_rule2cnt_V_read),
    .rule3cnt_V_dout(rule3cnt_V_c6_dout),
    .rule3cnt_V_empty_n(rule3cnt_V_c6_empty_n),
    .rule3cnt_V_read(my_ip_hls_entry90_U0_rule3cnt_V_read),
    .rule1_V_out_din(my_ip_hls_entry90_U0_rule1_V_out_din),
    .rule1_V_out_full_n(rule1_V_c_full_n),
    .rule1_V_out_write(my_ip_hls_entry90_U0_rule1_V_out_write),
    .rule2_V_out_din(my_ip_hls_entry90_U0_rule2_V_out_din),
    .rule2_V_out_full_n(rule2_V_c_full_n),
    .rule2_V_out_write(my_ip_hls_entry90_U0_rule2_V_out_write),
    .rule3_V_out_din(my_ip_hls_entry90_U0_rule3_V_out_din),
    .rule3_V_out_full_n(rule3_V_c_full_n),
    .rule3_V_out_write(my_ip_hls_entry90_U0_rule3_V_out_write),
    .rule1cnt_V_out_din(my_ip_hls_entry90_U0_rule1cnt_V_out_din),
    .rule1cnt_V_out_full_n(rule1cnt_V_c_full_n),
    .rule1cnt_V_out_write(my_ip_hls_entry90_U0_rule1cnt_V_out_write),
    .rule2cnt_V_out_din(my_ip_hls_entry90_U0_rule2cnt_V_out_din),
    .rule2cnt_V_out_full_n(rule2cnt_V_c_full_n),
    .rule2cnt_V_out_write(my_ip_hls_entry90_U0_rule2cnt_V_out_write),
    .rule3cnt_V_out_din(my_ip_hls_entry90_U0_rule3cnt_V_out_din),
    .rule3cnt_V_out_full_n(rule3cnt_V_c_full_n),
    .rule3cnt_V_out_write(my_ip_hls_entry90_U0_rule3cnt_V_out_write)
);

Block_codeRepl6_proc Block_codeRepl6_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_codeRepl6_proc_U0_ap_start),
    .ap_done(Block_codeRepl6_proc_U0_ap_done),
    .ap_continue(Block_codeRepl6_proc_U0_ap_continue),
    .ap_idle(Block_codeRepl6_proc_U0_ap_idle),
    .ap_ready(Block_codeRepl6_proc_U0_ap_ready),
    .rule3cnt_V_dout(rule3cnt_V_c_dout),
    .rule3cnt_V_empty_n(rule3cnt_V_c_empty_n),
    .rule3cnt_V_read(Block_codeRepl6_proc_U0_rule3cnt_V_read),
    .rule2cnt_V_dout(rule2cnt_V_c_dout),
    .rule2cnt_V_empty_n(rule2cnt_V_c_empty_n),
    .rule2cnt_V_read(Block_codeRepl6_proc_U0_rule2cnt_V_read),
    .rule1cnt_V_dout(rule1cnt_V_c_dout),
    .rule1cnt_V_empty_n(rule1cnt_V_c_empty_n),
    .rule1cnt_V_read(Block_codeRepl6_proc_U0_rule1cnt_V_read),
    .rule3cnt_V_buf_out_din(Block_codeRepl6_proc_U0_rule3cnt_V_buf_out_din),
    .rule3cnt_V_buf_out_full_n(rule3cnt_V_buf_c_full_n),
    .rule3cnt_V_buf_out_write(Block_codeRepl6_proc_U0_rule3cnt_V_buf_out_write),
    .rule2cnt_V_buf_out_din(Block_codeRepl6_proc_U0_rule2cnt_V_buf_out_din),
    .rule2cnt_V_buf_out_full_n(rule2cnt_V_buf_c_full_n),
    .rule2cnt_V_buf_out_write(Block_codeRepl6_proc_U0_rule2cnt_V_buf_out_write),
    .rule1cnt_V_buf_out_din(Block_codeRepl6_proc_U0_rule1cnt_V_buf_out_din),
    .rule1cnt_V_buf_out_full_n(rule1cnt_V_buf_c_full_n),
    .rule1cnt_V_buf_out_write(Block_codeRepl6_proc_U0_rule1cnt_V_buf_out_write)
);

okanonas82 okanonas82_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(okanonas82_U0_ap_start),
    .ap_done(okanonas82_U0_ap_done),
    .ap_continue(okanonas82_U0_ap_continue),
    .ap_idle(okanonas82_U0_ap_idle),
    .ap_ready(okanonas82_U0_ap_ready),
    .rule_V_dout(rule1_V_c_dout),
    .rule_V_empty_n(rule1_V_c_empty_n),
    .rule_V_read(okanonas82_U0_rule_V_read),
    .ap_return(okanonas82_U0_ap_return)
);

okanonas83 okanonas83_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(okanonas83_U0_ap_start),
    .ap_done(okanonas83_U0_ap_done),
    .ap_continue(okanonas83_U0_ap_continue),
    .ap_idle(okanonas83_U0_ap_idle),
    .ap_ready(okanonas83_U0_ap_ready),
    .rule_V_dout(rule2_V_c_dout),
    .rule_V_empty_n(rule2_V_c_empty_n),
    .rule_V_read(okanonas83_U0_rule_V_read),
    .ap_return(okanonas83_U0_ap_return)
);

okanonas okanonas_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(okanonas_U0_ap_start),
    .ap_done(okanonas_U0_ap_done),
    .ap_continue(okanonas_U0_ap_continue),
    .ap_idle(okanonas_U0_ap_idle),
    .ap_ready(okanonas_U0_ap_ready),
    .rule_V_dout(rule3_V_c_dout),
    .rule_V_empty_n(rule3_V_c_empty_n),
    .rule_V_read(okanonas_U0_rule_V_read),
    .ap_return(okanonas_U0_ap_return)
);

ps2ip_fifo ps2ip_fifo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ps2ip_fifo_U0_ap_start),
    .ap_done(ps2ip_fifo_U0_ap_done),
    .ap_continue(ps2ip_fifo_U0_ap_continue),
    .ap_idle(ps2ip_fifo_U0_ap_idle),
    .ap_ready(ps2ip_fifo_U0_ap_ready),
    .slaveIn_TVALID(slaveIn_TVALID),
    .slaveIn_TDATA(slaveIn_TDATA),
    .slaveIn_TREADY(ps2ip_fifo_U0_slaveIn_TREADY),
    .slaveIn_TSTRB(slaveIn_TSTRB),
    .slaveIn_TLAST(slaveIn_TLAST),
    .ps2ipFifo_V_data_V_din(ps2ip_fifo_U0_ps2ipFifo_V_data_V_din),
    .ps2ipFifo_V_data_V_full_n(ps2ipFifo_V_data_V_full_n),
    .ps2ipFifo_V_data_V_write(ps2ip_fifo_U0_ps2ipFifo_V_data_V_write),
    .ps2ipFifo_V_strb_V_din(ps2ip_fifo_U0_ps2ipFifo_V_strb_V_din),
    .ps2ipFifo_V_strb_V_full_n(ps2ipFifo_V_strb_V_full_n),
    .ps2ipFifo_V_strb_V_write(ps2ip_fifo_U0_ps2ipFifo_V_strb_V_write),
    .ps2ipFifo_V_last_V_din(ps2ip_fifo_U0_ps2ipFifo_V_last_V_din),
    .ps2ipFifo_V_last_V_full_n(ps2ipFifo_V_last_V_full_n),
    .ps2ipFifo_V_last_V_write(ps2ip_fifo_U0_ps2ipFifo_V_last_V_write)
);

core core_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(core_U0_ap_start),
    .start_full_n(core_U0_start_full_n),
    .ap_done(core_U0_ap_done),
    .ap_continue(core_U0_ap_continue),
    .ap_idle(core_U0_ap_idle),
    .ap_ready(core_U0_ap_ready),
    .rule1cnt_V_buf_dout(rule1cnt_V_buf_c_dout),
    .rule1cnt_V_buf_empty_n(rule1cnt_V_buf_c_empty_n),
    .rule1cnt_V_buf_read(core_U0_rule1cnt_V_buf_read),
    .rule2cnt_V_buf_dout(rule2cnt_V_buf_c_dout),
    .rule2cnt_V_buf_empty_n(rule2cnt_V_buf_c_empty_n),
    .rule2cnt_V_buf_read(core_U0_rule2cnt_V_buf_read),
    .rule3cnt_V_buf_dout(rule3cnt_V_buf_c_dout),
    .rule3cnt_V_buf_empty_n(rule3cnt_V_buf_c_empty_n),
    .rule3cnt_V_buf_read(core_U0_rule3cnt_V_buf_read),
    .rule1cnt_V_buf_out_din(core_U0_rule1cnt_V_buf_out_din),
    .rule1cnt_V_buf_out_full_n(rule1cnt_V_buf_c31_full_n),
    .rule1cnt_V_buf_out_write(core_U0_rule1cnt_V_buf_out_write),
    .rule2cnt_V_buf_out_din(core_U0_rule2cnt_V_buf_out_din),
    .rule2cnt_V_buf_out_full_n(rule2cnt_V_buf_c32_full_n),
    .rule2cnt_V_buf_out_write(core_U0_rule2cnt_V_buf_out_write),
    .rule3cnt_V_buf_out_din(core_U0_rule3cnt_V_buf_out_din),
    .rule3cnt_V_buf_out_full_n(rule3cnt_V_buf_c33_full_n),
    .rule3cnt_V_buf_out_write(core_U0_rule3cnt_V_buf_out_write),
    .start_out(core_U0_start_out),
    .start_write(core_U0_start_write),
    .p_read(regrule1_V_channel_dout),
    .p_read1(regrule2_V_channel_dout),
    .p_read2(regrule3_V_channel_dout),
    .ps2ipFifo_V_data_V_dout(ps2ipFifo_V_data_V_dout),
    .ps2ipFifo_V_data_V_empty_n(ps2ipFifo_V_data_V_empty_n),
    .ps2ipFifo_V_data_V_read(core_U0_ps2ipFifo_V_data_V_read),
    .ps2ipFifo_V_strb_V_dout(ps2ipFifo_V_strb_V_dout),
    .ps2ipFifo_V_strb_V_empty_n(ps2ipFifo_V_strb_V_empty_n),
    .ps2ipFifo_V_strb_V_read(core_U0_ps2ipFifo_V_strb_V_read),
    .ps2ipFifo_V_last_V_dout(ps2ipFifo_V_last_V_dout),
    .ps2ipFifo_V_last_V_empty_n(ps2ipFifo_V_last_V_empty_n),
    .ps2ipFifo_V_last_V_read(core_U0_ps2ipFifo_V_last_V_read),
    .ip2psFifo_V_data_V_din(core_U0_ip2psFifo_V_data_V_din),
    .ip2psFifo_V_data_V_full_n(ip2psFifo_V_data_V_full_n),
    .ip2psFifo_V_data_V_write(core_U0_ip2psFifo_V_data_V_write),
    .ip2psFifo_V_strb_V_din(core_U0_ip2psFifo_V_strb_V_din),
    .ip2psFifo_V_strb_V_full_n(ip2psFifo_V_strb_V_full_n),
    .ip2psFifo_V_strb_V_write(core_U0_ip2psFifo_V_strb_V_write),
    .ip2psFifo_V_last_V_din(core_U0_ip2psFifo_V_last_V_din),
    .ip2psFifo_V_last_V_full_n(ip2psFifo_V_last_V_full_n),
    .ip2psFifo_V_last_V_write(core_U0_ip2psFifo_V_last_V_write)
);

okanonas284 okanonas284_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(okanonas284_U0_ap_start),
    .ap_done(okanonas284_U0_ap_done),
    .ap_continue(okanonas284_U0_ap_continue),
    .ap_idle(okanonas284_U0_ap_idle),
    .ap_ready(okanonas284_U0_ap_ready),
    .rule1cnt_V_buf_dout(rule1cnt_V_buf_c31_dout),
    .rule1cnt_V_buf_empty_n(rule1cnt_V_buf_c31_empty_n),
    .rule1cnt_V_buf_read(okanonas284_U0_rule1cnt_V_buf_read)
);

okanonas285 okanonas285_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(okanonas285_U0_ap_start),
    .ap_done(okanonas285_U0_ap_done),
    .ap_continue(okanonas285_U0_ap_continue),
    .ap_idle(okanonas285_U0_ap_idle),
    .ap_ready(okanonas285_U0_ap_ready),
    .rule2cnt_V_buf_dout(rule2cnt_V_buf_c32_dout),
    .rule2cnt_V_buf_empty_n(rule2cnt_V_buf_c32_empty_n),
    .rule2cnt_V_buf_read(okanonas285_U0_rule2cnt_V_buf_read)
);

okanonas2 okanonas2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(okanonas2_U0_ap_start),
    .ap_done(okanonas2_U0_ap_done),
    .ap_continue(okanonas2_U0_ap_continue),
    .ap_idle(okanonas2_U0_ap_idle),
    .ap_ready(okanonas2_U0_ap_ready),
    .rule3cnt_V_buf_dout(rule3cnt_V_buf_c33_dout),
    .rule3cnt_V_buf_empty_n(rule3cnt_V_buf_c33_empty_n),
    .rule3cnt_V_buf_read(okanonas2_U0_rule3cnt_V_buf_read)
);

ip2ps_fifo ip2ps_fifo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ip2ps_fifo_U0_ap_start),
    .ap_done(ip2ps_fifo_U0_ap_done),
    .ap_continue(ip2ps_fifo_U0_ap_continue),
    .ap_idle(ip2ps_fifo_U0_ap_idle),
    .ap_ready(ip2ps_fifo_U0_ap_ready),
    .masterOut_TREADY(masterOut_TREADY),
    .masterOut_TDATA(ip2ps_fifo_U0_masterOut_TDATA),
    .masterOut_TVALID(ip2ps_fifo_U0_masterOut_TVALID),
    .masterOut_TSTRB(ip2ps_fifo_U0_masterOut_TSTRB),
    .masterOut_TLAST(ip2ps_fifo_U0_masterOut_TLAST),
    .ip2psFifo_V_data_V_dout(ip2psFifo_V_data_V_dout),
    .ip2psFifo_V_data_V_empty_n(ip2psFifo_V_data_V_empty_n),
    .ip2psFifo_V_data_V_read(ip2ps_fifo_U0_ip2psFifo_V_data_V_read),
    .ip2psFifo_V_strb_V_dout(ip2psFifo_V_strb_V_dout),
    .ip2psFifo_V_strb_V_empty_n(ip2psFifo_V_strb_V_empty_n),
    .ip2psFifo_V_strb_V_read(ip2ps_fifo_U0_ip2psFifo_V_strb_V_read),
    .ip2psFifo_V_last_V_dout(ip2psFifo_V_last_V_dout),
    .ip2psFifo_V_last_V_empty_n(ip2psFifo_V_last_V_empty_n),
    .ip2psFifo_V_last_V_read(ip2ps_fifo_U0_ip2psFifo_V_last_V_read)
);

fifo_w32_d1_A rule1_V_c1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(my_ip_hls_entry3_U0_rule1_V_out_din),
    .if_full_n(rule1_V_c1_full_n),
    .if_write(my_ip_hls_entry3_U0_rule1_V_out_write),
    .if_dout(rule1_V_c1_dout),
    .if_empty_n(rule1_V_c1_empty_n),
    .if_read(my_ip_hls_entry90_U0_rule1_V_read)
);

fifo_w32_d1_A rule2_V_c2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(my_ip_hls_entry3_U0_rule2_V_out_din),
    .if_full_n(rule2_V_c2_full_n),
    .if_write(my_ip_hls_entry3_U0_rule2_V_out_write),
    .if_dout(rule2_V_c2_dout),
    .if_empty_n(rule2_V_c2_empty_n),
    .if_read(my_ip_hls_entry90_U0_rule2_V_read)
);

fifo_w32_d1_A rule3_V_c3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(my_ip_hls_entry3_U0_rule3_V_out_din),
    .if_full_n(rule3_V_c3_full_n),
    .if_write(my_ip_hls_entry3_U0_rule3_V_out_write),
    .if_dout(rule3_V_c3_dout),
    .if_empty_n(rule3_V_c3_empty_n),
    .if_read(my_ip_hls_entry90_U0_rule3_V_read)
);

fifo_w32_d1_A rule1cnt_V_c4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(my_ip_hls_entry3_U0_rule1cnt_V_out_din),
    .if_full_n(rule1cnt_V_c4_full_n),
    .if_write(my_ip_hls_entry3_U0_rule1cnt_V_out_write),
    .if_dout(rule1cnt_V_c4_dout),
    .if_empty_n(rule1cnt_V_c4_empty_n),
    .if_read(my_ip_hls_entry90_U0_rule1cnt_V_read)
);

fifo_w32_d1_A rule2cnt_V_c5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(my_ip_hls_entry3_U0_rule2cnt_V_out_din),
    .if_full_n(rule2cnt_V_c5_full_n),
    .if_write(my_ip_hls_entry3_U0_rule2cnt_V_out_write),
    .if_dout(rule2cnt_V_c5_dout),
    .if_empty_n(rule2cnt_V_c5_empty_n),
    .if_read(my_ip_hls_entry90_U0_rule2cnt_V_read)
);

fifo_w32_d1_A rule3cnt_V_c6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(my_ip_hls_entry3_U0_rule3cnt_V_out_din),
    .if_full_n(rule3cnt_V_c6_full_n),
    .if_write(my_ip_hls_entry3_U0_rule3cnt_V_out_write),
    .if_dout(rule3cnt_V_c6_dout),
    .if_empty_n(rule3cnt_V_c6_empty_n),
    .if_read(my_ip_hls_entry90_U0_rule3cnt_V_read)
);

fifo_w32_d1_A rule1_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(my_ip_hls_entry90_U0_rule1_V_out_din),
    .if_full_n(rule1_V_c_full_n),
    .if_write(my_ip_hls_entry90_U0_rule1_V_out_write),
    .if_dout(rule1_V_c_dout),
    .if_empty_n(rule1_V_c_empty_n),
    .if_read(okanonas82_U0_rule_V_read)
);

fifo_w32_d1_A rule2_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(my_ip_hls_entry90_U0_rule2_V_out_din),
    .if_full_n(rule2_V_c_full_n),
    .if_write(my_ip_hls_entry90_U0_rule2_V_out_write),
    .if_dout(rule2_V_c_dout),
    .if_empty_n(rule2_V_c_empty_n),
    .if_read(okanonas83_U0_rule_V_read)
);

fifo_w32_d1_A rule3_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(my_ip_hls_entry90_U0_rule3_V_out_din),
    .if_full_n(rule3_V_c_full_n),
    .if_write(my_ip_hls_entry90_U0_rule3_V_out_write),
    .if_dout(rule3_V_c_dout),
    .if_empty_n(rule3_V_c_empty_n),
    .if_read(okanonas_U0_rule_V_read)
);

fifo_w32_d1_A rule1cnt_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(my_ip_hls_entry90_U0_rule1cnt_V_out_din),
    .if_full_n(rule1cnt_V_c_full_n),
    .if_write(my_ip_hls_entry90_U0_rule1cnt_V_out_write),
    .if_dout(rule1cnt_V_c_dout),
    .if_empty_n(rule1cnt_V_c_empty_n),
    .if_read(Block_codeRepl6_proc_U0_rule1cnt_V_read)
);

fifo_w32_d1_A rule2cnt_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(my_ip_hls_entry90_U0_rule2cnt_V_out_din),
    .if_full_n(rule2cnt_V_c_full_n),
    .if_write(my_ip_hls_entry90_U0_rule2cnt_V_out_write),
    .if_dout(rule2cnt_V_c_dout),
    .if_empty_n(rule2cnt_V_c_empty_n),
    .if_read(Block_codeRepl6_proc_U0_rule2cnt_V_read)
);

fifo_w32_d1_A rule3cnt_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(my_ip_hls_entry90_U0_rule3cnt_V_out_din),
    .if_full_n(rule3cnt_V_c_full_n),
    .if_write(my_ip_hls_entry90_U0_rule3cnt_V_out_write),
    .if_dout(rule3cnt_V_c_dout),
    .if_empty_n(rule3cnt_V_c_empty_n),
    .if_read(Block_codeRepl6_proc_U0_rule3cnt_V_read)
);

fifo_w32_d1_A rule3cnt_V_buf_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl6_proc_U0_rule3cnt_V_buf_out_din),
    .if_full_n(rule3cnt_V_buf_c_full_n),
    .if_write(Block_codeRepl6_proc_U0_rule3cnt_V_buf_out_write),
    .if_dout(rule3cnt_V_buf_c_dout),
    .if_empty_n(rule3cnt_V_buf_c_empty_n),
    .if_read(core_U0_rule3cnt_V_buf_read)
);

fifo_w32_d1_A rule2cnt_V_buf_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl6_proc_U0_rule2cnt_V_buf_out_din),
    .if_full_n(rule2cnt_V_buf_c_full_n),
    .if_write(Block_codeRepl6_proc_U0_rule2cnt_V_buf_out_write),
    .if_dout(rule2cnt_V_buf_c_dout),
    .if_empty_n(rule2cnt_V_buf_c_empty_n),
    .if_read(core_U0_rule2cnt_V_buf_read)
);

fifo_w32_d1_A rule1cnt_V_buf_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_codeRepl6_proc_U0_rule1cnt_V_buf_out_din),
    .if_full_n(rule1cnt_V_buf_c_full_n),
    .if_write(Block_codeRepl6_proc_U0_rule1cnt_V_buf_out_write),
    .if_dout(rule1cnt_V_buf_c_dout),
    .if_empty_n(rule1cnt_V_buf_c_empty_n),
    .if_read(core_U0_rule1cnt_V_buf_read)
);

fifo_w32_d2_A regrule1_V_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(okanonas82_U0_ap_return),
    .if_full_n(regrule1_V_channel_full_n),
    .if_write(okanonas82_U0_ap_done),
    .if_dout(regrule1_V_channel_dout),
    .if_empty_n(regrule1_V_channel_empty_n),
    .if_read(core_U0_ap_ready)
);

fifo_w32_d2_A regrule2_V_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(okanonas83_U0_ap_return),
    .if_full_n(regrule2_V_channel_full_n),
    .if_write(okanonas83_U0_ap_done),
    .if_dout(regrule2_V_channel_dout),
    .if_empty_n(regrule2_V_channel_empty_n),
    .if_read(core_U0_ap_ready)
);

fifo_w32_d2_A regrule3_V_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(okanonas_U0_ap_return),
    .if_full_n(regrule3_V_channel_full_n),
    .if_write(okanonas_U0_ap_done),
    .if_dout(regrule3_V_channel_dout),
    .if_empty_n(regrule3_V_channel_empty_n),
    .if_read(core_U0_ap_ready)
);

fifo_w32_d64_A ps2ipFifo_V_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(ps2ip_fifo_U0_ps2ipFifo_V_data_V_din),
    .if_full_n(ps2ipFifo_V_data_V_full_n),
    .if_write(ps2ip_fifo_U0_ps2ipFifo_V_data_V_write),
    .if_dout(ps2ipFifo_V_data_V_dout),
    .if_empty_n(ps2ipFifo_V_data_V_empty_n),
    .if_read(core_U0_ps2ipFifo_V_data_V_read)
);

fifo_w4_d64_A ps2ipFifo_V_strb_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(ps2ip_fifo_U0_ps2ipFifo_V_strb_V_din),
    .if_full_n(ps2ipFifo_V_strb_V_full_n),
    .if_write(ps2ip_fifo_U0_ps2ipFifo_V_strb_V_write),
    .if_dout(ps2ipFifo_V_strb_V_dout),
    .if_empty_n(ps2ipFifo_V_strb_V_empty_n),
    .if_read(core_U0_ps2ipFifo_V_strb_V_read)
);

fifo_w1_d64_A ps2ipFifo_V_last_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(ps2ip_fifo_U0_ps2ipFifo_V_last_V_din),
    .if_full_n(ps2ipFifo_V_last_V_full_n),
    .if_write(ps2ip_fifo_U0_ps2ipFifo_V_last_V_write),
    .if_dout(ps2ipFifo_V_last_V_dout),
    .if_empty_n(ps2ipFifo_V_last_V_empty_n),
    .if_read(core_U0_ps2ipFifo_V_last_V_read)
);

fifo_w32_d1_A rule1cnt_V_buf_c31_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(core_U0_rule1cnt_V_buf_out_din),
    .if_full_n(rule1cnt_V_buf_c31_full_n),
    .if_write(core_U0_rule1cnt_V_buf_out_write),
    .if_dout(rule1cnt_V_buf_c31_dout),
    .if_empty_n(rule1cnt_V_buf_c31_empty_n),
    .if_read(okanonas284_U0_rule1cnt_V_buf_read)
);

fifo_w32_d1_A rule2cnt_V_buf_c32_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(core_U0_rule2cnt_V_buf_out_din),
    .if_full_n(rule2cnt_V_buf_c32_full_n),
    .if_write(core_U0_rule2cnt_V_buf_out_write),
    .if_dout(rule2cnt_V_buf_c32_dout),
    .if_empty_n(rule2cnt_V_buf_c32_empty_n),
    .if_read(okanonas285_U0_rule2cnt_V_buf_read)
);

fifo_w32_d1_A rule3cnt_V_buf_c33_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(core_U0_rule3cnt_V_buf_out_din),
    .if_full_n(rule3cnt_V_buf_c33_full_n),
    .if_write(core_U0_rule3cnt_V_buf_out_write),
    .if_dout(rule3cnt_V_buf_c33_dout),
    .if_empty_n(rule3cnt_V_buf_c33_empty_n),
    .if_read(okanonas2_U0_rule3cnt_V_buf_read)
);

fifo_w32_d64_A ip2psFifo_V_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(core_U0_ip2psFifo_V_data_V_din),
    .if_full_n(ip2psFifo_V_data_V_full_n),
    .if_write(core_U0_ip2psFifo_V_data_V_write),
    .if_dout(ip2psFifo_V_data_V_dout),
    .if_empty_n(ip2psFifo_V_data_V_empty_n),
    .if_read(ip2ps_fifo_U0_ip2psFifo_V_data_V_read)
);

fifo_w4_d64_A ip2psFifo_V_strb_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(core_U0_ip2psFifo_V_strb_V_din),
    .if_full_n(ip2psFifo_V_strb_V_full_n),
    .if_write(core_U0_ip2psFifo_V_strb_V_write),
    .if_dout(ip2psFifo_V_strb_V_dout),
    .if_empty_n(ip2psFifo_V_strb_V_empty_n),
    .if_read(ip2ps_fifo_U0_ip2psFifo_V_strb_V_read)
);

fifo_w1_d64_A ip2psFifo_V_last_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(core_U0_ip2psFifo_V_last_V_din),
    .if_full_n(ip2psFifo_V_last_V_full_n),
    .if_write(core_U0_ip2psFifo_V_last_V_write),
    .if_dout(ip2psFifo_V_last_V_dout),
    .if_empty_n(ip2psFifo_V_last_V_empty_n),
    .if_read(ip2ps_fifo_U0_ip2psFifo_V_last_V_read)
);

start_for_my_ip_hbkb start_for_my_ip_hbkb_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_my_ip_hls_entry90_U0_din),
    .if_full_n(start_for_my_ip_hls_entry90_U0_full_n),
    .if_write(my_ip_hls_entry3_U0_start_write),
    .if_dout(start_for_my_ip_hls_entry90_U0_dout),
    .if_empty_n(start_for_my_ip_hls_entry90_U0_empty_n),
    .if_read(my_ip_hls_entry90_U0_ap_ready)
);

start_for_Block_ccud start_for_Block_ccud_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Block_codeRepl6_proc_U0_din),
    .if_full_n(start_for_Block_codeRepl6_proc_U0_full_n),
    .if_write(my_ip_hls_entry90_U0_start_write),
    .if_dout(start_for_Block_codeRepl6_proc_U0_dout),
    .if_empty_n(start_for_Block_codeRepl6_proc_U0_empty_n),
    .if_read(Block_codeRepl6_proc_U0_ap_ready)
);

start_for_okanonadEe start_for_okanonadEe_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_okanonas82_U0_din),
    .if_full_n(start_for_okanonas82_U0_full_n),
    .if_write(my_ip_hls_entry90_U0_start_write),
    .if_dout(start_for_okanonas82_U0_dout),
    .if_empty_n(start_for_okanonas82_U0_empty_n),
    .if_read(okanonas82_U0_ap_ready)
);

start_for_okanonaeOg start_for_okanonaeOg_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_okanonas83_U0_din),
    .if_full_n(start_for_okanonas83_U0_full_n),
    .if_write(my_ip_hls_entry90_U0_start_write),
    .if_dout(start_for_okanonas83_U0_dout),
    .if_empty_n(start_for_okanonas83_U0_empty_n),
    .if_read(okanonas83_U0_ap_ready)
);

start_for_okanonafYi start_for_okanonafYi_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_okanonas_U0_din),
    .if_full_n(start_for_okanonas_U0_full_n),
    .if_write(my_ip_hls_entry90_U0_start_write),
    .if_dout(start_for_okanonas_U0_dout),
    .if_empty_n(start_for_okanonas_U0_empty_n),
    .if_read(okanonas_U0_ap_ready)
);

start_for_okanonag8j start_for_okanonag8j_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_okanonas284_U0_din),
    .if_full_n(start_for_okanonas284_U0_full_n),
    .if_write(core_U0_start_write),
    .if_dout(start_for_okanonas284_U0_dout),
    .if_empty_n(start_for_okanonas284_U0_empty_n),
    .if_read(okanonas284_U0_ap_ready)
);

start_for_okanonahbi start_for_okanonahbi_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_okanonas285_U0_din),
    .if_full_n(start_for_okanonas285_U0_full_n),
    .if_write(core_U0_start_write),
    .if_dout(start_for_okanonas285_U0_dout),
    .if_empty_n(start_for_okanonas285_U0_empty_n),
    .if_read(okanonas285_U0_ap_ready)
);

start_for_okanonaibs start_for_okanonaibs_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_okanonas2_U0_din),
    .if_full_n(start_for_okanonas2_U0_full_n),
    .if_write(core_U0_start_write),
    .if_dout(start_for_okanonas2_U0_dout),
    .if_empty_n(start_for_okanonas2_U0_empty_n),
    .if_read(okanonas2_U0_ap_ready)
);

start_for_ip2ps_fjbC start_for_ip2ps_fjbC_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_ip2ps_fifo_U0_din),
    .if_full_n(start_for_ip2ps_fifo_U0_full_n),
    .if_write(core_U0_start_write),
    .if_dout(start_for_ip2ps_fifo_U0_dout),
    .if_empty_n(start_for_ip2ps_fifo_U0_empty_n),
    .if_read(ip2ps_fifo_U0_ap_ready)
);

assign Block_codeRepl6_proc_U0_ap_continue = 1'b1;

assign Block_codeRepl6_proc_U0_ap_start = start_for_Block_codeRepl6_proc_U0_empty_n;

assign Block_codeRepl6_proc_U0_start_full_n = 1'b1;

assign Block_codeRepl6_proc_U0_start_write = 1'b0;

assign ap_channel_done_regrule1_V_channel = okanonas82_U0_ap_done;

assign ap_channel_done_regrule2_V_channel = okanonas83_U0_ap_done;

assign ap_channel_done_regrule3_V_channel = okanonas_U0_ap_done;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b0;

assign core_U0_ap_continue = 1'b1;

assign core_U0_ap_start = (regrule3_V_channel_empty_n & regrule2_V_channel_empty_n & regrule1_V_channel_empty_n);

assign core_U0_start_full_n = (start_for_okanonas2_U0_full_n & start_for_okanonas285_U0_full_n & start_for_okanonas284_U0_full_n & start_for_ip2ps_fifo_U0_full_n);

assign ip2ps_fifo_U0_ap_continue = 1'b1;

assign ip2ps_fifo_U0_ap_start = start_for_ip2ps_fifo_U0_empty_n;

assign ip2ps_fifo_U0_start_full_n = 1'b1;

assign ip2ps_fifo_U0_start_write = 1'b0;

assign masterOut_TDATA = ip2ps_fifo_U0_masterOut_TDATA;

assign masterOut_TLAST = ip2ps_fifo_U0_masterOut_TLAST;

assign masterOut_TSTRB = ip2ps_fifo_U0_masterOut_TSTRB;

assign masterOut_TVALID = ip2ps_fifo_U0_masterOut_TVALID;

assign my_ip_hls_entry3_U0_ap_continue = 1'b1;

assign my_ip_hls_entry3_U0_ap_start = 1'b1;

assign my_ip_hls_entry90_U0_ap_continue = 1'b1;

assign my_ip_hls_entry90_U0_ap_start = start_for_my_ip_hls_entry90_U0_empty_n;

assign my_ip_hls_entry90_U0_start_full_n = (start_for_okanonas_U0_full_n & start_for_okanonas83_U0_full_n & start_for_okanonas82_U0_full_n & start_for_Block_codeRepl6_proc_U0_full_n);

assign okanonas284_U0_ap_continue = 1'b1;

assign okanonas284_U0_ap_start = start_for_okanonas284_U0_empty_n;

assign okanonas284_U0_start_full_n = 1'b1;

assign okanonas284_U0_start_write = 1'b0;

assign okanonas285_U0_ap_continue = 1'b1;

assign okanonas285_U0_ap_start = start_for_okanonas285_U0_empty_n;

assign okanonas285_U0_start_full_n = 1'b1;

assign okanonas285_U0_start_write = 1'b0;

assign okanonas2_U0_ap_continue = 1'b1;

assign okanonas2_U0_ap_start = start_for_okanonas2_U0_empty_n;

assign okanonas2_U0_start_full_n = 1'b1;

assign okanonas2_U0_start_write = 1'b0;

assign okanonas82_U0_ap_continue = regrule1_V_channel_full_n;

assign okanonas82_U0_ap_start = start_for_okanonas82_U0_empty_n;

assign okanonas82_U0_start_full_n = 1'b1;

assign okanonas82_U0_start_write = 1'b0;

assign okanonas83_U0_ap_continue = regrule2_V_channel_full_n;

assign okanonas83_U0_ap_start = start_for_okanonas83_U0_empty_n;

assign okanonas83_U0_start_full_n = 1'b1;

assign okanonas83_U0_start_write = 1'b0;

assign okanonas_U0_ap_continue = regrule3_V_channel_full_n;

assign okanonas_U0_ap_start = start_for_okanonas_U0_empty_n;

assign okanonas_U0_start_full_n = 1'b1;

assign okanonas_U0_start_write = 1'b0;

assign ps2ip_fifo_U0_ap_continue = 1'b1;

assign ps2ip_fifo_U0_ap_start = 1'b1;

assign ps2ip_fifo_U0_start_full_n = 1'b1;

assign ps2ip_fifo_U0_start_write = 1'b0;

assign slaveIn_TREADY = ps2ip_fifo_U0_slaveIn_TREADY;

assign start_for_Block_codeRepl6_proc_U0_din = 1'b1;

assign start_for_ip2ps_fifo_U0_din = 1'b1;

assign start_for_my_ip_hls_entry90_U0_din = 1'b1;

assign start_for_okanonas284_U0_din = 1'b1;

assign start_for_okanonas285_U0_din = 1'b1;

assign start_for_okanonas2_U0_din = 1'b1;

assign start_for_okanonas82_U0_din = 1'b1;

assign start_for_okanonas83_U0_din = 1'b1;

assign start_for_okanonas_U0_din = 1'b1;

endmodule //my_ip_hls
