// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Block_codeRepl6_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        rule3cnt_V_dout,
        rule3cnt_V_empty_n,
        rule3cnt_V_read,
        rule2cnt_V_dout,
        rule2cnt_V_empty_n,
        rule2cnt_V_read,
        rule1cnt_V_dout,
        rule1cnt_V_empty_n,
        rule1cnt_V_read,
        rule3cnt_V_buf_out_din,
        rule3cnt_V_buf_out_full_n,
        rule3cnt_V_buf_out_write,
        rule2cnt_V_buf_out_din,
        rule2cnt_V_buf_out_full_n,
        rule2cnt_V_buf_out_write,
        rule1cnt_V_buf_out_din,
        rule1cnt_V_buf_out_full_n,
        rule1cnt_V_buf_out_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] rule3cnt_V_dout;
input   rule3cnt_V_empty_n;
output   rule3cnt_V_read;
input  [31:0] rule2cnt_V_dout;
input   rule2cnt_V_empty_n;
output   rule2cnt_V_read;
input  [31:0] rule1cnt_V_dout;
input   rule1cnt_V_empty_n;
output   rule1cnt_V_read;
output  [31:0] rule3cnt_V_buf_out_din;
input   rule3cnt_V_buf_out_full_n;
output   rule3cnt_V_buf_out_write;
output  [31:0] rule2cnt_V_buf_out_din;
input   rule2cnt_V_buf_out_full_n;
output   rule2cnt_V_buf_out_write;
output  [31:0] rule1cnt_V_buf_out_din;
input   rule1cnt_V_buf_out_full_n;
output   rule1cnt_V_buf_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg rule3cnt_V_read;
reg rule2cnt_V_read;
reg rule1cnt_V_read;
reg rule3cnt_V_buf_out_write;
reg rule2cnt_V_buf_out_write;
reg rule1cnt_V_buf_out_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    rule3cnt_V_blk_n;
reg    rule2cnt_V_blk_n;
reg    rule1cnt_V_blk_n;
reg    rule3cnt_V_buf_out_blk_n;
reg    rule2cnt_V_buf_out_blk_n;
reg    rule1cnt_V_buf_out_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (rule1cnt_V_buf_out_full_n == 1'b0) | (rule2cnt_V_buf_out_full_n == 1'b0) | (rule3cnt_V_buf_out_full_n == 1'b0) | (rule1cnt_V_empty_n == 1'b0) | (rule2cnt_V_empty_n == 1'b0) | (rule3cnt_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (rule1cnt_V_buf_out_full_n == 1'b0) | (rule2cnt_V_buf_out_full_n == 1'b0) | (rule3cnt_V_buf_out_full_n == 1'b0) | (rule1cnt_V_empty_n == 1'b0) | (rule2cnt_V_empty_n == 1'b0) | (rule3cnt_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (rule1cnt_V_buf_out_full_n == 1'b0) | (rule2cnt_V_buf_out_full_n == 1'b0) | (rule3cnt_V_buf_out_full_n == 1'b0) | (rule1cnt_V_empty_n == 1'b0) | (rule2cnt_V_empty_n == 1'b0) | (rule3cnt_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        rule1cnt_V_blk_n = rule1cnt_V_empty_n;
    end else begin
        rule1cnt_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        rule1cnt_V_buf_out_blk_n = rule1cnt_V_buf_out_full_n;
    end else begin
        rule1cnt_V_buf_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (rule1cnt_V_buf_out_full_n == 1'b0) | (rule2cnt_V_buf_out_full_n == 1'b0) | (rule3cnt_V_buf_out_full_n == 1'b0) | (rule1cnt_V_empty_n == 1'b0) | (rule2cnt_V_empty_n == 1'b0) | (rule3cnt_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        rule1cnt_V_buf_out_write = 1'b1;
    end else begin
        rule1cnt_V_buf_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (rule1cnt_V_buf_out_full_n == 1'b0) | (rule2cnt_V_buf_out_full_n == 1'b0) | (rule3cnt_V_buf_out_full_n == 1'b0) | (rule1cnt_V_empty_n == 1'b0) | (rule2cnt_V_empty_n == 1'b0) | (rule3cnt_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        rule1cnt_V_read = 1'b1;
    end else begin
        rule1cnt_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        rule2cnt_V_blk_n = rule2cnt_V_empty_n;
    end else begin
        rule2cnt_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        rule2cnt_V_buf_out_blk_n = rule2cnt_V_buf_out_full_n;
    end else begin
        rule2cnt_V_buf_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (rule1cnt_V_buf_out_full_n == 1'b0) | (rule2cnt_V_buf_out_full_n == 1'b0) | (rule3cnt_V_buf_out_full_n == 1'b0) | (rule1cnt_V_empty_n == 1'b0) | (rule2cnt_V_empty_n == 1'b0) | (rule3cnt_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        rule2cnt_V_buf_out_write = 1'b1;
    end else begin
        rule2cnt_V_buf_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (rule1cnt_V_buf_out_full_n == 1'b0) | (rule2cnt_V_buf_out_full_n == 1'b0) | (rule3cnt_V_buf_out_full_n == 1'b0) | (rule1cnt_V_empty_n == 1'b0) | (rule2cnt_V_empty_n == 1'b0) | (rule3cnt_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        rule2cnt_V_read = 1'b1;
    end else begin
        rule2cnt_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        rule3cnt_V_blk_n = rule3cnt_V_empty_n;
    end else begin
        rule3cnt_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        rule3cnt_V_buf_out_blk_n = rule3cnt_V_buf_out_full_n;
    end else begin
        rule3cnt_V_buf_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (rule1cnt_V_buf_out_full_n == 1'b0) | (rule2cnt_V_buf_out_full_n == 1'b0) | (rule3cnt_V_buf_out_full_n == 1'b0) | (rule1cnt_V_empty_n == 1'b0) | (rule2cnt_V_empty_n == 1'b0) | (rule3cnt_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        rule3cnt_V_buf_out_write = 1'b1;
    end else begin
        rule3cnt_V_buf_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (rule1cnt_V_buf_out_full_n == 1'b0) | (rule2cnt_V_buf_out_full_n == 1'b0) | (rule3cnt_V_buf_out_full_n == 1'b0) | (rule1cnt_V_empty_n == 1'b0) | (rule2cnt_V_empty_n == 1'b0) | (rule3cnt_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        rule3cnt_V_read = 1'b1;
    end else begin
        rule3cnt_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (rule1cnt_V_buf_out_full_n == 1'b0) | (rule2cnt_V_buf_out_full_n == 1'b0) | (rule3cnt_V_buf_out_full_n == 1'b0) | (rule1cnt_V_empty_n == 1'b0) | (rule2cnt_V_empty_n == 1'b0) | (rule3cnt_V_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign rule1cnt_V_buf_out_din = rule1cnt_V_dout;

assign rule2cnt_V_buf_out_din = rule2cnt_V_dout;

assign rule3cnt_V_buf_out_din = rule3cnt_V_dout;

endmodule //Block_codeRepl6_proc
